#**CODE-2:**

In [0]:
'''
CODE-2: TO GET FINAL DATAMATRIX FOR SATELLITE DATA 
           AFTER IMPUTATION FOR KNOWN GROUND LOCATIONS
==========================================================================================
TO DO/RELOOK:
-> Know the extents of individual locations on ground
-> Recheck the final datamatrix as sorting in ascending form is used for further codes

INPUT DATA      : MYD04_3K
TIME PERIOD     : 01 Jan - 31 Mar, 2016 - 2020  
INPUT           : chennai_df
OUTPUT          : chennai_sat_data_df, pixel_count_sat_data

==========================================================================================
'''

'\nCODE-2: TO GET FINAL DATAMATRIX FOR SATELLITE DATA \n           AFTER IMPUTATION FOR KNOWN GROUND LOCATIONS\n==========================================================================================\nTO DO/RELOOK:\n-> Know the extents of individual locations on ground\n-> Recheck the final datamatrix as sorting in ascending form is used for further codes\n\nINPUT DATA      : MYD04_3K\nTIME PERIOD     : 01 Jan - 31 Mar, 2016 - 2020  \nINPUT           : chennai_df\nOUTPUT          : chennai_sat_data_df, pixel_count_sat_data\n\n==========================================================================================\n'

In [0]:
'''
PLACE         LAT1     LAT2    LON1    LON2
alandur,     12.9927,13.0084,80.1886,80.2099
velachery,   12.9609,12.9975,80.2029,80.2336
manali,      13.1467,13.2052,80.2496,80.2959
kilpauk,     13.0747,13.0930,80.2272,80.2506
annanagar,   13.0766,13.1035,80.1968,80.2183
tnagar,      13.0310,13.0534,80.2263,80.2510
adyar,       12.9899,13.0232,80.2405,80.2780
nungambakam, 13.0508,13.0715,80.2313,80.2544

We use only first 3 places
'''

In [0]:
pip install datawig

In [0]:
from datetime import datetime
import pandas as pd
import datawig  #for imputation
import numpy as np

In [0]:
#Reading code-1 file
chennai_new_df = pd.read_csv('/content/chennai_final_raw_sat_data_modis.csv')
chennai_new_df.head()

   Unnamed: 0    Year  ...  Land_sea_Flag  Land_Ocean_Quality_Flag
0       31201  2016.0  ...            0.0                  -9999.0
1       31652  2016.0  ...            0.0                  -9999.0
2       31653  2016.0  ...            1.0                  -9999.0
3       31654  2016.0  ...            1.0                  -9999.0
4       32103  2016.0  ...            0.0                  -9999.0

[5 rows x 13 columns]

In [0]:
#creating a time stamp for easy viewing of date and time
chennai_new_df["time_stamp"] = ''
i=0
for i in range(len(chennai_new_df)):
    chennai_new_df.iloc[i,13] = datetime(int(chennai_new_df.iloc[i,1]),int(chennai_new_df.iloc[i,2]),
                                       int(chennai_new_df.iloc[i,3]), int(chennai_new_df.iloc[i,4]),
                                       int(chennai_new_df.iloc[i,5]),int(chennai_new_df.iloc[i,6]))

In [0]:
# Marking respective regions based on lat long extent
def places_satellite_data(str, lat1,lat2,lon1,lon2):
    region = chennai_new_df[(chennai_new_df['Latitude'] > lat1) & (chennai_new_df['Latitude'] < lat2) & (chennai_new_df['Longitude'] > lon1) & (chennai_new_df['Longitude'] < lon2)]
    region['Place'] = str
    return region

In [0]:
#calling 'places_satellite_data'  function
Alandur     = places_satellite_data('Alandur', 12.99,13.01,80.18,80.21)
Velachery   = places_satellite_data('Velachery', 12.96,13.00, 80.20,80.23)
Manali      = places_satellite_data('Manali', 13.14, 13.21, 80.24, 80.30)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [0]:
#merging all dataframes together
dflist = [Alandur, Velachery, Manali ]
chennai_sat_data_df = pd.DataFrame()
for f in dflist:
    chennai_sat_data_df = chennai_sat_data_df.append(f)
chennai_sat_data_df.head()

     Unnamed: 0    Year  ...           time_stamp    Place
35        28849  2016.0  ...  2016-01-02 13:00:37  Alandur
54       199062  2016.0  ...  2016-01-03 13:43:24  Alandur
95        61164  2016.0  ...  2016-01-05 13:31:08  Alandur
209      268920  2016.0  ...  2016-01-10 13:49:32  Alandur
249      132819  2016.0  ...  2016-01-12 13:37:18  Alandur

[5 rows x 15 columns]

### Miscellaneous operations

In [0]:
#for similar time intervals as ground data i.e. for every 15 mins
chennai_sat_data_df['RoundedMinute'] = ""
#to round satellite time in minutes to every 15mins similar to cpcb
chennai_sat_data_df['RoundedMinute'] = pd.cut(x=chennai_sat_data_df['Minute'], bins=[0, 15, 30, 45, 59], labels=['0','15','30','45'])
#for minutes with 0 fill rounded minutes with 0
chennai_sat_data_df['RoundedMinute'].replace(np.nan, 0, inplace=True)
chennai_sat_data_df['RoundedMinute'] = chennai_sat_data_df['RoundedMinute'].astype(int)

In [0]:
#sorting values according to date   
chennai_sat_data_df = chennai_sat_data_df.sort_values(['Year', 'Month', 'Day', 'Hour', 'RoundedMinute','Place'], ascending=[True, True, True, True, True, True])
#rearranging columns
chennai_sat_data_df = chennai_sat_data_df.reindex(columns=['Year','Month','Hour','Day','RoundedMinute','Latitude','Longitude', 'Place',
                                                           'time_stamp','updated_AOD_Land_and_Ocean_datawig','Optical_Depth_Land_And_Ocean',
                                                           'Image_Optical_Depth_Land_And_Ocean','Land_sea_Flag','Land_Ocean_Quality_Flag'])

In [0]:
#reindexing dataframe
chennai_sat_data_df.reset_index(drop=True, inplace=True)

In [0]:
#to get number of pixels for each day(same hour and minute) for a particular place 
pixel_count_sat_data = [] 
pixel_count_sat_data = chennai_sat_data_df.groupby(['Year','Month', 'Day','Hour','RoundedMinute','Place']).size().reset_index(name='count')

In [0]:
chennai_sat_data_df.head()

### Imputation of Image Optical Depth

In [0]:
#1. Dividing into year-wise data for imputation
def year_wise(str, year):
     return chennai_sat_data_df[chennai_sat_data_df[str] == year]  
yr_2016 = year_wise('Year', 2016)
yr_2017 = year_wise('Year', 2017)
yr_2018 = year_wise('Year', 2018)
yr_2019 = year_wise('Year', 2019)
yr_2020 = year_wise('Year', 2020)

In [0]:
# 2.IMPUTATION
#df - yearwise dataframe to be imputed, str - column name
#month_num - month number, null_value - null value that is to be refilled 
#Imputation is done for every month, in a certain place, based on weights(distance) of latitude and longitude 
#Haversine formula is not included to make things simpler

In [0]:
def imputation_AOD(df):
    
    def month_wise_df(df, month_num, str, null_value):
        df_mon = df[df['Month'] == month_num]
        
        x_columns = ['Latitude', 'Longitude', 'Place', 'Year']
        
        value = df_mon[df_mon[str] != null_value]
        no_value = df_mon[df_mon[str] == null_value]
        
        imputer = datawig.SimpleImputer(
            input_columns = x_columns, # column(s) containing information about the column we want to impute
            output_column = str, # the column we'd like to impute values for
            output_path = 'datawig_imputation' # stores model data and metrics
            )
        imputer.fit(train_df = value, num_epochs = 120)
        imputed = imputer.predict(no_value)
        imputed.head()
        
        datawig_imputation_data = list()
        predictions = np.asarray(imputed['Image_Optical_Depth_Land_And_Ocean_imputed'])
        cnt = 0
        for i in range(df_mon.shape[0]):
            if(df_mon.iloc[i][str] == null_value):
                datawig_imputation_data.append(predictions[cnt])
                cnt+=1
            else:
                datawig_imputation_data.append(df_mon.iloc[i][str])
        print(cnt,"rows have been imputed")
        df_mon['updated_AOD_Land_and_Ocean_datawig'] = np.asarray(datawig_imputation_data)
        
        return df_mon
        
    mon_1 = month_wise_df(df, 1, 'Image_Optical_Depth_Land_And_Ocean', -9999)
    mon_2 = month_wise_df(df, 2, 'Image_Optical_Depth_Land_And_Ocean', -9999)
    mon_3 = month_wise_df(df, 3, 'Image_Optical_Depth_Land_And_Ocean', -9999)
    
    month_dflist = [mon_1, mon_2, mon_3]
    imputed_monthwise_df = pd.DataFrame()
    for mon in month_dflist:
        imputed_monthwise_df = imputed_monthwise_df.append(mon)
        
    return imputed_monthwise_df

In [0]:
#calling Imputation AOD function
yr_2016_imputed = imputation_AOD(yr_2016)
yr_2017_imputed = imputation_AOD(yr_2017)
yr_2018_imputed = imputation_AOD(yr_2018)
yr_2019_imputed = imputation_AOD(yr_2019)
yr_2020_imputed = imputation_AOD(yr_2020)

2020-06-08 08:01:49,310 [INFO]
========== start: fit model
2020-06-08 08:01:49,314 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:01:49,353 [INFO]  Epoch[0] Batch [0-1]	Speed: 993.90 samples/sec	cross-entropy=17.825206	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,355 [INFO]  Epoch[0] Train-cross-entropy=17.825206
2020-06-08 08:01:49,356 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,358 [INFO]  Epoch[0] Time cost=0.039
2020-06-08 08:01:49,364 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:01:49,381 [INFO]  Epoch[0] Validation-cross-entropy=32.053574
2020-06-08 08:01:49,383 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,419 [INFO]  Epoch[1] Batch [0-1]	Speed: 990.39 samples/sec	cross-entropy=15.414490	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,421 [INFO]  Epoch[1] Train-cross-entropy=15.414490
2020-06-08 08:01:49,423 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,424 [INFO]  Epoch[1] Time cost=0.039
2020-06-08 08:01:49,428 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:01:49,449 [INFO]  Epoch[1] Validation-cross-entropy=32.075935
2020-06-08 08:01:49,450 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,487 [INFO]  Epoch[2] Batch [0-1]	Speed: 982.30 samples/sec	cross-entropy=14.158165	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,488 [INFO]  Epoch[2] Train-cross-entropy=14.158165
2020-06-08 08:01:49,490 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,492 [INFO]  Epoch[2] Time cost=0.040
2020-06-08 08:01:49,500 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:01:49,517 [INFO]  Epoch[2] Validation-cross-entropy=32.567608
2020-06-08 08:01:49,520 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,557 [INFO]  Epoch[3] Batch [0-1]	Speed: 984.12 samples/sec	cross-entropy=13.790178	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,561 [INFO]  Epoch[3] Train-cross-entropy=13.790178
2020-06-08 08:01:49,564 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,566 [INFO]  Epoch[3] Time cost=0.042
2020-06-08 08:01:49,570 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:01:49,590 [INFO]  Epoch[3] Validation-cross-entropy=33.280235
2020-06-08 08:01:49,594 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,642 [INFO]  Epoch[4] Batch [0-1]	Speed: 687.52 samples/sec	cross-entropy=13.920486	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,644 [INFO]  Epoch[4] Train-cross-entropy=13.920486
2020-06-08 08:01:49,647 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,649 [INFO]  Epoch[4] Time cost=0.053
2020-06-08 08:01:49,653 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:01:49,673 [INFO]  Epoch[4] Validation-cross-entropy=33.854908
2020-06-08 08:01:49,675 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,712 [INFO]  Epoch[5] Batch [0-1]	Speed: 991.43 samples/sec	cross-entropy=14.069002	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,716 [INFO]  Epoch[5] Train-cross-entropy=14.069002
2020-06-08 08:01:49,717 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:49,719 [INFO]  Epoch[5] Time cost=0.042
2020-06-08 08:01:49,724 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:01:49,743 [INFO]  No improvement detected for 5 epochs compared to 32.05357360839844 last error obtained: 34.115821838378906, stopping here
2020-06-08 08:01:49,747 [INFO]
========== done (0.4375433921813965 s) fit model

53 rows have been imputed

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
2020-06-08 08:01:50,122 [INFO]
========== start: fit model
2020-06-08 08:01:50,126 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:01:50,167 [INFO]  Epoch[0] Batch [0-1]	Speed: 971.62 samples/sec	cross-entropy=13.548134	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,169 [INFO]  Epoch[0] Train-cross-entropy=13.548134
2020-06-08 08:01:50,171 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,173 [INFO]  Epoch[0] Time cost=0.040
2020-06-08 08:01:50,179 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:01:50,198 [INFO]  Epoch[0] Validation-cross-entropy=1.434293
2020-06-08 08:01:50,199 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,237 [INFO]  Epoch[1] Batch [0-1]	Speed: 986.04 samples/sec	cross-entropy=12.156722	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,241 [INFO]  Epoch[1] Train-cross-entropy=12.156722
2020-06-08 08:01:50,243 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,247 [INFO]  Epoch[1] Time cost=0.044
2020-06-08 08:01:50,251 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:01:50,269 [INFO]  Epoch[1] Validation-cross-entropy=0.988957
2020-06-08 08:01:50,272 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,309 [INFO]  Epoch[2] Batch [0-1]	Speed: 986.46 samples/sec	cross-entropy=11.508132	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,310 [INFO]  Epoch[2] Train-cross-entropy=11.508132
2020-06-08 08:01:50,312 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,314 [INFO]  Epoch[2] Time cost=0.040
2020-06-08 08:01:50,320 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:01:50,338 [INFO]  Epoch[2] Validation-cross-entropy=0.785012
2020-06-08 08:01:50,340 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,378 [INFO]  Epoch[3] Batch [0-1]	Speed: 976.61 samples/sec	cross-entropy=11.215652	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,379 [INFO]  Epoch[3] Train-cross-entropy=11.215652
2020-06-08 08:01:50,381 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,382 [INFO]  Epoch[3] Time cost=0.040
2020-06-08 08:01:50,387 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:01:50,406 [INFO]  Epoch[3] Validation-cross-entropy=0.784176
2020-06-08 08:01:50,408 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,445 [INFO]  Epoch[4] Batch [0-1]	Speed: 988.70 samples/sec	cross-entropy=11.086434	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,446 [INFO]  Epoch[4] Train-cross-entropy=11.086434
2020-06-08 08:01:50,447 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,449 [INFO]  Epoch[4] Time cost=0.039
2020-06-08 08:01:50,453 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:01:50,474 [INFO]  Epoch[4] Validation-cross-entropy=0.913470
2020-06-08 08:01:50,476 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,517 [INFO]  Epoch[5] Batch [0-1]	Speed: 897.25 samples/sec	cross-entropy=10.996661	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,519 [INFO]  Epoch[5] Train-cross-entropy=10.996661
2020-06-08 08:01:50,521 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,522 [INFO]  Epoch[5] Time cost=0.045
2020-06-08 08:01:50,528 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:01:50,549 [INFO]  Epoch[5] Validation-cross-entropy=1.119509
2020-06-08 08:01:50,550 [INFO]  Epoch[5] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,587 [INFO]  Epoch[6] Batch [0-1]	Speed: 976.67 samples/sec	cross-entropy=10.883736	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,588 [INFO]  Epoch[6] Train-cross-entropy=10.883736
2020-06-08 08:01:50,589 [INFO]  Epoch[6] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,591 [INFO]  Epoch[6] Time cost=0.039
2020-06-08 08:01:50,595 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-08 08:01:50,616 [INFO]  Epoch[6] Validation-cross-entropy=1.376238
2020-06-08 08:01:50,618 [INFO]  Epoch[6] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,655 [INFO]  Epoch[7] Batch [0-1]	Speed: 981.18 samples/sec	cross-entropy=10.743484	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,658 [INFO]  Epoch[7] Train-cross-entropy=10.743484
2020-06-08 08:01:50,660 [INFO]  Epoch[7] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:50,663 [INFO]  Epoch[7] Time cost=0.043
2020-06-08 08:01:50,669 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-08 08:01:50,688 [INFO]  No improvement detected for 5 epochs compared to 0.7850123643875122 last error obtained: 1.6810729503631592, stopping here
2020-06-08 08:01:50,689 [INFO]
========== done (0.5678324699401855 s) fit model

49 rows have been imputed

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
2020-06-08 08:01:51,065 [INFO]
========== start: fit model
2020-06-08 08:01:51,066 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:01:51,128 [INFO]  Epoch[0] Batch [0-2]	Speed: 927.48 samples/sec	cross-entropy=16.574883	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,130 [INFO]  Epoch[0] Train-cross-entropy=16.574883
2020-06-08 08:01:51,133 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,136 [INFO]  Epoch[0] Time cost=0.064
2020-06-08 08:01:51,142 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:01:51,160 [INFO]  Epoch[0] Validation-cross-entropy=23.569040
2020-06-08 08:01:51,162 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,219 [INFO]  Epoch[1] Batch [0-2]	Speed: 942.38 samples/sec	cross-entropy=14.113548	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,220 [INFO]  Epoch[1] Train-cross-entropy=14.113548
2020-06-08 08:01:51,222 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,224 [INFO]  Epoch[1] Time cost=0.059
2020-06-08 08:01:51,230 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:01:51,248 [INFO]  Epoch[1] Validation-cross-entropy=18.450474
2020-06-08 08:01:51,250 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,304 [INFO]  Epoch[2] Batch [0-2]	Speed: 988.05 samples/sec	cross-entropy=13.252647	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,306 [INFO]  Epoch[2] Train-cross-entropy=13.252647
2020-06-08 08:01:51,311 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,312 [INFO]  Epoch[2] Time cost=0.058
2020-06-08 08:01:51,320 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:01:51,338 [INFO]  Epoch[2] Validation-cross-entropy=15.733408
2020-06-08 08:01:51,342 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,395 [INFO]  Epoch[3] Batch [0-2]	Speed: 978.30 samples/sec	cross-entropy=13.084245	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,399 [INFO]  Epoch[3] Train-cross-entropy=13.084245
2020-06-08 08:01:51,403 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,406 [INFO]  Epoch[3] Time cost=0.061
2020-06-08 08:01:51,412 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:01:51,432 [INFO]  Epoch[3] Validation-cross-entropy=14.711618
2020-06-08 08:01:51,436 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,489 [INFO]  Epoch[4] Batch [0-2]	Speed: 977.15 samples/sec	cross-entropy=12.967855	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,494 [INFO]  Epoch[4] Train-cross-entropy=12.967855
2020-06-08 08:01:51,497 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,501 [INFO]  Epoch[4] Time cost=0.061
2020-06-08 08:01:51,508 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:01:51,527 [INFO]  Epoch[4] Validation-cross-entropy=14.764194
2020-06-08 08:01:51,531 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,591 [INFO]  Epoch[5] Batch [0-2]	Speed: 823.84 samples/sec	cross-entropy=12.705270	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,592 [INFO]  Epoch[5] Train-cross-entropy=12.705270
2020-06-08 08:01:51,594 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,598 [INFO]  Epoch[5] Time cost=0.065
2020-06-08 08:01:51,604 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:01:51,621 [INFO]  Epoch[5] Validation-cross-entropy=15.410262
2020-06-08 08:01:51,623 [INFO]  Epoch[5] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,677 [INFO]  Epoch[6] Batch [0-2]	Speed: 985.09 samples/sec	cross-entropy=12.368245	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,681 [INFO]  Epoch[6] Train-cross-entropy=12.368245
2020-06-08 08:01:51,684 [INFO]  Epoch[6] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,687 [INFO]  Epoch[6] Time cost=0.062
2020-06-08 08:01:51,691 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-08 08:01:51,711 [INFO]  Epoch[6] Validation-cross-entropy=16.251545
2020-06-08 08:01:51,715 [INFO]  Epoch[6] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,767 [INFO]  Epoch[7] Batch [0-2]	Speed: 987.93 samples/sec	cross-entropy=12.069923	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,771 [INFO]  Epoch[7] Train-cross-entropy=12.069923
2020-06-08 08:01:51,775 [INFO]  Epoch[7] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,778 [INFO]  Epoch[7] Time cost=0.060
2020-06-08 08:01:51,783 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-08 08:01:51,801 [INFO]  Epoch[7] Validation-cross-entropy=16.978388
2020-06-08 08:01:51,805 [INFO]  Epoch[7] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,859 [INFO]  Epoch[8] Batch [0-2]	Speed: 974.52 samples/sec	cross-entropy=11.847481	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,863 [INFO]  Epoch[8] Train-cross-entropy=11.847481
2020-06-08 08:01:51,866 [INFO]  Epoch[8] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:51,869 [INFO]  Epoch[8] Time cost=0.061
2020-06-08 08:01:51,875 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-08 08:01:51,893 [INFO]  No improvement detected for 5 epochs compared to 14.711618423461914 last error obtained: 17.40690040588379, stopping here
2020-06-08 08:01:51,897 [INFO]
========== done (0.8326997756958008 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

29 rows have been imputed

2020-06-08 08:01:52,252 [INFO]
========== start: fit model
2020-06-08 08:01:52,255 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:01:52,295 [INFO]  Epoch[0] Batch [0-1]	Speed: 998.72 samples/sec	cross-entropy=9.752713	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,297 [INFO]  Epoch[0] Train-cross-entropy=9.752713
2020-06-08 08:01:52,299 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,301 [INFO]  Epoch[0] Time cost=0.039
2020-06-08 08:01:52,306 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:01:52,324 [INFO]  Epoch[0] Validation-cross-entropy=1.348931
2020-06-08 08:01:52,326 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,364 [INFO]  Epoch[1] Batch [0-1]	Speed: 980.64 samples/sec	cross-entropy=9.275238	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,369 [INFO]  Epoch[1] Train-cross-entropy=9.275238
2020-06-08 08:01:52,370 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,373 [INFO]  Epoch[1] Time cost=0.044
2020-06-08 08:01:52,380 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:01:52,398 [INFO]  Epoch[1] Validation-cross-entropy=2.143006
2020-06-08 08:01:52,401 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,437 [INFO]  Epoch[2] Batch [0-1]	Speed: 985.88 samples/sec	cross-entropy=9.076128	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,441 [INFO]  Epoch[2] Train-cross-entropy=9.076128
2020-06-08 08:01:52,445 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,448 [INFO]  Epoch[2] Time cost=0.046
2020-06-08 08:01:52,454 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:01:52,472 [INFO]  Epoch[2] Validation-cross-entropy=2.132286
2020-06-08 08:01:52,476 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,512 [INFO]  Epoch[3] Batch [0-1]	Speed: 981.18 samples/sec	cross-entropy=8.875886	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,517 [INFO]  Epoch[3] Train-cross-entropy=8.875886
2020-06-08 08:01:52,520 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,521 [INFO]  Epoch[3] Time cost=0.042
2020-06-08 08:01:52,529 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:01:52,547 [INFO]  Epoch[3] Validation-cross-entropy=1.700814
2020-06-08 08:01:52,552 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,588 [INFO]  Epoch[4] Batch [0-1]	Speed: 988.84 samples/sec	cross-entropy=8.730401	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,590 [INFO]  Epoch[4] Train-cross-entropy=8.730401
2020-06-08 08:01:52,592 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,594 [INFO]  Epoch[4] Time cost=0.039
2020-06-08 08:01:52,601 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:01:52,620 [INFO]  Epoch[4] Validation-cross-entropy=1.233762
2020-06-08 08:01:52,621 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,660 [INFO]  Epoch[5] Batch [0-1]	Speed: 979.29 samples/sec	cross-entropy=8.674396	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,661 [INFO]  Epoch[5] Train-cross-entropy=8.674396
2020-06-08 08:01:52,663 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,664 [INFO]  Epoch[5] Time cost=0.041
2020-06-08 08:01:52,668 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:01:52,691 [INFO]  Epoch[5] Validation-cross-entropy=0.917639
2020-06-08 08:01:52,692 [INFO]  Epoch[5] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,729 [INFO]  Epoch[6] Batch [0-1]	Speed: 947.10 samples/sec	cross-entropy=8.668346	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,731 [INFO]  Epoch[6] Train-cross-entropy=8.668346
2020-06-08 08:01:52,733 [INFO]  Epoch[6] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,734 [INFO]  Epoch[6] Time cost=0.040
2020-06-08 08:01:52,739 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-08 08:01:52,759 [INFO]  Epoch[6] Validation-cross-entropy=0.775398
2020-06-08 08:01:52,761 [INFO]  Epoch[6] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,798 [INFO]  Epoch[7] Batch [0-1]	Speed: 1002.21 samples/sec	cross-entropy=8.659348	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,799 [INFO]  Epoch[7] Train-cross-entropy=8.659348
2020-06-08 08:01:52,800 [INFO]  Epoch[7] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,803 [INFO]  Epoch[7] Time cost=0.041
2020-06-08 08:01:52,815 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-08 08:01:52,835 [INFO]  Epoch[7] Validation-cross-entropy=0.754728
2020-06-08 08:01:52,837 [INFO]  Epoch[7] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,876 [INFO]  Epoch[8] Batch [0-1]	Speed: 976.30 samples/sec	cross-entropy=8.634827	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,877 [INFO]  Epoch[8] Train-cross-entropy=8.634827
2020-06-08 08:01:52,880 [INFO]  Epoch[8] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,882 [INFO]  Epoch[8] Time cost=0.042
2020-06-08 08:01:52,888 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-08 08:01:52,906 [INFO]  Epoch[8] Validation-cross-entropy=0.798226
2020-06-08 08:01:52,907 [INFO]  Epoch[8] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,945 [INFO]  Epoch[9] Batch [0-1]	Speed: 977.85 samples/sec	cross-entropy=8.606959	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,946 [INFO]  Epoch[9] Train-cross-entropy=8.606959
2020-06-08 08:01:52,949 [INFO]  Epoch[9] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:52,951 [INFO]  Epoch[9] Time cost=0.042
2020-06-08 08:01:52,956 [INFO]  Saved checkpoint to "datawig_imputation/model-0009.params"
2020-06-08 08:01:52,976 [INFO]  Epoch[9] Validation-cross-entropy=0.849923
2020-06-08 08:01:52,977 [INFO]  Epoch[9] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,015 [INFO]  Epoch[10] Batch [0-1]	Speed: 971.75 samples/sec	cross-entropy=8.583351	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,017 [INFO]  Epoch[10] Train-cross-entropy=8.583351
2020-06-08 08:01:53,018 [INFO]  Epoch[10] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,020 [INFO]  Epoch[10] Time cost=0.041
2020-06-08 08:01:53,026 [INFO]  Saved checkpoint to "datawig_imputation/model-0010.params"
2020-06-08 08:01:53,052 [INFO]  Epoch[10] Validation-cross-entropy=0.850146
2020-06-08 08:01:53,054 [INFO]  Epoch[10] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,092 [INFO]  Epoch[11] Batch [0-1]	Speed: 953.39 samples/sec	cross-entropy=8.565770	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,094 [INFO]  Epoch[11] Train-cross-entropy=8.565770
2020-06-08 08:01:53,095 [INFO]  Epoch[11] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,097 [INFO]  Epoch[11] Time cost=0.041
2020-06-08 08:01:53,102 [INFO]  Saved checkpoint to "datawig_imputation/model-0011.params"
2020-06-08 08:01:53,123 [INFO]  Epoch[11] Validation-cross-entropy=0.765838
2020-06-08 08:01:53,124 [INFO]  Epoch[11] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,164 [INFO]  Epoch[12] Batch [0-1]	Speed: 976.64 samples/sec	cross-entropy=8.545428	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,165 [INFO]  Epoch[12] Train-cross-entropy=8.545428
2020-06-08 08:01:53,167 [INFO]  Epoch[12] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,168 [INFO]  Epoch[12] Time cost=0.042
2020-06-08 08:01:53,174 [INFO]  Saved checkpoint to "datawig_imputation/model-0012.params"
2020-06-08 08:01:53,196 [INFO]  Epoch[12] Validation-cross-entropy=0.615446
2020-06-08 08:01:53,198 [INFO]  Epoch[12] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,235 [INFO]  Epoch[13] Batch [0-1]	Speed: 983.05 samples/sec	cross-entropy=8.522262	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,236 [INFO]  Epoch[13] Train-cross-entropy=8.522262
2020-06-08 08:01:53,239 [INFO]  Epoch[13] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,241 [INFO]  Epoch[13] Time cost=0.042
2020-06-08 08:01:53,247 [INFO]  Saved checkpoint to "datawig_imputation/model-0013.params"
2020-06-08 08:01:53,268 [INFO]  Epoch[13] Validation-cross-entropy=0.458135
2020-06-08 08:01:53,270 [INFO]  Epoch[13] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,307 [INFO]  Epoch[14] Batch [0-1]	Speed: 988.99 samples/sec	cross-entropy=8.505203	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,308 [INFO]  Epoch[14] Train-cross-entropy=8.505203
2020-06-08 08:01:53,310 [INFO]  Epoch[14] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,311 [INFO]  Epoch[14] Time cost=0.040
2020-06-08 08:01:53,317 [INFO]  Saved checkpoint to "datawig_imputation/model-0014.params"
2020-06-08 08:01:53,338 [INFO]  Epoch[14] Validation-cross-entropy=0.344918
2020-06-08 08:01:53,340 [INFO]  Epoch[14] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,377 [INFO]  Epoch[15] Batch [0-1]	Speed: 985.00 samples/sec	cross-entropy=8.501828	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,379 [INFO]  Epoch[15] Train-cross-entropy=8.501828
2020-06-08 08:01:53,380 [INFO]  Epoch[15] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,382 [INFO]  Epoch[15] Time cost=0.040
2020-06-08 08:01:53,387 [INFO]  Saved checkpoint to "datawig_imputation/model-0015.params"
2020-06-08 08:01:53,407 [INFO]  Epoch[15] Validation-cross-entropy=0.294349
2020-06-08 08:01:53,408 [INFO]  Epoch[15] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,445 [INFO]  Epoch[16] Batch [0-1]	Speed: 979.55 samples/sec	cross-entropy=8.501981	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,447 [INFO]  Epoch[16] Train-cross-entropy=8.501981
2020-06-08 08:01:53,448 [INFO]  Epoch[16] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,451 [INFO]  Epoch[16] Time cost=0.041
2020-06-08 08:01:53,455 [INFO]  Saved checkpoint to "datawig_imputation/model-0016.params"
2020-06-08 08:01:53,476 [INFO]  Epoch[16] Validation-cross-entropy=0.294869
2020-06-08 08:01:53,478 [INFO]  Epoch[16] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,515 [INFO]  Epoch[17] Batch [0-1]	Speed: 980.25 samples/sec	cross-entropy=8.501194	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,517 [INFO]  Epoch[17] Train-cross-entropy=8.501194
2020-06-08 08:01:53,519 [INFO]  Epoch[17] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,521 [INFO]  Epoch[17] Time cost=0.042
2020-06-08 08:01:53,528 [INFO]  Saved checkpoint to "datawig_imputation/model-0017.params"
2020-06-08 08:01:53,547 [INFO]  Epoch[17] Validation-cross-entropy=0.326749
2020-06-08 08:01:53,549 [INFO]  Epoch[17] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,586 [INFO]  Epoch[18] Batch [0-1]	Speed: 979.61 samples/sec	cross-entropy=8.501599	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,590 [INFO]  Epoch[18] Train-cross-entropy=8.501599
2020-06-08 08:01:53,592 [INFO]  Epoch[18] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,593 [INFO]  Epoch[18] Time cost=0.042
2020-06-08 08:01:53,599 [INFO]  Saved checkpoint to "datawig_imputation/model-0018.params"
2020-06-08 08:01:53,618 [INFO]  Epoch[18] Validation-cross-entropy=0.368475
2020-06-08 08:01:53,619 [INFO]  Epoch[18] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,657 [INFO]  Epoch[19] Batch [0-1]	Speed: 977.32 samples/sec	cross-entropy=8.504273	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,662 [INFO]  Epoch[19] Train-cross-entropy=8.504273
2020-06-08 08:01:53,665 [INFO]  Epoch[19] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,666 [INFO]  Epoch[19] Time cost=0.044
2020-06-08 08:01:53,672 [INFO]  Saved checkpoint to "datawig_imputation/model-0019.params"
2020-06-08 08:01:53,692 [INFO]  Epoch[19] Validation-cross-entropy=0.396490
2020-06-08 08:01:53,693 [INFO]  Epoch[19] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,730 [INFO]  Epoch[20] Batch [0-1]	Speed: 974.30 samples/sec	cross-entropy=8.503472	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,732 [INFO]  Epoch[20] Train-cross-entropy=8.503472
2020-06-08 08:01:53,735 [INFO]  Epoch[20] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:53,738 [INFO]  Epoch[20] Time cost=0.044
2020-06-08 08:01:53,745 [INFO]  Saved checkpoint to "datawig_imputation/model-0020.params"
2020-06-08 08:01:53,762 [INFO]  No improvement detected for 5 epochs compared to 0.2943488657474518 last error obtained: 0.3986668288707733, stopping here
2020-06-08 08:01:53,764 [INFO]
========== done (1.513782024383545 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

46 rows have been imputed

2020-06-08 08:01:54,074 [INFO]
========== start: fit model
2020-06-08 08:01:54,080 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:01:54,120 [INFO]  Epoch[0] Batch [0-1]	Speed: 983.54 samples/sec	cross-entropy=14.550487	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,122 [INFO]  Epoch[0] Train-cross-entropy=14.550487
2020-06-08 08:01:54,125 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,127 [INFO]  Epoch[0] Time cost=0.042
2020-06-08 08:01:54,133 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:01:54,150 [INFO]  Epoch[0] Validation-cross-entropy=5.533320
2020-06-08 08:01:54,153 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,190 [INFO]  Epoch[1] Batch [0-1]	Speed: 978.02 samples/sec	cross-entropy=13.781682	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,191 [INFO]  Epoch[1] Train-cross-entropy=13.781682
2020-06-08 08:01:54,194 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,197 [INFO]  Epoch[1] Time cost=0.042
2020-06-08 08:01:54,203 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:01:54,222 [INFO]  Epoch[1] Validation-cross-entropy=5.890641
2020-06-08 08:01:54,223 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,261 [INFO]  Epoch[2] Batch [0-1]	Speed: 985.13 samples/sec	cross-entropy=13.463156	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,266 [INFO]  Epoch[2] Train-cross-entropy=13.463156
2020-06-08 08:01:54,269 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,271 [INFO]  Epoch[2] Time cost=0.045
2020-06-08 08:01:54,277 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:01:54,296 [INFO]  Epoch[2] Validation-cross-entropy=6.547391
2020-06-08 08:01:54,299 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,336 [INFO]  Epoch[3] Batch [0-1]	Speed: 967.11 samples/sec	cross-entropy=13.274268	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,337 [INFO]  Epoch[3] Train-cross-entropy=13.274268
2020-06-08 08:01:54,342 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,344 [INFO]  Epoch[3] Time cost=0.043
2020-06-08 08:01:54,350 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:01:54,369 [INFO]  Epoch[3] Validation-cross-entropy=7.023177
2020-06-08 08:01:54,371 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,409 [INFO]  Epoch[4] Batch [0-1]	Speed: 986.79 samples/sec	cross-entropy=13.167472	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,411 [INFO]  Epoch[4] Train-cross-entropy=13.167472
2020-06-08 08:01:54,414 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,417 [INFO]  Epoch[4] Time cost=0.042
2020-06-08 08:01:54,424 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:01:54,442 [INFO]  Epoch[4] Validation-cross-entropy=7.158712
2020-06-08 08:01:54,443 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,486 [INFO]  Epoch[5] Batch [0-1]	Speed: 963.47 samples/sec	cross-entropy=13.095717	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,488 [INFO]  Epoch[5] Train-cross-entropy=13.095717
2020-06-08 08:01:54,490 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,492 [INFO]  Epoch[5] Time cost=0.047
2020-06-08 08:01:54,496 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:01:54,516 [INFO]  No improvement detected for 5 epochs compared to 5.53331995010376 last error obtained: 6.976983070373535, stopping here
2020-06-08 08:01:54,518 [INFO]
========== done (0.44390392303466797 s) fit model

35 rows have been imputed

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
2020-06-08 08:01:54,882 [INFO]
========== start: fit model
2020-06-08 08:01:54,887 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:01:54,941 [INFO]  Epoch[0] Batch [0-2]	Speed: 991.45 samples/sec	cross-entropy=13.777053	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,943 [INFO]  Epoch[0] Train-cross-entropy=13.777053
2020-06-08 08:01:54,945 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:54,947 [INFO]  Epoch[0] Time cost=0.056
2020-06-08 08:01:54,952 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:01:54,970 [INFO]  Epoch[0] Validation-cross-entropy=22.532059
2020-06-08 08:01:54,973 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,026 [INFO]  Epoch[1] Batch [0-2]	Speed: 981.93 samples/sec	cross-entropy=12.823145	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,031 [INFO]  Epoch[1] Train-cross-entropy=12.823145
2020-06-08 08:01:55,034 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,038 [INFO]  Epoch[1] Time cost=0.063
2020-06-08 08:01:55,044 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:01:55,066 [INFO]  Epoch[1] Validation-cross-entropy=23.081631
2020-06-08 08:01:55,068 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,123 [INFO]  Epoch[2] Batch [0-2]	Speed: 961.69 samples/sec	cross-entropy=12.440292	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,125 [INFO]  Epoch[2] Train-cross-entropy=12.440292
2020-06-08 08:01:55,128 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,132 [INFO]  Epoch[2] Time cost=0.061
2020-06-08 08:01:55,139 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:01:55,157 [INFO]  Epoch[2] Validation-cross-entropy=24.043932
2020-06-08 08:01:55,159 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,213 [INFO]  Epoch[3] Batch [0-2]	Speed: 995.02 samples/sec	cross-entropy=12.136072	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,214 [INFO]  Epoch[3] Train-cross-entropy=12.136072
2020-06-08 08:01:55,216 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,219 [INFO]  Epoch[3] Time cost=0.056
2020-06-08 08:01:55,226 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:01:55,246 [INFO]  Epoch[3] Validation-cross-entropy=25.026915
2020-06-08 08:01:55,250 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,302 [INFO]  Epoch[4] Batch [0-2]	Speed: 993.30 samples/sec	cross-entropy=11.947322	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,307 [INFO]  Epoch[4] Train-cross-entropy=11.947322
2020-06-08 08:01:55,310 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,312 [INFO]  Epoch[4] Time cost=0.060
2020-06-08 08:01:55,319 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:01:55,338 [INFO]  Epoch[4] Validation-cross-entropy=25.796112
2020-06-08 08:01:55,342 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,395 [INFO]  Epoch[5] Batch [0-2]	Speed: 984.56 samples/sec	cross-entropy=11.828698	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,400 [INFO]  Epoch[5] Train-cross-entropy=11.828698
2020-06-08 08:01:55,403 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,404 [INFO]  Epoch[5] Time cost=0.058
2020-06-08 08:01:55,412 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:01:55,430 [INFO]  No improvement detected for 5 epochs compared to 22.532058715820312 last error obtained: 26.187053680419922, stopping here
2020-06-08 08:01:55,431 [INFO]
========== done (0.5502307415008545 s) fit model

33 rows have been imputed

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
2020-06-08 08:01:55,804 [INFO]
========== start: fit model
2020-06-08 08:01:55,805 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:01:55,849 [INFO]  Epoch[0] Batch [0-1]	Speed: 968.09 samples/sec	cross-entropy=11.899713	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,851 [INFO]  Epoch[0] Train-cross-entropy=11.899713
2020-06-08 08:01:55,853 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,855 [INFO]  Epoch[0] Time cost=0.042
2020-06-08 08:01:55,861 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:01:55,880 [INFO]  Epoch[0] Validation-cross-entropy=11.663993
2020-06-08 08:01:55,882 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,922 [INFO]  Epoch[1] Batch [0-1]	Speed: 813.28 samples/sec	cross-entropy=10.370178	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,927 [INFO]  Epoch[1] Train-cross-entropy=10.370178
2020-06-08 08:01:55,929 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,930 [INFO]  Epoch[1] Time cost=0.046
2020-06-08 08:01:55,936 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:01:55,955 [INFO]  Epoch[1] Validation-cross-entropy=16.656906
2020-06-08 08:01:55,957 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,996 [INFO]  Epoch[2] Batch [0-1]	Speed: 899.87 samples/sec	cross-entropy=9.859435	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:55,999 [INFO]  Epoch[2] Train-cross-entropy=9.859435
2020-06-08 08:01:56,003 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,005 [INFO]  Epoch[2] Time cost=0.046
2020-06-08 08:01:56,011 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:01:56,028 [INFO]  Epoch[2] Validation-cross-entropy=19.735447
2020-06-08 08:01:56,032 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,070 [INFO]  Epoch[3] Batch [0-1]	Speed: 929.05 samples/sec	cross-entropy=9.600455	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,072 [INFO]  Epoch[3] Train-cross-entropy=9.600455
2020-06-08 08:01:56,073 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,075 [INFO]  Epoch[3] Time cost=0.041
2020-06-08 08:01:56,080 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:01:56,102 [INFO]  Epoch[3] Validation-cross-entropy=19.559134
2020-06-08 08:01:56,104 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,141 [INFO]  Epoch[4] Batch [0-1]	Speed: 978.13 samples/sec	cross-entropy=9.273104	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,143 [INFO]  Epoch[4] Train-cross-entropy=9.273104
2020-06-08 08:01:56,145 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,146 [INFO]  Epoch[4] Time cost=0.041
2020-06-08 08:01:56,151 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:01:56,173 [INFO]  Epoch[4] Validation-cross-entropy=17.303614
2020-06-08 08:01:56,175 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,212 [INFO]  Epoch[5] Batch [0-1]	Speed: 974.92 samples/sec	cross-entropy=8.990307	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,214 [INFO]  Epoch[5] Train-cross-entropy=8.990307
2020-06-08 08:01:56,215 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,217 [INFO]  Epoch[5] Time cost=0.040
2020-06-08 08:01:56,222 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:01:56,243 [INFO]  No improvement detected for 5 epochs compared to 11.663992881774902 last error obtained: 14.391563415527344, stopping here
2020-06-08 08:01:56,245 [INFO]
========== done (0.4411449432373047 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

35 rows have been imputed

2020-06-08 08:01:56,626 [INFO]
========== start: fit model
2020-06-08 08:01:56,627 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:01:56,671 [INFO]  Epoch[0] Batch [0-1]	Speed: 992.54 samples/sec	cross-entropy=9.224019	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,673 [INFO]  Epoch[0] Train-cross-entropy=9.224019
2020-06-08 08:01:56,675 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,677 [INFO]  Epoch[0] Time cost=0.045
2020-06-08 08:01:56,683 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:01:56,701 [INFO]  Epoch[0] Validation-cross-entropy=642.854614
2020-06-08 08:01:56,705 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,742 [INFO]  Epoch[1] Batch [0-1]	Speed: 984.69 samples/sec	cross-entropy=7.931674	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,744 [INFO]  Epoch[1] Train-cross-entropy=7.931674
2020-06-08 08:01:56,747 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,749 [INFO]  Epoch[1] Time cost=0.043
2020-06-08 08:01:56,756 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:01:56,773 [INFO]  Epoch[1] Validation-cross-entropy=593.190430
2020-06-08 08:01:56,775 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,812 [INFO]  Epoch[2] Batch [0-1]	Speed: 982.52 samples/sec	cross-entropy=8.065804	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,814 [INFO]  Epoch[2] Train-cross-entropy=8.065804
2020-06-08 08:01:56,817 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,819 [INFO]  Epoch[2] Time cost=0.042
2020-06-08 08:01:56,826 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:01:56,843 [INFO]  Epoch[2] Validation-cross-entropy=568.033813
2020-06-08 08:01:56,845 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,883 [INFO]  Epoch[3] Batch [0-1]	Speed: 969.92 samples/sec	cross-entropy=8.143991	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,885 [INFO]  Epoch[3] Train-cross-entropy=8.143991
2020-06-08 08:01:56,888 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,891 [INFO]  Epoch[3] Time cost=0.042
2020-06-08 08:01:56,897 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:01:56,915 [INFO]  Epoch[3] Validation-cross-entropy=564.097168
2020-06-08 08:01:56,917 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,955 [INFO]  Epoch[4] Batch [0-1]	Speed: 948.96 samples/sec	cross-entropy=7.901749	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,957 [INFO]  Epoch[4] Train-cross-entropy=7.901749
2020-06-08 08:01:56,961 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:56,964 [INFO]  Epoch[4] Time cost=0.044
2020-06-08 08:01:56,971 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:01:56,989 [INFO]  Epoch[4] Validation-cross-entropy=572.259888
2020-06-08 08:01:56,991 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,029 [INFO]  Epoch[5] Batch [0-1]	Speed: 934.73 samples/sec	cross-entropy=7.674531	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,031 [INFO]  Epoch[5] Train-cross-entropy=7.674531
2020-06-08 08:01:57,034 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,038 [INFO]  Epoch[5] Time cost=0.044
2020-06-08 08:01:57,044 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:01:57,061 [INFO]  Epoch[5] Validation-cross-entropy=585.740295
2020-06-08 08:01:57,064 [INFO]  Epoch[5] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,110 [INFO]  Epoch[6] Batch [0-1]	Speed: 930.00 samples/sec	cross-entropy=7.609481	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,114 [INFO]  Epoch[6] Train-cross-entropy=7.609481
2020-06-08 08:01:57,116 [INFO]  Epoch[6] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,119 [INFO]  Epoch[6] Time cost=0.051
2020-06-08 08:01:57,125 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-08 08:01:57,143 [INFO]  Epoch[6] Validation-cross-entropy=599.463074
2020-06-08 08:01:57,145 [INFO]  Epoch[6] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,183 [INFO]  Epoch[7] Batch [0-1]	Speed: 979.45 samples/sec	cross-entropy=7.629314	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,185 [INFO]  Epoch[7] Train-cross-entropy=7.629314
2020-06-08 08:01:57,188 [INFO]  Epoch[7] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,191 [INFO]  Epoch[7] Time cost=0.043
2020-06-08 08:01:57,199 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-08 08:01:57,216 [INFO]  No improvement detected for 5 epochs compared to 568.0338134765625 last error obtained: 609.3060302734375, stopping here
2020-06-08 08:01:57,218 [INFO]
========== done (0.5929362773895264 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

42 rows have been imputed

2020-06-08 08:01:57,541 [INFO]
========== start: fit model
2020-06-08 08:01:57,547 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:01:57,604 [INFO]  Epoch[0] Batch [0-2]	Speed: 988.63 samples/sec	cross-entropy=16.756479	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,608 [INFO]  Epoch[0] Train-cross-entropy=16.756479
2020-06-08 08:01:57,611 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,613 [INFO]  Epoch[0] Time cost=0.060
2020-06-08 08:01:57,620 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:01:57,638 [INFO]  Epoch[0] Validation-cross-entropy=4.574572
2020-06-08 08:01:57,641 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,694 [INFO]  Epoch[1] Batch [0-2]	Speed: 987.72 samples/sec	cross-entropy=14.441141	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,698 [INFO]  Epoch[1] Train-cross-entropy=14.441141
2020-06-08 08:01:57,699 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,702 [INFO]  Epoch[1] Time cost=0.060
2020-06-08 08:01:57,708 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:01:57,727 [INFO]  Epoch[1] Validation-cross-entropy=5.074704
2020-06-08 08:01:57,731 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,784 [INFO]  Epoch[2] Batch [0-2]	Speed: 985.93 samples/sec	cross-entropy=13.398134	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,789 [INFO]  Epoch[2] Train-cross-entropy=13.398134
2020-06-08 08:01:57,792 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,795 [INFO]  Epoch[2] Time cost=0.061
2020-06-08 08:01:57,801 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:01:57,819 [INFO]  Epoch[2] Validation-cross-entropy=5.807591
2020-06-08 08:01:57,823 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,876 [INFO]  Epoch[3] Batch [0-2]	Speed: 986.64 samples/sec	cross-entropy=13.219948	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,881 [INFO]  Epoch[3] Train-cross-entropy=13.219948
2020-06-08 08:01:57,882 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,887 [INFO]  Epoch[3] Time cost=0.060
2020-06-08 08:01:57,892 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:01:57,910 [INFO]  Epoch[3] Validation-cross-entropy=6.027503
2020-06-08 08:01:57,915 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,969 [INFO]  Epoch[4] Batch [0-2]	Speed: 934.42 samples/sec	cross-entropy=13.208435	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,974 [INFO]  Epoch[4] Train-cross-entropy=13.208435
2020-06-08 08:01:57,979 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:57,984 [INFO]  Epoch[4] Time cost=0.066
2020-06-08 08:01:57,992 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:01:58,011 [INFO]  Epoch[4] Validation-cross-entropy=5.563994
2020-06-08 08:01:58,016 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,071 [INFO]  Epoch[5] Batch [0-2]	Speed: 969.32 samples/sec	cross-entropy=13.022211	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,076 [INFO]  Epoch[5] Train-cross-entropy=13.022211
2020-06-08 08:01:58,080 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,084 [INFO]  Epoch[5] Time cost=0.063
2020-06-08 08:01:58,091 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:01:58,114 [INFO]  No improvement detected for 5 epochs compared to 4.5745720863342285 last error obtained: 4.868525505065918, stopping here
2020-06-08 08:01:58,116 [INFO]
========== done (0.575531005859375 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

29 rows have been imputed

2020-06-08 08:01:58,478 [INFO]
========== start: fit model
2020-06-08 08:01:58,480 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:01:58,521 [INFO]  Epoch[0] Batch [0-1]	Speed: 991.02 samples/sec	cross-entropy=18.343332	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,522 [INFO]  Epoch[0] Train-cross-entropy=18.343332
2020-06-08 08:01:58,524 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,525 [INFO]  Epoch[0] Time cost=0.042
2020-06-08 08:01:58,532 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:01:58,553 [INFO]  Epoch[0] Validation-cross-entropy=6.866802
2020-06-08 08:01:58,555 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,596 [INFO]  Epoch[1] Batch [0-1]	Speed: 824.59 samples/sec	cross-entropy=15.469167	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,598 [INFO]  Epoch[1] Train-cross-entropy=15.469167
2020-06-08 08:01:58,600 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,606 [INFO]  Epoch[1] Time cost=0.049
2020-06-08 08:01:58,614 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:01:58,634 [INFO]  Epoch[1] Validation-cross-entropy=3.845374
2020-06-08 08:01:58,636 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,676 [INFO]  Epoch[2] Batch [0-1]	Speed: 990.86 samples/sec	cross-entropy=13.224257	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,678 [INFO]  Epoch[2] Train-cross-entropy=13.224257
2020-06-08 08:01:58,683 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,685 [INFO]  Epoch[2] Time cost=0.045
2020-06-08 08:01:58,691 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:01:58,708 [INFO]  Epoch[2] Validation-cross-entropy=1.722044
2020-06-08 08:01:58,710 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,748 [INFO]  Epoch[3] Batch [0-1]	Speed: 988.71 samples/sec	cross-entropy=11.800830	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,751 [INFO]  Epoch[3] Train-cross-entropy=11.800830
2020-06-08 08:01:58,753 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,757 [INFO]  Epoch[3] Time cost=0.044
2020-06-08 08:01:58,762 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:01:58,780 [INFO]  Epoch[3] Validation-cross-entropy=0.502860
2020-06-08 08:01:58,781 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,818 [INFO]  Epoch[4] Batch [0-1]	Speed: 986.03 samples/sec	cross-entropy=10.954745	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,820 [INFO]  Epoch[4] Train-cross-entropy=10.954745
2020-06-08 08:01:58,824 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,826 [INFO]  Epoch[4] Time cost=0.041
2020-06-08 08:01:58,833 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:01:58,851 [INFO]  Epoch[4] Validation-cross-entropy=0.028609
2020-06-08 08:01:58,853 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,890 [INFO]  Epoch[5] Batch [0-1]	Speed: 962.15 samples/sec	cross-entropy=10.547705	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,895 [INFO]  Epoch[5] Train-cross-entropy=10.547705
2020-06-08 08:01:58,897 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,900 [INFO]  Epoch[5] Time cost=0.046
2020-06-08 08:01:58,905 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:01:58,923 [INFO]  Epoch[5] Validation-cross-entropy=0.086812
2020-06-08 08:01:58,925 [INFO]  Epoch[5] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,963 [INFO]  Epoch[6] Batch [0-1]	Speed: 959.49 samples/sec	cross-entropy=10.395882	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,966 [INFO]  Epoch[6] Train-cross-entropy=10.395882
2020-06-08 08:01:58,969 [INFO]  Epoch[6] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:58,971 [INFO]  Epoch[6] Time cost=0.044
2020-06-08 08:01:58,977 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-08 08:01:58,996 [INFO]  Epoch[6] Validation-cross-entropy=0.452710
2020-06-08 08:01:58,998 [INFO]  Epoch[6] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,036 [INFO]  Epoch[7] Batch [0-1]	Speed: 959.93 samples/sec	cross-entropy=10.290563	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,037 [INFO]  Epoch[7] Train-cross-entropy=10.290563
2020-06-08 08:01:59,041 [INFO]  Epoch[7] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,044 [INFO]  Epoch[7] Time cost=0.044
2020-06-08 08:01:59,050 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-08 08:01:59,068 [INFO]  Epoch[7] Validation-cross-entropy=0.924136
2020-06-08 08:01:59,070 [INFO]  Epoch[7] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,109 [INFO]  Epoch[8] Batch [0-1]	Speed: 914.12 samples/sec	cross-entropy=10.110237	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,116 [INFO]  Epoch[8] Train-cross-entropy=10.110237
2020-06-08 08:01:59,120 [INFO]  Epoch[8] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,123 [INFO]  Epoch[8] Time cost=0.050
2020-06-08 08:01:59,129 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-08 08:01:59,147 [INFO]  Epoch[8] Validation-cross-entropy=1.352793
2020-06-08 08:01:59,151 [INFO]  Epoch[8] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,187 [INFO]  Epoch[9] Batch [0-1]	Speed: 989.21 samples/sec	cross-entropy=9.822678	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,189 [INFO]  Epoch[9] Train-cross-entropy=9.822678
2020-06-08 08:01:59,191 [INFO]  Epoch[9] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,193 [INFO]  Epoch[9] Time cost=0.040
2020-06-08 08:01:59,199 [INFO]  Saved checkpoint to "datawig_imputation/model-0009.params"
2020-06-08 08:01:59,218 [INFO]  No improvement detected for 5 epochs compared to 0.028609098866581917 last error obtained: 1.661797046661377, stopping here
2020-06-08 08:01:59,223 [INFO]
========== done (0.7452259063720703 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

42 rows have been imputed

2020-06-08 08:01:59,508 [INFO]
========== start: fit model
2020-06-08 08:01:59,511 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:01:59,539 [INFO]  Epoch[0] Train-cross-entropy=15.874971
2020-06-08 08:01:59,541 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,544 [INFO]  Epoch[0] Time cost=0.028
2020-06-08 08:01:59,550 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:01:59,569 [INFO]  Epoch[0] Validation-cross-entropy=6.355150
2020-06-08 08:01:59,571 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,595 [INFO]  Epoch[1] Batch [-1-0]	Speed: 284.74 samples/sec	cross-entropy=15.489558	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,599 [INFO]  Epoch[1] Train-cross-entropy=15.489558
2020-06-08 08:01:59,601 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,603 [INFO]  Epoch[1] Time cost=0.030
2020-06-08 08:01:59,609 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:01:59,631 [INFO]  Epoch[1] Validation-cross-entropy=7.508646
2020-06-08 08:01:59,634 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,655 [INFO]  Epoch[2] Batch [-1-0]	Speed: 282.82 samples/sec	cross-entropy=15.252461	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,657 [INFO]  Epoch[2] Train-cross-entropy=15.252461
2020-06-08 08:01:59,659 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,661 [INFO]  Epoch[2] Time cost=0.025
2020-06-08 08:01:59,667 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:01:59,691 [INFO]  Epoch[2] Validation-cross-entropy=8.100435
2020-06-08 08:01:59,693 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,715 [INFO]  Epoch[3] Batch [-1-0]	Speed: 275.89 samples/sec	cross-entropy=15.002492	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,718 [INFO]  Epoch[3] Train-cross-entropy=15.002492
2020-06-08 08:01:59,721 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,726 [INFO]  Epoch[3] Time cost=0.029
2020-06-08 08:01:59,732 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:01:59,750 [INFO]  Epoch[3] Validation-cross-entropy=8.199635
2020-06-08 08:01:59,752 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,774 [INFO]  Epoch[4] Batch [-1-0]	Speed: 285.26 samples/sec	cross-entropy=14.772054	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,775 [INFO]  Epoch[4] Train-cross-entropy=14.772054
2020-06-08 08:01:59,777 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,781 [INFO]  Epoch[4] Time cost=0.026
2020-06-08 08:01:59,788 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:01:59,805 [INFO]  Epoch[4] Validation-cross-entropy=7.939920
2020-06-08 08:01:59,807 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,828 [INFO]  Epoch[5] Batch [-1-0]	Speed: 303.82 samples/sec	cross-entropy=14.563131	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,832 [INFO]  Epoch[5] Train-cross-entropy=14.563131
2020-06-08 08:01:59,837 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:01:59,839 [INFO]  Epoch[5] Time cost=0.029
2020-06-08 08:01:59,846 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:01:59,864 [INFO]  No improvement detected for 5 epochs compared to 6.355149745941162 last error obtained: 7.475727081298828, stopping here
2020-06-08 08:01:59,866 [INFO]
========== done (0.35871052742004395 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

39 rows have been imputed

2020-06-08 08:02:00,203 [INFO]
========== start: fit model
2020-06-08 08:02:00,206 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:02:00,263 [INFO]  Epoch[0] Batch [0-2]	Speed: 966.21 samples/sec	cross-entropy=18.798131	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,268 [INFO]  Epoch[0] Train-cross-entropy=18.798131
2020-06-08 08:02:00,272 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,275 [INFO]  Epoch[0] Time cost=0.064
2020-06-08 08:02:00,281 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:02:00,299 [INFO]  Epoch[0] Validation-cross-entropy=24.422241
2020-06-08 08:02:00,300 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,356 [INFO]  Epoch[1] Batch [0-2]	Speed: 959.93 samples/sec	cross-entropy=17.403262	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,357 [INFO]  Epoch[1] Train-cross-entropy=17.403262
2020-06-08 08:02:00,360 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,362 [INFO]  Epoch[1] Time cost=0.060
2020-06-08 08:02:00,367 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:02:00,387 [INFO]  Epoch[1] Validation-cross-entropy=27.415352
2020-06-08 08:02:00,390 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,443 [INFO]  Epoch[2] Batch [0-2]	Speed: 982.32 samples/sec	cross-entropy=16.992846	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,447 [INFO]  Epoch[2] Train-cross-entropy=16.992846
2020-06-08 08:02:00,449 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,451 [INFO]  Epoch[2] Time cost=0.060
2020-06-08 08:02:00,456 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:02:00,477 [INFO]  Epoch[2] Validation-cross-entropy=28.515400
2020-06-08 08:02:00,479 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,533 [INFO]  Epoch[3] Batch [0-2]	Speed: 985.96 samples/sec	cross-entropy=16.983164	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,537 [INFO]  Epoch[3] Train-cross-entropy=16.983164
2020-06-08 08:02:00,540 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,544 [INFO]  Epoch[3] Time cost=0.063
2020-06-08 08:02:00,549 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:02:00,568 [INFO]  Epoch[3] Validation-cross-entropy=28.243538
2020-06-08 08:02:00,572 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,625 [INFO]  Epoch[4] Batch [0-2]	Speed: 983.49 samples/sec	cross-entropy=17.015796	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,630 [INFO]  Epoch[4] Train-cross-entropy=17.015796
2020-06-08 08:02:00,633 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,635 [INFO]  Epoch[4] Time cost=0.059
2020-06-08 08:02:00,643 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:02:00,662 [INFO]  Epoch[4] Validation-cross-entropy=27.211645
2020-06-08 08:02:00,666 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,719 [INFO]  Epoch[5] Batch [0-2]	Speed: 990.37 samples/sec	cross-entropy=16.964890	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,724 [INFO]  Epoch[5] Train-cross-entropy=16.964890
2020-06-08 08:02:00,725 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:00,731 [INFO]  Epoch[5] Time cost=0.061
2020-06-08 08:02:00,737 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:02:00,755 [INFO]  No improvement detected for 5 epochs compared to 24.4222412109375 last error obtained: 25.96071434020996, stopping here
2020-06-08 08:02:00,760 [INFO]
========== done (0.5570907592773438 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

22 rows have been imputed

2020-06-08 08:02:01,148 [INFO]
========== start: fit model
2020-06-08 08:02:01,153 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:02:01,192 [INFO]  Epoch[0] Batch [0-1]	Speed: 981.58 samples/sec	cross-entropy=16.248174	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,195 [INFO]  Epoch[0] Train-cross-entropy=16.248174
2020-06-08 08:02:01,197 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,198 [INFO]  Epoch[0] Time cost=0.042
2020-06-08 08:02:01,204 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:02:01,222 [INFO]  Epoch[0] Validation-cross-entropy=31.020180
2020-06-08 08:02:01,226 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,263 [INFO]  Epoch[1] Batch [0-1]	Speed: 986.46 samples/sec	cross-entropy=13.989931	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,266 [INFO]  Epoch[1] Train-cross-entropy=13.989931
2020-06-08 08:02:01,268 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,270 [INFO]  Epoch[1] Time cost=0.043
2020-06-08 08:02:01,277 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:02:01,295 [INFO]  Epoch[1] Validation-cross-entropy=27.096642
2020-06-08 08:02:01,298 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,334 [INFO]  Epoch[2] Batch [0-1]	Speed: 983.18 samples/sec	cross-entropy=12.287005	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,336 [INFO]  Epoch[2] Train-cross-entropy=12.287005
2020-06-08 08:02:01,337 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,339 [INFO]  Epoch[2] Time cost=0.040
2020-06-08 08:02:01,344 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:02:01,366 [INFO]  Epoch[2] Validation-cross-entropy=23.933914
2020-06-08 08:02:01,368 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,405 [INFO]  Epoch[3] Batch [0-1]	Speed: 985.03 samples/sec	cross-entropy=11.319689	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,407 [INFO]  Epoch[3] Train-cross-entropy=11.319689
2020-06-08 08:02:01,409 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,410 [INFO]  Epoch[3] Time cost=0.040
2020-06-08 08:02:01,420 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:02:01,438 [INFO]  Epoch[3] Validation-cross-entropy=24.177708
2020-06-08 08:02:01,440 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,480 [INFO]  Epoch[4] Batch [0-1]	Speed: 866.93 samples/sec	cross-entropy=10.872655	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,482 [INFO]  Epoch[4] Train-cross-entropy=10.872655
2020-06-08 08:02:01,487 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,491 [INFO]  Epoch[4] Time cost=0.048
2020-06-08 08:02:01,497 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:02:01,514 [INFO]  Epoch[4] Validation-cross-entropy=26.766150
2020-06-08 08:02:01,518 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,554 [INFO]  Epoch[5] Batch [0-1]	Speed: 983.05 samples/sec	cross-entropy=10.763708	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,559 [INFO]  Epoch[5] Train-cross-entropy=10.763708
2020-06-08 08:02:01,562 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,566 [INFO]  Epoch[5] Time cost=0.046
2020-06-08 08:02:01,572 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:02:01,590 [INFO]  Epoch[5] Validation-cross-entropy=30.146265
2020-06-08 08:02:01,594 [INFO]  Epoch[5] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,631 [INFO]  Epoch[6] Batch [0-1]	Speed: 986.18 samples/sec	cross-entropy=10.873284	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,635 [INFO]  Epoch[6] Train-cross-entropy=10.873284
2020-06-08 08:02:01,639 [INFO]  Epoch[6] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,642 [INFO]  Epoch[6] Time cost=0.045
2020-06-08 08:02:01,648 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-08 08:02:01,667 [INFO]  Epoch[6] Validation-cross-entropy=32.531036
2020-06-08 08:02:01,672 [INFO]  Epoch[6] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,709 [INFO]  Epoch[7] Batch [0-1]	Speed: 997.59 samples/sec	cross-entropy=11.050183	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,712 [INFO]  Epoch[7] Train-cross-entropy=11.050183
2020-06-08 08:02:01,717 [INFO]  Epoch[7] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:01,720 [INFO]  Epoch[7] Time cost=0.045
2020-06-08 08:02:01,726 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-08 08:02:01,747 [INFO]  No improvement detected for 5 epochs compared to 23.933914184570312 last error obtained: 32.87643051147461, stopping here
2020-06-08 08:02:01,749 [INFO]
========== done (0.60121750831604 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

45 rows have been imputed

2020-06-08 08:02:02,084 [INFO]
========== start: fit model
2020-06-08 08:02:02,091 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:02:02,130 [INFO]  Epoch[0] Batch [0-1]	Speed: 979.65 samples/sec	cross-entropy=11.695600	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,134 [INFO]  Epoch[0] Train-cross-entropy=11.695600
2020-06-08 08:02:02,136 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,138 [INFO]  Epoch[0] Time cost=0.042
2020-06-08 08:02:02,144 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:02:02,168 [INFO]  Epoch[0] Validation-cross-entropy=8.650583
2020-06-08 08:02:02,170 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,208 [INFO]  Epoch[1] Batch [0-1]	Speed: 971.92 samples/sec	cross-entropy=10.689271	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,210 [INFO]  Epoch[1] Train-cross-entropy=10.689271
2020-06-08 08:02:02,214 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,216 [INFO]  Epoch[1] Time cost=0.043
2020-06-08 08:02:02,222 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:02:02,241 [INFO]  Epoch[1] Validation-cross-entropy=10.507668
2020-06-08 08:02:02,243 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,280 [INFO]  Epoch[2] Batch [0-1]	Speed: 975.70 samples/sec	cross-entropy=10.354915	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,282 [INFO]  Epoch[2] Train-cross-entropy=10.354915
2020-06-08 08:02:02,285 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,287 [INFO]  Epoch[2] Time cost=0.043
2020-06-08 08:02:02,293 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:02:02,312 [INFO]  Epoch[2] Validation-cross-entropy=12.665655
2020-06-08 08:02:02,314 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,352 [INFO]  Epoch[3] Batch [0-1]	Speed: 975.35 samples/sec	cross-entropy=10.401731	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,356 [INFO]  Epoch[3] Train-cross-entropy=10.401731
2020-06-08 08:02:02,359 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,363 [INFO]  Epoch[3] Time cost=0.045
2020-06-08 08:02:02,368 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:02:02,386 [INFO]  Epoch[3] Validation-cross-entropy=13.418213
2020-06-08 08:02:02,388 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,428 [INFO]  Epoch[4] Batch [0-1]	Speed: 877.46 samples/sec	cross-entropy=10.391232	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,431 [INFO]  Epoch[4] Train-cross-entropy=10.391232
2020-06-08 08:02:02,434 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,436 [INFO]  Epoch[4] Time cost=0.045
2020-06-08 08:02:02,442 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:02:02,460 [INFO]  Epoch[4] Validation-cross-entropy=12.620148
2020-06-08 08:02:02,463 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,501 [INFO]  Epoch[5] Batch [0-1]	Speed: 975.86 samples/sec	cross-entropy=10.210230	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,505 [INFO]  Epoch[5] Train-cross-entropy=10.210230
2020-06-08 08:02:02,507 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,513 [INFO]  Epoch[5] Time cost=0.048
2020-06-08 08:02:02,519 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:02:02,537 [INFO]  No improvement detected for 5 epochs compared to 8.650583267211914 last error obtained: 11.42182731628418, stopping here
2020-06-08 08:02:02,539 [INFO]
========== done (0.4563891887664795 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

45 rows have been imputed

2020-06-08 08:02:02,866 [INFO]
========== start: fit model
2020-06-08 08:02:02,869 [WARNING]  Already bound, ignoring bind()
2020-06-08 08:02:02,926 [INFO]  Epoch[0] Batch [0-2]	Speed: 973.51 samples/sec	cross-entropy=12.856544	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,931 [INFO]  Epoch[0] Train-cross-entropy=12.856544
2020-06-08 08:02:02,934 [INFO]  Epoch[0] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:02,937 [INFO]  Epoch[0] Time cost=0.063
2020-06-08 08:02:02,945 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-08 08:02:02,963 [INFO]  Epoch[0] Validation-cross-entropy=13.725596
2020-06-08 08:02:02,969 [INFO]  Epoch[0] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,025 [INFO]  Epoch[1] Batch [0-2]	Speed: 960.24 samples/sec	cross-entropy=12.003463	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,029 [INFO]  Epoch[1] Train-cross-entropy=12.003463
2020-06-08 08:02:03,034 [INFO]  Epoch[1] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,038 [INFO]  Epoch[1] Time cost=0.067
2020-06-08 08:02:03,044 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-08 08:02:03,062 [INFO]  Epoch[1] Validation-cross-entropy=17.929972
2020-06-08 08:02:03,063 [INFO]  Epoch[1] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,118 [INFO]  Epoch[2] Batch [0-2]	Speed: 966.93 samples/sec	cross-entropy=11.938083	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,123 [INFO]  Epoch[2] Train-cross-entropy=11.938083
2020-06-08 08:02:03,126 [INFO]  Epoch[2] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,128 [INFO]  Epoch[2] Time cost=0.062
2020-06-08 08:02:03,137 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-08 08:02:03,157 [INFO]  Epoch[2] Validation-cross-entropy=20.525043
2020-06-08 08:02:03,162 [INFO]  Epoch[2] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,225 [INFO]  Epoch[3] Batch [0-2]	Speed: 977.96 samples/sec	cross-entropy=12.004370	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,227 [INFO]  Epoch[3] Train-cross-entropy=12.004370
2020-06-08 08:02:03,231 [INFO]  Epoch[3] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,233 [INFO]  Epoch[3] Time cost=0.059
2020-06-08 08:02:03,240 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-08 08:02:03,258 [INFO]  Epoch[3] Validation-cross-entropy=21.156551
2020-06-08 08:02:03,260 [INFO]  Epoch[3] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,313 [INFO]  Epoch[4] Batch [0-2]	Speed: 991.16 samples/sec	cross-entropy=12.051388	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,315 [INFO]  Epoch[4] Train-cross-entropy=12.051388
2020-06-08 08:02:03,319 [INFO]  Epoch[4] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,322 [INFO]  Epoch[4] Time cost=0.059
2020-06-08 08:02:03,328 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-08 08:02:03,346 [INFO]  Epoch[4] Validation-cross-entropy=20.388252
2020-06-08 08:02:03,348 [INFO]  Epoch[4] Validation-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,402 [INFO]  Epoch[5] Batch [0-2]	Speed: 984.46 samples/sec	cross-entropy=12.032450	Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,404 [INFO]  Epoch[5] Train-cross-entropy=12.032450
2020-06-08 08:02:03,407 [INFO]  Epoch[5] Train-Image_Optical_Depth_Land_And_Ocean-accuracy=0.000000
2020-06-08 08:02:03,410 [INFO]  Epoch[5] Time cost=0.058
2020-06-08 08:02:03,416 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-08 08:02:03,437 [INFO]  No improvement detected for 5 epochs compared to 13.72559642791748 last error obtained: 19.000476837158203, stopping here
2020-06-08 08:02:03,439 [INFO]
========== done (0.5733656883239746 s) fit model

40 rows have been imputed

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [0]:
# 3.Appending them back
imputed_year_dflist = [yr_2016_imputed, yr_2017_imputed, yr_2018_imputed,
                       yr_2019_imputed, yr_2020_imputed ]
chennai_sat_data_imputed = pd.DataFrame()
for imputed_df in imputed_year_dflist:
    chennai_sat_data_imputed = chennai_sat_data_imputed.append(imputed_df)

###Cross validation
cross checking imputed values and observed values by their mean values

In [0]:
#mean of imputed AOD
chennai_sat_data_imputed['updated_AOD_Land_and_Ocean_datawig'].mean(axis = 0, skipna = True)

0.4640422219544601

In [0]:
#mean of existing AOD
chennai_sat_data_imputed['Image_Optical_Depth_Land_And_Ocean'].replace(-9999, np.NaN, inplace = True)
chennai_sat_data_imputed['Image_Optical_Depth_Land_And_Ocean'].mean(axis = 0, skipna = True)

0.46954891119126435

In [0]:
chennai_sat_data_imputed.to_csv("chennai_final_sat_data_imputed7.csv")
print("Imputed values file named 'chennai_sat_data_imputed' is created")

Imputed values file named 'chennai_sat_data_imputed' is created