# **CODE-5:**

In [48]:
'''
CODE-5: TO IMPUTE RH, PM VALUES AND IMPLEMENT RH-PM CORRECTION FACTOR
==========================================================================================
TO DO/RELOOK:
-> Recheck the final combined datamatrix making sure timestamp and place
        for ground and satellite are similar

INPUT           : chennai_final_combined_data
OUTPUT          : chennai_overall_datamatrix
==========================================================================================
'''

'\nCODE-5: TO IMPUTE RH, PM VALUES AND IMPLEMENT RH-PM CORRECTION FACTOR\n==========================================================================================\nTO DO/RELOOK:\n-> Recheck the final combined datamatrix making sure timestamp and place\n        for ground and satellite are similar\n\nINPUT           : chennai_final_combined_data\nOUTPUT          : chennai_overall_datamatrix\n==========================================================================================\n'

In [49]:
pip install datawig

Requirement already satisfied: datawig in /usr/local/lib/python3.6/dist-packages (0.1.12)
Requirement already satisfied: typing==3.6.6 in /usr/local/lib/python3.6/dist-packages (from datawig) (3.6.6)
Requirement already satisfied: mxnet==1.4.0 in /usr/local/lib/python3.6/dist-packages (from datawig) (1.4.0)
Requirement already satisfied: pandas==0.25.3 in /usr/local/lib/python3.6/dist-packages (from datawig) (0.25.3)
Requirement already satisfied: scikit-learn[alldeps]==0.22.1 in /usr/local/lib/python3.6/dist-packages (from datawig) (0.22.1)
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.6/dist-packages (from mxnet==1.4.0->datawig) (2.23.0)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from mxnet==1.4.0->datawig) (0.8.4)
Collecting numpy<1.15.0,>=1.8.2
  Downloading https://files.pythonhosted.org/packages/e5/c4/395ebb218053ba44d64935b3729bc88241ec279915e72100c5979db10945/numpy-1.14.6-cp36-cp36m-manylinux1_x86_64.whl (13.8MB)
     |████████████████████████████████| 13.8MB 317kB/s
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas==0.25.3->datawig) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas==0.25.3->datawig) (2.8.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn[alldeps]==0.22.1->datawig) (0.15.1)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn[alldeps]==0.22.1->datawig) (1.4.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->mxnet==1.4.0->datawig) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->mxnet==1.4.0->datawig) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->mxnet==1.4.0->datawig) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->mxnet==1.4.0->datawig) (2020.4.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.6.1->pandas==0.25.3->datawig) (1.12.0)
ERROR: xarray 0.15.1 has requirement numpy>=1.15, but you'll have numpy 1.14.6 which is incompatible.
ERROR: umap-learn 0.4.3 has requirement numpy>=1.17, but you'll have numpy 1.14.6 which is incompatible.
ERROR: tifffile 2020.5.30 has requirement numpy>=1.15.1, but you'll have numpy 1.14.6 which is incompatible.
ERROR: tensorflow 2.2.0 has requirement numpy<2.0,>=1.16.0, but you'll have numpy 1.14.6 which is incompatible.
ERROR: spacy 2.2.4 has requirement numpy>=1.15.0, but you'll have numpy 1.14.6 which is incompatible.
ERROR: plotnine 0.6.0 has requirement numpy>=1.16.0, but you'll have numpy 1.14.6 which is incompatible.
ERROR: numba 0.48.0 has requirement numpy>=1.15, but you'll have numpy 1.14.6 which is incompatible.
ERROR: imgaug 0.2.9 has requirement numpy>=1.15.0, but you'll have numpy 1.14.6 which is incompatible.
ERROR: google-colab 1.0.0 has requirement pandas~=1.0.0; python_version >= "3.0", but you'll have pandas 0.25.3 which is incompatible.
ERROR: fastai 1.0.61 has requirement numpy>=1.15, but you'll have numpy 1.14.6 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: cvxpy 1.0.31 has requirement numpy>=1.15, but you'll have numpy 1.14.6 which is incompatible.
ERROR: blis 0.4.1 has requirement numpy>=1.15.0, but you'll have numpy 1.14.6 which is incompatible.
ERROR: astropy 4.0.1.post1 has requirement numpy>=1.16, but you'll have numpy 1.14.6 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
Installing collected packages: numpy
  Found existing installation: numpy 1.18.4
    Uninstalling numpy-1.18.4:
      Successfully uninstalled numpy-1.18.4
Successfully installed numpy-1.14.6

In [0]:
import pandas as pd
import datawig  #for imputation
import numpy as np

In [0]:
chennai_combined_data = pd.read_csv("chennai_final_combined_data7.csv")

In [52]:
chennai_combined_data

      Unnamed: 0  PM2.5  ...  Land_sea_Flag  Land_Ocean_Quality_Flag
0              0   0.00  ...            1.0                  -9999.0
1              1   0.00  ...            1.0                  -9999.0
2              2   0.00  ...            1.0                  -9999.0
3              3  34.27  ...            1.0                  -9999.0
4              4  29.32  ...            1.0                  -9999.0
...          ...    ...  ...            ...                      ...
1029         205   7.34  ...            1.0                      3.0
1030         206  38.72  ...            1.0                  -9999.0
1031         207  14.41  ...            1.0                  -9999.0
1032         208  23.86  ...            1.0                  -9999.0
1033         209  25.73  ...            1.0                  -9999.0

[1034 rows x 21 columns]

In [0]:
#PM IMPUTATION
#1. Dividing into year-wise data for imputation
def year_wise(str, year):
     return chennai_combined_data[chennai_combined_data[str] == year]  
yr_2016 = year_wise('Year', 2016)
yr_2017 = year_wise('Year', 2017)
yr_2018 = year_wise('Year', 2018)
yr_2019 = year_wise('Year', 2019)
yr_2020 = year_wise('Year', 2020)

In [54]:
chennai_combined_data.groupby(['Year']).size().reset_index(name='count')

     Year  count
0  2016.0    232
1  2017.0    208
2  2018.0    198
3  2019.0    186
4  2020.0    210

In [0]:
# IMPUTATION
#df - yearwise dataframe to be imputed, str - column name
#month_num - month number, null_value - null value that is to be refilled 
#Imputation is done for every month, in a certain place, based on weights(distance) of latitude and longitude 
#Haversine formula is not included to make things simpler

In [0]:
def imputation(df, str1, str2, str3,):
    
    def month_wise_df(df, month_num, str1, str2, str3, null_value):
        df_mon = df[df['Month'] == month_num]
        
        x_columns = ['Latitude', 'Longitude','Place']
        
        value = df_mon[df_mon[str1] != null_value]
        no_value = df_mon[df_mon[str1] == null_value]
        
        imputer = datawig.SimpleImputer(
            input_columns = x_columns, # column(s) containing information about the column we want to impute
            output_column = str1, # the column we'd like to impute values for
            output_path = 'datawig_imputation' # stores model data and metrics
            )
        imputer.fit(train_df = value, num_epochs = 120)
        imputed = imputer.predict(no_value)
        imputed.head()
        
        datawig_imputation_data = list()
        predictions = np.asarray(imputed[str2])
        cnt = 0
        for i in range(df_mon.shape[0]):
            if(df_mon.iloc[i][str1] == null_value):
                datawig_imputation_data.append(predictions[cnt])
                cnt+=1
            else:
                datawig_imputation_data.append(df_mon.iloc[i][str1])
        print(cnt,"rows have been imputed")
        df_mon[str3] = np.asarray(datawig_imputation_data)
        
        return df_mon
        
    mon_1 = month_wise_df(df, 1, str1, str2, str3, 0)
    mon_2 = month_wise_df(df, 2, str1, str2, str3, 0)
    mon_3 = month_wise_df(df, 3, str1, str2, str3, 0)
    
    month_dflist = [mon_1, mon_2, mon_3]
    imputed_monthwise_df = pd.DataFrame()
    for mon in month_dflist:
        imputed_monthwise_df = imputed_monthwise_df.append(mon)
        
    return imputed_monthwise_df

In [60]:
#calling Imputation for filling PM values
yr_2016_PM_imputed = imputation(yr_2016,'PM2.5','PM2.5_imputed','PM_updated')
yr_2017_PM_imputed = imputation(yr_2017,'PM2.5','PM2.5_imputed','PM_updated')
yr_2018_PM_imputed = imputation(yr_2018,'PM2.5','PM2.5_imputed','PM_updated')
yr_2019_PM_imputed = imputation(yr_2019,'PM2.5','PM2.5_imputed','PM_updated')
yr_2020_PM_imputed = imputation(yr_2020,'PM2.5','PM2.5_imputed','PM_updated')

2020-06-09 14:58:53,807 [INFO]
========== start: fit model
2020-06-09 14:58:53,811 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:58:53,867 [INFO]  Epoch[0] Batch [0-2]	Speed: 1002.25 samples/sec	cross-entropy=11.345235	PM2.5-accuracy=0.000000
2020-06-09 14:58:53,887 [INFO]  Epoch[0] Train-cross-entropy=16.210867
2020-06-09 14:58:53,891 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:53,893 [INFO]  Epoch[0] Time cost=0.078
2020-06-09 14:58:53,899 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:58:53,917 [INFO]  Epoch[0] Validation-cross-entropy=8.075699
2020-06-09 14:58:53,922 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:53,974 [INFO]  Epoch[1] Batch [0-2]	Speed: 1024.37 samples/sec	cross-entropy=10.652667	PM2.5-accuracy=0.000000
2020-06-09 14:58:53,995 [INFO]  Epoch[1] Train-cross-entropy=15.675165
2020-06-09 14:58:54,000 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,004 [INFO]  Epoch[1] Time cost=0.078
2020-06-09 14:58:54,011 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:58:54,030 [INFO]  Epoch[1] Validation-cross-entropy=8.104671
2020-06-09 14:58:54,035 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,089 [INFO]  Epoch[2] Batch [0-2]	Speed: 988.68 samples/sec	cross-entropy=10.452376	PM2.5-accuracy=0.000000
2020-06-09 14:58:54,111 [INFO]  Epoch[2] Train-cross-entropy=15.524899
2020-06-09 14:58:54,115 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,119 [INFO]  Epoch[2] Time cost=0.080
2020-06-09 14:58:54,127 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:58:54,146 [INFO]  Epoch[2] Validation-cross-entropy=8.165354
2020-06-09 14:58:54,151 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,204 [INFO]  Epoch[3] Batch [0-2]	Speed: 1012.96 samples/sec	cross-entropy=10.425891	PM2.5-accuracy=0.000000
2020-06-09 14:58:54,225 [INFO]  Epoch[3] Train-cross-entropy=15.480772
2020-06-09 14:58:54,230 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,234 [INFO]  Epoch[3] Time cost=0.078
2020-06-09 14:58:54,240 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:58:54,259 [INFO]  Epoch[3] Validation-cross-entropy=8.203191
2020-06-09 14:58:54,263 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,316 [INFO]  Epoch[4] Batch [0-2]	Speed: 996.47 samples/sec	cross-entropy=10.414758	PM2.5-accuracy=0.000000
2020-06-09 14:58:54,337 [INFO]  Epoch[4] Train-cross-entropy=15.443670
2020-06-09 14:58:54,342 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,346 [INFO]  Epoch[4] Time cost=0.078
2020-06-09 14:58:54,352 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:58:54,371 [INFO]  Epoch[4] Validation-cross-entropy=8.146700
2020-06-09 14:58:54,377 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,430 [INFO]  Epoch[5] Batch [0-2]	Speed: 997.77 samples/sec	cross-entropy=10.407951	PM2.5-accuracy=0.000000
2020-06-09 14:58:54,451 [INFO]  Epoch[5] Train-cross-entropy=15.404073
2020-06-09 14:58:54,456 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,460 [INFO]  Epoch[5] Time cost=0.079
2020-06-09 14:58:54,467 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:58:54,485 [INFO]  Epoch[5] Validation-cross-entropy=8.026841
2020-06-09 14:58:54,489 [INFO]  Epoch[5] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,541 [INFO]  Epoch[6] Batch [0-2]	Speed: 1014.27 samples/sec	cross-entropy=10.394188	PM2.5-accuracy=0.000000
2020-06-09 14:58:54,561 [INFO]  Epoch[6] Train-cross-entropy=15.359746
2020-06-09 14:58:54,566 [INFO]  Epoch[6] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,570 [INFO]  Epoch[6] Time cost=0.077
2020-06-09 14:58:54,576 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:58:54,594 [INFO]  Epoch[6] Validation-cross-entropy=7.930461
2020-06-09 14:58:54,599 [INFO]  Epoch[6] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,652 [INFO]  Epoch[7] Batch [0-2]	Speed: 994.68 samples/sec	cross-entropy=10.392550	PM2.5-accuracy=0.000000
2020-06-09 14:58:54,673 [INFO]  Epoch[7] Train-cross-entropy=15.329038
2020-06-09 14:58:54,678 [INFO]  Epoch[7] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,683 [INFO]  Epoch[7] Time cost=0.080
2020-06-09 14:58:54,689 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:58:54,708 [INFO]  Epoch[7] Validation-cross-entropy=7.893802
2020-06-09 14:58:54,713 [INFO]  Epoch[7] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,770 [INFO]  Epoch[8] Batch [0-2]	Speed: 948.19 samples/sec	cross-entropy=10.380478	PM2.5-accuracy=0.000000
2020-06-09 14:58:54,791 [INFO]  Epoch[8] Train-cross-entropy=15.293946
2020-06-09 14:58:54,801 [INFO]  Epoch[8] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,804 [INFO]  Epoch[8] Time cost=0.085
2020-06-09 14:58:54,811 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-09 14:58:54,830 [INFO]  Epoch[8] Validation-cross-entropy=7.904583
2020-06-09 14:58:54,835 [INFO]  Epoch[8] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,889 [INFO]  Epoch[9] Batch [0-2]	Speed: 985.63 samples/sec	cross-entropy=10.360898	PM2.5-accuracy=0.000000
2020-06-09 14:58:54,910 [INFO]  Epoch[9] Train-cross-entropy=15.257214
2020-06-09 14:58:54,913 [INFO]  Epoch[9] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:54,918 [INFO]  Epoch[9] Time cost=0.079
2020-06-09 14:58:54,924 [INFO]  Saved checkpoint to "datawig_imputation/model-0009.params"
2020-06-09 14:58:54,942 [INFO]  Epoch[9] Validation-cross-entropy=7.933978
2020-06-09 14:58:54,945 [INFO]  Epoch[9] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,000 [INFO]  Epoch[10] Batch [0-2]	Speed: 979.49 samples/sec	cross-entropy=10.339591	PM2.5-accuracy=0.000000
2020-06-09 14:58:55,021 [INFO]  Epoch[10] Train-cross-entropy=15.220646
2020-06-09 14:58:55,024 [INFO]  Epoch[10] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,028 [INFO]  Epoch[10] Time cost=0.078
2020-06-09 14:58:55,034 [INFO]  Saved checkpoint to "datawig_imputation/model-0010.params"
2020-06-09 14:58:55,052 [INFO]  Epoch[10] Validation-cross-entropy=7.963318
2020-06-09 14:58:55,056 [INFO]  Epoch[10] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,108 [INFO]  Epoch[11] Batch [0-2]	Speed: 1016.57 samples/sec	cross-entropy=10.325258	PM2.5-accuracy=0.000000
2020-06-09 14:58:55,129 [INFO]  Epoch[11] Train-cross-entropy=15.190450
2020-06-09 14:58:55,133 [INFO]  Epoch[11] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,137 [INFO]  Epoch[11] Time cost=0.076
2020-06-09 14:58:55,142 [INFO]  Saved checkpoint to "datawig_imputation/model-0011.params"
2020-06-09 14:58:55,160 [INFO]  Epoch[11] Validation-cross-entropy=7.987871
2020-06-09 14:58:55,164 [INFO]  Epoch[11] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,216 [INFO]  Epoch[12] Batch [0-2]	Speed: 1009.49 samples/sec	cross-entropy=10.317230	PM2.5-accuracy=0.000000
2020-06-09 14:58:55,236 [INFO]  Epoch[12] Train-cross-entropy=15.164634
2020-06-09 14:58:55,239 [INFO]  Epoch[12] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,244 [INFO]  Epoch[12] Time cost=0.076
2020-06-09 14:58:55,249 [INFO]  Saved checkpoint to "datawig_imputation/model-0012.params"
2020-06-09 14:58:55,267 [INFO]  No improvement detected for 5 epochs compared to 7.893802165985107 last error obtained: 7.998985290527344, stopping here
2020-06-09 14:58:55,270 [INFO]
========== done (1.4635639190673828 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

14 rows have been imputed

2020-06-09 14:58:55,593 [INFO]
========== start: fit model
2020-06-09 14:58:55,597 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:58:55,654 [INFO]  Epoch[0] Batch [0-2]	Speed: 1003.87 samples/sec	cross-entropy=18.352882	PM2.5-accuracy=0.000000
2020-06-09 14:58:55,674 [INFO]  Epoch[0] Train-cross-entropy=14.501904
2020-06-09 14:58:55,678 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,681 [INFO]  Epoch[0] Time cost=0.078
2020-06-09 14:58:55,687 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:58:55,704 [INFO]  Epoch[0] Validation-cross-entropy=5.456439
2020-06-09 14:58:55,707 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,759 [INFO]  Epoch[1] Batch [0-2]	Speed: 1021.12 samples/sec	cross-entropy=17.559775	PM2.5-accuracy=0.000000
2020-06-09 14:58:55,780 [INFO]  Epoch[1] Train-cross-entropy=13.793141
2020-06-09 14:58:55,785 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,789 [INFO]  Epoch[1] Time cost=0.078
2020-06-09 14:58:55,796 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:58:55,818 [INFO]  Epoch[1] Validation-cross-entropy=5.113689
2020-06-09 14:58:55,823 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,876 [INFO]  Epoch[2] Batch [0-2]	Speed: 1000.33 samples/sec	cross-entropy=17.344273	PM2.5-accuracy=0.000000
2020-06-09 14:58:55,897 [INFO]  Epoch[2] Train-cross-entropy=13.563314
2020-06-09 14:58:55,902 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,907 [INFO]  Epoch[2] Time cost=0.079
2020-06-09 14:58:55,914 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:58:55,932 [INFO]  Epoch[2] Validation-cross-entropy=6.470554
2020-06-09 14:58:55,937 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:55,990 [INFO]  Epoch[3] Batch [0-2]	Speed: 999.07 samples/sec	cross-entropy=17.338761	PM2.5-accuracy=0.000000
2020-06-09 14:58:56,011 [INFO]  Epoch[3] Train-cross-entropy=13.561623
2020-06-09 14:58:56,016 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:56,020 [INFO]  Epoch[3] Time cost=0.079
2020-06-09 14:58:56,026 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:58:56,044 [INFO]  Epoch[3] Validation-cross-entropy=7.465403
2020-06-09 14:58:56,049 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:56,100 [INFO]  Epoch[4] Batch [0-2]	Speed: 1016.32 samples/sec	cross-entropy=17.399304	PM2.5-accuracy=0.000000
2020-06-09 14:58:56,121 [INFO]  Epoch[4] Train-cross-entropy=13.617689
2020-06-09 14:58:56,123 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:56,129 [INFO]  Epoch[4] Time cost=0.076
2020-06-09 14:58:56,134 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:58:56,153 [INFO]  Epoch[4] Validation-cross-entropy=7.360920
2020-06-09 14:58:56,158 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:56,210 [INFO]  Epoch[5] Batch [0-2]	Speed: 995.39 samples/sec	cross-entropy=17.386145	PM2.5-accuracy=0.000000
2020-06-09 14:58:56,231 [INFO]  Epoch[5] Train-cross-entropy=13.615003
2020-06-09 14:58:56,236 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:56,240 [INFO]  Epoch[5] Time cost=0.078
2020-06-09 14:58:56,245 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:58:56,263 [INFO]  No improvement detected for 5 epochs compared to 5.45643949508667 last error obtained: 6.708418369293213, stopping here
2020-06-09 14:58:56,268 [INFO]
========== done (0.6752898693084717 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

11 rows have been imputed

2020-06-09 14:58:56,614 [INFO]
========== start: fit model
2020-06-09 14:58:56,619 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:58:56,675 [INFO]  Epoch[0] Batch [0-2]	Speed: 1008.19 samples/sec	cross-entropy=15.786303	PM2.5-accuracy=0.000000
2020-06-09 14:58:56,697 [INFO]  Epoch[0] Train-cross-entropy=15.189493
2020-06-09 14:58:56,702 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:56,707 [INFO]  Epoch[0] Time cost=0.082
2020-06-09 14:58:56,715 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:58:56,734 [INFO]  Epoch[0] Validation-cross-entropy=11.419115
2020-06-09 14:58:56,739 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:56,793 [INFO]  Epoch[1] Batch [0-2]	Speed: 990.92 samples/sec	cross-entropy=12.677509	PM2.5-accuracy=0.000000
2020-06-09 14:58:56,816 [INFO]  Epoch[1] Train-cross-entropy=13.420330
2020-06-09 14:58:56,822 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:56,827 [INFO]  Epoch[1] Time cost=0.083
2020-06-09 14:58:56,835 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:58:56,854 [INFO]  Epoch[1] Validation-cross-entropy=8.715384
2020-06-09 14:58:56,859 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:56,914 [INFO]  Epoch[2] Batch [0-2]	Speed: 977.85 samples/sec	cross-entropy=11.917748	PM2.5-accuracy=0.000000
2020-06-09 14:58:56,935 [INFO]  Epoch[2] Train-cross-entropy=13.080537
2020-06-09 14:58:56,939 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:56,943 [INFO]  Epoch[2] Time cost=0.080
2020-06-09 14:58:56,950 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:58:56,968 [INFO]  Epoch[2] Validation-cross-entropy=7.906425
2020-06-09 14:58:56,972 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:57,025 [INFO]  Epoch[3] Batch [0-2]	Speed: 975.14 samples/sec	cross-entropy=11.289075	PM2.5-accuracy=0.000000
2020-06-09 14:58:57,046 [INFO]  Epoch[3] Train-cross-entropy=12.603295
2020-06-09 14:58:57,051 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:57,056 [INFO]  Epoch[3] Time cost=0.079
2020-06-09 14:58:57,062 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:58:57,081 [INFO]  Epoch[3] Validation-cross-entropy=8.049402
2020-06-09 14:58:57,084 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:57,140 [INFO]  Epoch[4] Batch [0-2]	Speed: 949.63 samples/sec	cross-entropy=11.318196	PM2.5-accuracy=0.000000
2020-06-09 14:58:57,163 [INFO]  Epoch[4] Train-cross-entropy=12.520082
2020-06-09 14:58:57,168 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:57,172 [INFO]  Epoch[4] Time cost=0.083
2020-06-09 14:58:57,178 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:58:57,197 [INFO]  Epoch[4] Validation-cross-entropy=8.477513
2020-06-09 14:58:57,202 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:57,255 [INFO]  Epoch[5] Batch [0-2]	Speed: 992.84 samples/sec	cross-entropy=11.481908	PM2.5-accuracy=0.000000
2020-06-09 14:58:57,276 [INFO]  Epoch[5] Train-cross-entropy=12.489563
2020-06-09 14:58:57,281 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:57,285 [INFO]  Epoch[5] Time cost=0.079
2020-06-09 14:58:57,291 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:58:57,310 [INFO]  Epoch[5] Validation-cross-entropy=8.767394
2020-06-09 14:58:57,314 [INFO]  Epoch[5] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:57,366 [INFO]  Epoch[6] Batch [0-2]	Speed: 1008.23 samples/sec	cross-entropy=11.531913	PM2.5-accuracy=0.000000
2020-06-09 14:58:57,387 [INFO]  Epoch[6] Train-cross-entropy=12.413020
2020-06-09 14:58:57,392 [INFO]  Epoch[6] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:57,397 [INFO]  Epoch[6] Time cost=0.079
2020-06-09 14:58:57,403 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:58:57,422 [INFO]  Epoch[6] Validation-cross-entropy=8.873236
2020-06-09 14:58:57,427 [INFO]  Epoch[6] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:57,480 [INFO]  Epoch[7] Batch [0-2]	Speed: 990.09 samples/sec	cross-entropy=11.568968	PM2.5-accuracy=0.000000
2020-06-09 14:58:57,502 [INFO]  Epoch[7] Train-cross-entropy=12.406651
2020-06-09 14:58:57,507 [INFO]  Epoch[7] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:57,511 [INFO]  Epoch[7] Time cost=0.080
2020-06-09 14:58:57,518 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:58:57,537 [INFO]  No improvement detected for 5 epochs compared to 7.906425476074219 last error obtained: 8.80850887298584, stopping here
2020-06-09 14:58:57,542 [INFO]
========== done (0.9292359352111816 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

11 rows have been imputed

2020-06-09 14:58:57,933 [INFO]
========== start: fit model
2020-06-09 14:58:57,938 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:58:57,978 [INFO]  Epoch[0] Batch [0-1]	Speed: 1014.94 samples/sec	cross-entropy=15.221191	PM2.5-accuracy=0.000000
2020-06-09 14:58:57,983 [INFO]  Epoch[0] Train-cross-entropy=15.221191
2020-06-09 14:58:57,987 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:57,990 [INFO]  Epoch[0] Time cost=0.047
2020-06-09 14:58:57,996 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:58:58,014 [INFO]  Epoch[0] Validation-cross-entropy=9.870314
2020-06-09 14:58:58,019 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,055 [INFO]  Epoch[1] Batch [0-1]	Speed: 1017.63 samples/sec	cross-entropy=11.900692	PM2.5-accuracy=0.000000
2020-06-09 14:58:58,058 [INFO]  Epoch[1] Train-cross-entropy=11.900692
2020-06-09 14:58:58,065 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,070 [INFO]  Epoch[1] Time cost=0.047
2020-06-09 14:58:58,076 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:58:58,096 [INFO]  Epoch[1] Validation-cross-entropy=15.051738
2020-06-09 14:58:58,099 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,136 [INFO]  Epoch[2] Batch [0-1]	Speed: 1001.89 samples/sec	cross-entropy=9.622982	PM2.5-accuracy=0.000000
2020-06-09 14:58:58,142 [INFO]  Epoch[2] Train-cross-entropy=9.622982
2020-06-09 14:58:58,147 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,152 [INFO]  Epoch[2] Time cost=0.048
2020-06-09 14:58:58,159 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:58:58,177 [INFO]  Epoch[2] Validation-cross-entropy=21.824104
2020-06-09 14:58:58,181 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,218 [INFO]  Epoch[3] Batch [0-1]	Speed: 1006.85 samples/sec	cross-entropy=8.210097	PM2.5-accuracy=0.000000
2020-06-09 14:58:58,223 [INFO]  Epoch[3] Train-cross-entropy=8.210097
2020-06-09 14:58:58,228 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,232 [INFO]  Epoch[3] Time cost=0.046
2020-06-09 14:58:58,238 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:58:58,256 [INFO]  Epoch[3] Validation-cross-entropy=29.195557
2020-06-09 14:58:58,260 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,296 [INFO]  Epoch[4] Batch [0-1]	Speed: 1010.52 samples/sec	cross-entropy=7.738182	PM2.5-accuracy=0.000000
2020-06-09 14:58:58,302 [INFO]  Epoch[4] Train-cross-entropy=7.738182
2020-06-09 14:58:58,307 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,311 [INFO]  Epoch[4] Time cost=0.046
2020-06-09 14:58:58,317 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:58:58,337 [INFO]  Epoch[4] Validation-cross-entropy=35.823235
2020-06-09 14:58:58,342 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,381 [INFO]  Epoch[5] Batch [0-1]	Speed: 999.67 samples/sec	cross-entropy=7.794042	PM2.5-accuracy=0.000000
2020-06-09 14:58:58,385 [INFO]  Epoch[5] Train-cross-entropy=7.794042
2020-06-09 14:58:58,391 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,395 [INFO]  Epoch[5] Time cost=0.047
2020-06-09 14:58:58,401 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:58:58,422 [INFO]  No improvement detected for 5 epochs compared to 9.87031364440918 last error obtained: 40.52263259887695, stopping here
2020-06-09 14:58:58,427 [INFO]
========== done (0.4942488670349121 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

42 rows have been imputed

2020-06-09 14:58:58,793 [INFO]
========== start: fit model
2020-06-09 14:58:58,799 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:58:58,836 [INFO]  Epoch[0] Batch [0-1]	Speed: 1031.02 samples/sec	cross-entropy=16.686365	PM2.5-accuracy=0.000000
2020-06-09 14:58:58,840 [INFO]  Epoch[0] Train-cross-entropy=16.686365
2020-06-09 14:58:58,845 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,849 [INFO]  Epoch[0] Time cost=0.046
2020-06-09 14:58:58,856 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:58:58,877 [INFO]  Epoch[0] Validation-cross-entropy=2.654953
2020-06-09 14:58:58,881 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,917 [INFO]  Epoch[1] Batch [0-1]	Speed: 1010.89 samples/sec	cross-entropy=12.779438	PM2.5-accuracy=0.000000
2020-06-09 14:58:58,921 [INFO]  Epoch[1] Train-cross-entropy=12.779438
2020-06-09 14:58:58,925 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,929 [INFO]  Epoch[1] Time cost=0.044
2020-06-09 14:58:58,934 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:58:58,952 [INFO]  Epoch[1] Validation-cross-entropy=2.824356
2020-06-09 14:58:58,956 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:58,993 [INFO]  Epoch[2] Batch [0-1]	Speed: 1002.48 samples/sec	cross-entropy=10.608742	PM2.5-accuracy=0.000000
2020-06-09 14:58:58,999 [INFO]  Epoch[2] Train-cross-entropy=10.608742
2020-06-09 14:58:59,003 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,007 [INFO]  Epoch[2] Time cost=0.048
2020-06-09 14:58:59,014 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:58:59,033 [INFO]  Epoch[2] Validation-cross-entropy=3.603506
2020-06-09 14:58:59,037 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,075 [INFO]  Epoch[3] Batch [0-1]	Speed: 937.07 samples/sec	cross-entropy=9.555577	PM2.5-accuracy=0.000000
2020-06-09 14:58:59,080 [INFO]  Epoch[3] Train-cross-entropy=9.555577
2020-06-09 14:58:59,083 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,087 [INFO]  Epoch[3] Time cost=0.046
2020-06-09 14:58:59,093 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:58:59,111 [INFO]  Epoch[3] Validation-cross-entropy=4.920185
2020-06-09 14:58:59,117 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,153 [INFO]  Epoch[4] Batch [0-1]	Speed: 1022.18 samples/sec	cross-entropy=8.950678	PM2.5-accuracy=0.000000
2020-06-09 14:58:59,157 [INFO]  Epoch[4] Train-cross-entropy=8.950678
2020-06-09 14:58:59,160 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,164 [INFO]  Epoch[4] Time cost=0.043
2020-06-09 14:58:59,170 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:58:59,188 [INFO]  Epoch[4] Validation-cross-entropy=6.596867
2020-06-09 14:58:59,191 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,228 [INFO]  Epoch[5] Batch [0-1]	Speed: 1009.67 samples/sec	cross-entropy=8.506580	PM2.5-accuracy=0.000000
2020-06-09 14:58:59,232 [INFO]  Epoch[5] Train-cross-entropy=8.506580
2020-06-09 14:58:59,236 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,240 [INFO]  Epoch[5] Time cost=0.044
2020-06-09 14:58:59,246 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:58:59,264 [INFO]  No improvement detected for 5 epochs compared to 2.6549530029296875 last error obtained: 8.388639450073242, stopping here
2020-06-09 14:58:59,267 [INFO]
========== done (0.4749603271484375 s) fit model

38 rows have been imputed

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
2020-06-09 14:58:59,626 [INFO]
========== start: fit model
2020-06-09 14:58:59,632 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:58:59,672 [INFO]  Epoch[0] Batch [0-1]	Speed: 1006.98 samples/sec	cross-entropy=15.030273	PM2.5-accuracy=0.000000
2020-06-09 14:58:59,678 [INFO]  Epoch[0] Train-cross-entropy=15.030273
2020-06-09 14:58:59,682 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,686 [INFO]  Epoch[0] Time cost=0.048
2020-06-09 14:58:59,694 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:58:59,714 [INFO]  Epoch[0] Validation-cross-entropy=4.184320
2020-06-09 14:58:59,721 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,757 [INFO]  Epoch[1] Batch [0-1]	Speed: 1019.07 samples/sec	cross-entropy=13.977502	PM2.5-accuracy=0.000000
2020-06-09 14:58:59,761 [INFO]  Epoch[1] Train-cross-entropy=13.977502
2020-06-09 14:58:59,764 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,768 [INFO]  Epoch[1] Time cost=0.044
2020-06-09 14:58:59,775 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:58:59,793 [INFO]  Epoch[1] Validation-cross-entropy=5.040277
2020-06-09 14:58:59,798 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,836 [INFO]  Epoch[2] Batch [0-1]	Speed: 994.88 samples/sec	cross-entropy=13.246997	PM2.5-accuracy=0.000000
2020-06-09 14:58:59,841 [INFO]  Epoch[2] Train-cross-entropy=13.246997
2020-06-09 14:58:59,845 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,849 [INFO]  Epoch[2] Time cost=0.046
2020-06-09 14:58:59,857 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:58:59,885 [INFO]  Epoch[2] Validation-cross-entropy=5.785511
2020-06-09 14:58:59,891 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,930 [INFO]  Epoch[3] Batch [0-1]	Speed: 992.09 samples/sec	cross-entropy=12.829570	PM2.5-accuracy=0.000000
2020-06-09 14:58:59,935 [INFO]  Epoch[3] Train-cross-entropy=12.829570
2020-06-09 14:58:59,939 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:58:59,943 [INFO]  Epoch[3] Time cost=0.046
2020-06-09 14:58:59,949 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:58:59,968 [INFO]  Epoch[3] Validation-cross-entropy=6.668622
2020-06-09 14:58:59,973 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,012 [INFO]  Epoch[4] Batch [0-1]	Speed: 952.66 samples/sec	cross-entropy=12.503158	PM2.5-accuracy=0.000000
2020-06-09 14:59:00,018 [INFO]  Epoch[4] Train-cross-entropy=12.503158
2020-06-09 14:59:00,023 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,028 [INFO]  Epoch[4] Time cost=0.050
2020-06-09 14:59:00,035 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:00,053 [INFO]  Epoch[4] Validation-cross-entropy=7.752173
2020-06-09 14:59:00,059 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,096 [INFO]  Epoch[5] Batch [0-1]	Speed: 997.53 samples/sec	cross-entropy=12.265673	PM2.5-accuracy=0.000000
2020-06-09 14:59:00,101 [INFO]  Epoch[5] Train-cross-entropy=12.265673
2020-06-09 14:59:00,106 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,111 [INFO]  Epoch[5] Time cost=0.047
2020-06-09 14:59:00,118 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:00,137 [INFO]  No improvement detected for 5 epochs compared to 4.184319972991943 last error obtained: 8.960392951965332, stopping here
2020-06-09 14:59:00,141 [INFO]
========== done (0.5155801773071289 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

42 rows have been imputed

2020-06-09 14:59:00,509 [INFO]
========== start: fit model
2020-06-09 14:59:00,518 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:00,572 [INFO]  Epoch[0] Batch [0-2]	Speed: 1016.82 samples/sec	cross-entropy=14.637582	PM2.5-accuracy=0.000000
2020-06-09 14:59:00,577 [INFO]  Epoch[0] Train-cross-entropy=14.637582
2020-06-09 14:59:00,582 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,588 [INFO]  Epoch[0] Time cost=0.064
2020-06-09 14:59:00,595 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:00,614 [INFO]  Epoch[0] Validation-cross-entropy=0.399521
2020-06-09 14:59:00,618 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,669 [INFO]  Epoch[1] Batch [0-2]	Speed: 1029.81 samples/sec	cross-entropy=13.951778	PM2.5-accuracy=0.000000
2020-06-09 14:59:00,674 [INFO]  Epoch[1] Train-cross-entropy=13.951778
2020-06-09 14:59:00,677 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,681 [INFO]  Epoch[1] Time cost=0.059
2020-06-09 14:59:00,686 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:00,704 [INFO]  Epoch[1] Validation-cross-entropy=0.344844
2020-06-09 14:59:00,708 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,761 [INFO]  Epoch[2] Batch [0-2]	Speed: 990.41 samples/sec	cross-entropy=13.853712	PM2.5-accuracy=0.000000
2020-06-09 14:59:00,765 [INFO]  Epoch[2] Train-cross-entropy=13.853712
2020-06-09 14:59:00,769 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,773 [INFO]  Epoch[2] Time cost=0.061
2020-06-09 14:59:00,779 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:00,797 [INFO]  Epoch[2] Validation-cross-entropy=0.239248
2020-06-09 14:59:00,800 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,856 [INFO]  Epoch[3] Batch [0-2]	Speed: 1009.87 samples/sec	cross-entropy=13.784998	PM2.5-accuracy=0.000000
2020-06-09 14:59:00,861 [INFO]  Epoch[3] Train-cross-entropy=13.784998
2020-06-09 14:59:00,866 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,871 [INFO]  Epoch[3] Time cost=0.064
2020-06-09 14:59:00,878 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:00,901 [INFO]  Epoch[3] Validation-cross-entropy=0.128694
2020-06-09 14:59:00,905 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,957 [INFO]  Epoch[4] Batch [0-2]	Speed: 1019.47 samples/sec	cross-entropy=13.877933	PM2.5-accuracy=0.000000
2020-06-09 14:59:00,961 [INFO]  Epoch[4] Train-cross-entropy=13.877933
2020-06-09 14:59:00,965 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:00,969 [INFO]  Epoch[4] Time cost=0.060
2020-06-09 14:59:00,974 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:00,992 [INFO]  Epoch[4] Validation-cross-entropy=0.151069
2020-06-09 14:59:00,996 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,049 [INFO]  Epoch[5] Batch [0-2]	Speed: 1005.07 samples/sec	cross-entropy=13.820609	PM2.5-accuracy=0.000000
2020-06-09 14:59:01,053 [INFO]  Epoch[5] Train-cross-entropy=13.820609
2020-06-09 14:59:01,057 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,061 [INFO]  Epoch[5] Time cost=0.061
2020-06-09 14:59:01,066 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:01,084 [INFO]  Epoch[5] Validation-cross-entropy=0.150433
2020-06-09 14:59:01,088 [INFO]  Epoch[5] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,144 [INFO]  Epoch[6] Batch [0-2]	Speed: 929.13 samples/sec	cross-entropy=13.748949	PM2.5-accuracy=0.000000
2020-06-09 14:59:01,149 [INFO]  Epoch[6] Train-cross-entropy=13.748949
2020-06-09 14:59:01,153 [INFO]  Epoch[6] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,156 [INFO]  Epoch[6] Time cost=0.063
2020-06-09 14:59:01,162 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:01,180 [INFO]  Epoch[6] Validation-cross-entropy=0.251516
2020-06-09 14:59:01,184 [INFO]  Epoch[6] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,241 [INFO]  Epoch[7] Batch [0-2]	Speed: 878.13 samples/sec	cross-entropy=13.698292	PM2.5-accuracy=0.000000
2020-06-09 14:59:01,246 [INFO]  Epoch[7] Train-cross-entropy=13.698292
2020-06-09 14:59:01,250 [INFO]  Epoch[7] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,254 [INFO]  Epoch[7] Time cost=0.066
2020-06-09 14:59:01,261 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:59:01,280 [INFO]  Epoch[7] Validation-cross-entropy=0.199980
2020-06-09 14:59:01,283 [INFO]  Epoch[7] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,336 [INFO]  Epoch[8] Batch [0-2]	Speed: 1003.32 samples/sec	cross-entropy=13.609938	PM2.5-accuracy=0.000000
2020-06-09 14:59:01,339 [INFO]  Epoch[8] Train-cross-entropy=13.609938
2020-06-09 14:59:01,343 [INFO]  Epoch[8] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,346 [INFO]  Epoch[8] Time cost=0.060
2020-06-09 14:59:01,353 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-09 14:59:01,371 [INFO]  No improvement detected for 5 epochs compared to 0.12869375944137573 last error obtained: 0.17372219264507294, stopping here
2020-06-09 14:59:01,375 [INFO]
========== done (0.8662447929382324 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

16 rows have been imputed

2020-06-09 14:59:01,621 [INFO]
========== start: fit model
2020-06-09 14:59:01,628 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:01,683 [INFO]  Epoch[0] Batch [0-2]	Speed: 1001.04 samples/sec	cross-entropy=14.005911	PM2.5-accuracy=0.000000
2020-06-09 14:59:01,688 [INFO]  Epoch[0] Train-cross-entropy=14.005911
2020-06-09 14:59:01,691 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,695 [INFO]  Epoch[0] Time cost=0.062
2020-06-09 14:59:01,701 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:01,719 [INFO]  Epoch[0] Validation-cross-entropy=3.039149
2020-06-09 14:59:01,722 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,777 [INFO]  Epoch[1] Batch [0-2]	Speed: 994.99 samples/sec	cross-entropy=13.271592	PM2.5-accuracy=0.000000
2020-06-09 14:59:01,782 [INFO]  Epoch[1] Train-cross-entropy=13.271592
2020-06-09 14:59:01,786 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,790 [INFO]  Epoch[1] Time cost=0.063
2020-06-09 14:59:01,796 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:01,815 [INFO]  Epoch[1] Validation-cross-entropy=4.318490
2020-06-09 14:59:01,821 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,876 [INFO]  Epoch[2] Batch [0-2]	Speed: 1010.09 samples/sec	cross-entropy=13.269264	PM2.5-accuracy=0.000000
2020-06-09 14:59:01,881 [INFO]  Epoch[2] Train-cross-entropy=13.269264
2020-06-09 14:59:01,886 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,890 [INFO]  Epoch[2] Time cost=0.062
2020-06-09 14:59:01,899 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:01,922 [INFO]  Epoch[2] Validation-cross-entropy=3.411153
2020-06-09 14:59:01,927 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,981 [INFO]  Epoch[3] Batch [0-2]	Speed: 1000.90 samples/sec	cross-entropy=12.912163	PM2.5-accuracy=0.000000
2020-06-09 14:59:01,986 [INFO]  Epoch[3] Train-cross-entropy=12.912163
2020-06-09 14:59:01,991 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:01,995 [INFO]  Epoch[3] Time cost=0.063
2020-06-09 14:59:02,002 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:02,022 [INFO]  Epoch[3] Validation-cross-entropy=2.490775
2020-06-09 14:59:02,028 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,081 [INFO]  Epoch[4] Batch [0-2]	Speed: 992.51 samples/sec	cross-entropy=12.946574	PM2.5-accuracy=0.000000
2020-06-09 14:59:02,086 [INFO]  Epoch[4] Train-cross-entropy=12.946574
2020-06-09 14:59:02,091 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,095 [INFO]  Epoch[4] Time cost=0.063
2020-06-09 14:59:02,103 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:02,122 [INFO]  Epoch[4] Validation-cross-entropy=2.207879
2020-06-09 14:59:02,127 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,180 [INFO]  Epoch[5] Batch [0-2]	Speed: 1007.30 samples/sec	cross-entropy=12.959553	PM2.5-accuracy=0.000000
2020-06-09 14:59:02,185 [INFO]  Epoch[5] Train-cross-entropy=12.959553
2020-06-09 14:59:02,190 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,194 [INFO]  Epoch[5] Time cost=0.063
2020-06-09 14:59:02,201 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:02,220 [INFO]  Epoch[5] Validation-cross-entropy=2.475026
2020-06-09 14:59:02,225 [INFO]  Epoch[5] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,278 [INFO]  Epoch[6] Batch [0-2]	Speed: 1006.21 samples/sec	cross-entropy=12.838422	PM2.5-accuracy=0.000000
2020-06-09 14:59:02,284 [INFO]  Epoch[6] Train-cross-entropy=12.838422
2020-06-09 14:59:02,289 [INFO]  Epoch[6] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,293 [INFO]  Epoch[6] Time cost=0.063
2020-06-09 14:59:02,300 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:02,319 [INFO]  Epoch[6] Validation-cross-entropy=3.118111
2020-06-09 14:59:02,325 [INFO]  Epoch[6] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,379 [INFO]  Epoch[7] Batch [0-2]	Speed: 989.54 samples/sec	cross-entropy=12.806410	PM2.5-accuracy=0.000000
2020-06-09 14:59:02,385 [INFO]  Epoch[7] Train-cross-entropy=12.806410
2020-06-09 14:59:02,389 [INFO]  Epoch[7] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,394 [INFO]  Epoch[7] Time cost=0.064
2020-06-09 14:59:02,402 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:59:02,421 [INFO]  Epoch[7] Validation-cross-entropy=3.748659
2020-06-09 14:59:02,426 [INFO]  Epoch[7] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,480 [INFO]  Epoch[8] Batch [0-2]	Speed: 1011.46 samples/sec	cross-entropy=12.834480	PM2.5-accuracy=0.000000
2020-06-09 14:59:02,486 [INFO]  Epoch[8] Train-cross-entropy=12.834480
2020-06-09 14:59:02,490 [INFO]  Epoch[8] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,496 [INFO]  Epoch[8] Time cost=0.064
2020-06-09 14:59:02,503 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-09 14:59:02,522 [INFO]  Epoch[8] Validation-cross-entropy=3.970336
2020-06-09 14:59:02,527 [INFO]  Epoch[8] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,580 [INFO]  Epoch[9] Batch [0-2]	Speed: 956.97 samples/sec	cross-entropy=12.807612	PM2.5-accuracy=0.000000
2020-06-09 14:59:02,585 [INFO]  Epoch[9] Train-cross-entropy=12.807612
2020-06-09 14:59:02,589 [INFO]  Epoch[9] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:02,593 [INFO]  Epoch[9] Time cost=0.062
2020-06-09 14:59:02,599 [INFO]  Saved checkpoint to "datawig_imputation/model-0009.params"
2020-06-09 14:59:02,619 [INFO]  No improvement detected for 5 epochs compared to 2.207878828048706 last error obtained: 3.785609245300293, stopping here
2020-06-09 14:59:02,624 [INFO]
========== done (1.0035953521728516 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

11 rows have been imputed

2020-06-09 14:59:02,967 [INFO]
========== start: fit model
2020-06-09 14:59:02,974 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:03,030 [INFO]  Epoch[0] Batch [0-2]	Speed: 1000.53 samples/sec	cross-entropy=11.934125	PM2.5-accuracy=0.000000
2020-06-09 14:59:03,051 [INFO]  Epoch[0] Train-cross-entropy=13.373390
2020-06-09 14:59:03,056 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,060 [INFO]  Epoch[0] Time cost=0.081
2020-06-09 14:59:03,067 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:03,086 [INFO]  Epoch[0] Validation-cross-entropy=24.400137
2020-06-09 14:59:03,090 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,143 [INFO]  Epoch[1] Batch [0-2]	Speed: 1003.35 samples/sec	cross-entropy=12.179408	PM2.5-accuracy=0.000000
2020-06-09 14:59:03,164 [INFO]  Epoch[1] Train-cross-entropy=13.131501
2020-06-09 14:59:03,169 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,173 [INFO]  Epoch[1] Time cost=0.079
2020-06-09 14:59:03,180 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:03,199 [INFO]  Epoch[1] Validation-cross-entropy=21.747194
2020-06-09 14:59:03,204 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,257 [INFO]  Epoch[2] Batch [0-2]	Speed: 990.32 samples/sec	cross-entropy=12.120974	PM2.5-accuracy=0.000000
2020-06-09 14:59:03,279 [INFO]  Epoch[2] Train-cross-entropy=13.165897
2020-06-09 14:59:03,284 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,289 [INFO]  Epoch[2] Time cost=0.080
2020-06-09 14:59:03,295 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:03,314 [INFO]  Epoch[2] Validation-cross-entropy=21.299541
2020-06-09 14:59:03,323 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,377 [INFO]  Epoch[3] Batch [0-2]	Speed: 956.72 samples/sec	cross-entropy=11.716020	PM2.5-accuracy=0.000000
2020-06-09 14:59:03,398 [INFO]  Epoch[3] Train-cross-entropy=13.010253
2020-06-09 14:59:03,402 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,406 [INFO]  Epoch[3] Time cost=0.078
2020-06-09 14:59:03,412 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:03,431 [INFO]  Epoch[3] Validation-cross-entropy=21.967319
2020-06-09 14:59:03,435 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,487 [INFO]  Epoch[4] Batch [0-2]	Speed: 1008.19 samples/sec	cross-entropy=11.478739	PM2.5-accuracy=0.000000
2020-06-09 14:59:03,507 [INFO]  Epoch[4] Train-cross-entropy=12.857999
2020-06-09 14:59:03,511 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,515 [INFO]  Epoch[4] Time cost=0.077
2020-06-09 14:59:03,521 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:03,539 [INFO]  Epoch[4] Validation-cross-entropy=22.906820
2020-06-09 14:59:03,544 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,597 [INFO]  Epoch[5] Batch [0-2]	Speed: 985.85 samples/sec	cross-entropy=11.437729	PM2.5-accuracy=0.000000
2020-06-09 14:59:03,618 [INFO]  Epoch[5] Train-cross-entropy=12.761112
2020-06-09 14:59:03,621 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,626 [INFO]  Epoch[5] Time cost=0.078
2020-06-09 14:59:03,632 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:03,649 [INFO]  Epoch[5] Validation-cross-entropy=23.492167
2020-06-09 14:59:03,654 [INFO]  Epoch[5] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,706 [INFO]  Epoch[6] Batch [0-2]	Speed: 1017.16 samples/sec	cross-entropy=11.508591	PM2.5-accuracy=0.000000
2020-06-09 14:59:03,728 [INFO]  Epoch[6] Train-cross-entropy=12.744216
2020-06-09 14:59:03,732 [INFO]  Epoch[6] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:03,736 [INFO]  Epoch[6] Time cost=0.078
2020-06-09 14:59:03,742 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:03,760 [INFO]  No improvement detected for 5 epochs compared to 21.747194290161133 last error obtained: 23.48052978515625, stopping here
2020-06-09 14:59:03,765 [INFO]
========== done (0.7981281280517578 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

11 rows have been imputed

2020-06-09 14:59:04,071 [INFO]
========== start: fit model
2020-06-09 14:59:04,075 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:04,136 [INFO]  Epoch[0] Batch [0-2]	Speed: 950.20 samples/sec	cross-entropy=15.846202	PM2.5-accuracy=0.000000
2020-06-09 14:59:04,141 [INFO]  Epoch[0] Train-cross-entropy=15.846202
2020-06-09 14:59:04,145 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,148 [INFO]  Epoch[0] Time cost=0.066
2020-06-09 14:59:04,161 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:04,182 [INFO]  Epoch[0] Validation-cross-entropy=44.704174
2020-06-09 14:59:04,187 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,242 [INFO]  Epoch[1] Batch [0-2]	Speed: 995.73 samples/sec	cross-entropy=14.280640	PM2.5-accuracy=0.000000
2020-06-09 14:59:04,247 [INFO]  Epoch[1] Train-cross-entropy=14.280640
2020-06-09 14:59:04,251 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,254 [INFO]  Epoch[1] Time cost=0.063
2020-06-09 14:59:04,260 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:04,278 [INFO]  Epoch[1] Validation-cross-entropy=39.700275
2020-06-09 14:59:04,282 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,335 [INFO]  Epoch[2] Batch [0-2]	Speed: 966.81 samples/sec	cross-entropy=14.093703	PM2.5-accuracy=0.000000
2020-06-09 14:59:04,340 [INFO]  Epoch[2] Train-cross-entropy=14.093703
2020-06-09 14:59:04,344 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,347 [INFO]  Epoch[2] Time cost=0.061
2020-06-09 14:59:04,353 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:04,370 [INFO]  Epoch[2] Validation-cross-entropy=36.878109
2020-06-09 14:59:04,375 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,429 [INFO]  Epoch[3] Batch [0-2]	Speed: 949.11 samples/sec	cross-entropy=14.189281	PM2.5-accuracy=0.000000
2020-06-09 14:59:04,433 [INFO]  Epoch[3] Train-cross-entropy=14.189281
2020-06-09 14:59:04,437 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,441 [INFO]  Epoch[3] Time cost=0.063
2020-06-09 14:59:04,447 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:04,465 [INFO]  Epoch[3] Validation-cross-entropy=36.300564
2020-06-09 14:59:04,470 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,523 [INFO]  Epoch[4] Batch [0-2]	Speed: 998.75 samples/sec	cross-entropy=14.243150	PM2.5-accuracy=0.000000
2020-06-09 14:59:04,528 [INFO]  Epoch[4] Train-cross-entropy=14.243150
2020-06-09 14:59:04,532 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,535 [INFO]  Epoch[4] Time cost=0.061
2020-06-09 14:59:04,541 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:04,559 [INFO]  Epoch[4] Validation-cross-entropy=37.146450
2020-06-09 14:59:04,564 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,615 [INFO]  Epoch[5] Batch [0-2]	Speed: 1019.33 samples/sec	cross-entropy=14.105511	PM2.5-accuracy=0.000000
2020-06-09 14:59:04,620 [INFO]  Epoch[5] Train-cross-entropy=14.105511
2020-06-09 14:59:04,623 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,627 [INFO]  Epoch[5] Time cost=0.059
2020-06-09 14:59:04,632 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:04,650 [INFO]  Epoch[5] Validation-cross-entropy=38.562611
2020-06-09 14:59:04,654 [INFO]  Epoch[5] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,706 [INFO]  Epoch[6] Batch [0-2]	Speed: 1000.27 samples/sec	cross-entropy=13.973387	PM2.5-accuracy=0.000000
2020-06-09 14:59:04,711 [INFO]  Epoch[6] Train-cross-entropy=13.973387
2020-06-09 14:59:04,715 [INFO]  Epoch[6] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,718 [INFO]  Epoch[6] Time cost=0.061
2020-06-09 14:59:04,724 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:04,743 [INFO]  Epoch[6] Validation-cross-entropy=39.788376
2020-06-09 14:59:04,748 [INFO]  Epoch[6] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,806 [INFO]  Epoch[7] Batch [0-2]	Speed: 880.57 samples/sec	cross-entropy=13.923613	PM2.5-accuracy=0.000000
2020-06-09 14:59:04,811 [INFO]  Epoch[7] Train-cross-entropy=13.923613
2020-06-09 14:59:04,817 [INFO]  Epoch[7] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:04,821 [INFO]  Epoch[7] Time cost=0.069
2020-06-09 14:59:04,828 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:59:04,846 [INFO]  No improvement detected for 5 epochs compared to 36.878108978271484 last error obtained: 40.30576705932617, stopping here
2020-06-09 14:59:04,851 [INFO]
========== done (0.7804834842681885 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

11 rows have been imputed

2020-06-09 14:59:05,167 [INFO]
========== start: fit model
2020-06-09 14:59:05,173 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:05,226 [INFO]  Epoch[0] Batch [0-2]	Speed: 1019.66 samples/sec	cross-entropy=14.013715	PM2.5-accuracy=0.000000
2020-06-09 14:59:05,229 [INFO]  Epoch[0] Train-cross-entropy=14.013715
2020-06-09 14:59:05,234 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:05,238 [INFO]  Epoch[0] Time cost=0.060
2020-06-09 14:59:05,243 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:05,261 [INFO]  Epoch[0] Validation-cross-entropy=0.882853
2020-06-09 14:59:05,265 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:05,318 [INFO]  Epoch[1] Batch [0-2]	Speed: 981.96 samples/sec	cross-entropy=13.849790	PM2.5-accuracy=0.000000
2020-06-09 14:59:05,323 [INFO]  Epoch[1] Train-cross-entropy=13.849790
2020-06-09 14:59:05,327 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:05,331 [INFO]  Epoch[1] Time cost=0.062
2020-06-09 14:59:05,336 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:05,354 [INFO]  Epoch[1] Validation-cross-entropy=1.302991
2020-06-09 14:59:05,360 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:05,414 [INFO]  Epoch[2] Batch [0-2]	Speed: 974.91 samples/sec	cross-entropy=13.497541	PM2.5-accuracy=0.000000
2020-06-09 14:59:05,419 [INFO]  Epoch[2] Train-cross-entropy=13.497541
2020-06-09 14:59:05,424 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:05,428 [INFO]  Epoch[2] Time cost=0.064
2020-06-09 14:59:05,434 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:05,453 [INFO]  Epoch[2] Validation-cross-entropy=1.490816
2020-06-09 14:59:05,458 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:05,511 [INFO]  Epoch[3] Batch [0-2]	Speed: 1014.57 samples/sec	cross-entropy=13.202966	PM2.5-accuracy=0.000000
2020-06-09 14:59:05,516 [INFO]  Epoch[3] Train-cross-entropy=13.202966
2020-06-09 14:59:05,520 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:05,524 [INFO]  Epoch[3] Time cost=0.062
2020-06-09 14:59:05,530 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:05,548 [INFO]  Epoch[3] Validation-cross-entropy=1.689384
2020-06-09 14:59:05,553 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:05,605 [INFO]  Epoch[4] Batch [0-2]	Speed: 998.00 samples/sec	cross-entropy=13.005652	PM2.5-accuracy=0.000000
2020-06-09 14:59:05,610 [INFO]  Epoch[4] Train-cross-entropy=13.005652
2020-06-09 14:59:05,615 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:05,619 [INFO]  Epoch[4] Time cost=0.063
2020-06-09 14:59:05,626 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:05,645 [INFO]  Epoch[4] Validation-cross-entropy=2.011005
2020-06-09 14:59:05,650 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:05,703 [INFO]  Epoch[5] Batch [0-2]	Speed: 990.40 samples/sec	cross-entropy=12.997342	PM2.5-accuracy=0.000000
2020-06-09 14:59:05,708 [INFO]  Epoch[5] Train-cross-entropy=12.997342
2020-06-09 14:59:05,713 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:05,717 [INFO]  Epoch[5] Time cost=0.063
2020-06-09 14:59:05,723 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:05,742 [INFO]  No improvement detected for 5 epochs compared to 0.8828533291816711 last error obtained: 2.4365875720977783, stopping here
2020-06-09 14:59:05,747 [INFO]
========== done (0.5809991359710693 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

10 rows have been imputed

2020-06-09 14:59:06,104 [INFO]
========== start: fit model
2020-06-09 14:59:06,112 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:06,168 [INFO]  Epoch[0] Batch [0-2]	Speed: 996.47 samples/sec	cross-entropy=15.242361	PM2.5-accuracy=0.000000
2020-06-09 14:59:06,189 [INFO]  Epoch[0] Train-cross-entropy=11.909575
2020-06-09 14:59:06,194 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:06,198 [INFO]  Epoch[0] Time cost=0.080
2020-06-09 14:59:06,205 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:06,225 [INFO]  Epoch[0] Validation-cross-entropy=1.301535
2020-06-09 14:59:06,231 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:06,284 [INFO]  Epoch[1] Batch [0-2]	Speed: 986.17 samples/sec	cross-entropy=14.777186	PM2.5-accuracy=0.000000
2020-06-09 14:59:06,306 [INFO]  Epoch[1] Train-cross-entropy=11.594443
2020-06-09 14:59:06,311 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:06,317 [INFO]  Epoch[1] Time cost=0.082
2020-06-09 14:59:06,324 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:06,343 [INFO]  Epoch[1] Validation-cross-entropy=1.300559
2020-06-09 14:59:06,349 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:06,401 [INFO]  Epoch[2] Batch [0-2]	Speed: 1004.11 samples/sec	cross-entropy=14.369425	PM2.5-accuracy=0.000000
2020-06-09 14:59:06,422 [INFO]  Epoch[2] Train-cross-entropy=11.292512
2020-06-09 14:59:06,427 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:06,432 [INFO]  Epoch[2] Time cost=0.079
2020-06-09 14:59:06,438 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:06,456 [INFO]  Epoch[2] Validation-cross-entropy=1.320086
2020-06-09 14:59:06,461 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:06,514 [INFO]  Epoch[3] Batch [0-2]	Speed: 989.61 samples/sec	cross-entropy=14.097661	PM2.5-accuracy=0.000000
2020-06-09 14:59:06,535 [INFO]  Epoch[3] Train-cross-entropy=10.985720
2020-06-09 14:59:06,541 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:06,545 [INFO]  Epoch[3] Time cost=0.080
2020-06-09 14:59:06,551 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:06,569 [INFO]  Epoch[3] Validation-cross-entropy=1.428491
2020-06-09 14:59:06,575 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:06,629 [INFO]  Epoch[4] Batch [0-2]	Speed: 983.26 samples/sec	cross-entropy=14.119952	PM2.5-accuracy=0.000000
2020-06-09 14:59:06,650 [INFO]  Epoch[4] Train-cross-entropy=10.955382
2020-06-09 14:59:06,655 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:06,659 [INFO]  Epoch[4] Time cost=0.080
2020-06-09 14:59:06,665 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:06,685 [INFO]  Epoch[4] Validation-cross-entropy=1.547642
2020-06-09 14:59:06,689 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:06,741 [INFO]  Epoch[5] Batch [0-2]	Speed: 1012.25 samples/sec	cross-entropy=14.006042	PM2.5-accuracy=0.000000
2020-06-09 14:59:06,761 [INFO]  Epoch[5] Train-cross-entropy=10.893048
2020-06-09 14:59:06,765 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:06,769 [INFO]  Epoch[5] Time cost=0.076
2020-06-09 14:59:06,775 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:06,792 [INFO]  No improvement detected for 5 epochs compared to 1.3015350103378296 last error obtained: 1.386428952217102, stopping here
2020-06-09 14:59:06,797 [INFO]
========== done (0.6933774948120117 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

9 rows have been imputed

2020-06-09 14:59:07,147 [INFO]
========== start: fit model
2020-06-09 14:59:07,150 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:07,193 [INFO]  Epoch[0] Batch [0-1]	Speed: 995.64 samples/sec	cross-entropy=14.830739	PM2.5-accuracy=0.000000
2020-06-09 14:59:07,197 [INFO]  Epoch[0] Train-cross-entropy=14.830739
2020-06-09 14:59:07,201 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,205 [INFO]  Epoch[0] Time cost=0.048
2020-06-09 14:59:07,211 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:07,229 [INFO]  Epoch[0] Validation-cross-entropy=2.542719
2020-06-09 14:59:07,234 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,270 [INFO]  Epoch[1] Batch [0-1]	Speed: 998.45 samples/sec	cross-entropy=12.292464	PM2.5-accuracy=0.000000
2020-06-09 14:59:07,275 [INFO]  Epoch[1] Train-cross-entropy=12.292464
2020-06-09 14:59:07,278 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,282 [INFO]  Epoch[1] Time cost=0.044
2020-06-09 14:59:07,288 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:07,305 [INFO]  Epoch[1] Validation-cross-entropy=0.511627
2020-06-09 14:59:07,309 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,345 [INFO]  Epoch[2] Batch [0-1]	Speed: 1022.74 samples/sec	cross-entropy=11.367468	PM2.5-accuracy=0.000000
2020-06-09 14:59:07,351 [INFO]  Epoch[2] Train-cross-entropy=11.367468
2020-06-09 14:59:07,355 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,359 [INFO]  Epoch[2] Time cost=0.046
2020-06-09 14:59:07,364 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:07,384 [INFO]  Epoch[2] Validation-cross-entropy=0.316600
2020-06-09 14:59:07,390 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,431 [INFO]  Epoch[3] Batch [0-1]	Speed: 893.55 samples/sec	cross-entropy=10.993304	PM2.5-accuracy=0.000000
2020-06-09 14:59:07,437 [INFO]  Epoch[3] Train-cross-entropy=10.993304
2020-06-09 14:59:07,442 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,447 [INFO]  Epoch[3] Time cost=0.052
2020-06-09 14:59:07,455 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:07,474 [INFO]  Epoch[3] Validation-cross-entropy=0.801342
2020-06-09 14:59:07,480 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,519 [INFO]  Epoch[4] Batch [0-1]	Speed: 976.56 samples/sec	cross-entropy=10.772656	PM2.5-accuracy=0.000000
2020-06-09 14:59:07,524 [INFO]  Epoch[4] Train-cross-entropy=10.772656
2020-06-09 14:59:07,528 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,533 [INFO]  Epoch[4] Time cost=0.048
2020-06-09 14:59:07,540 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:07,558 [INFO]  Epoch[4] Validation-cross-entropy=1.325647
2020-06-09 14:59:07,564 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,601 [INFO]  Epoch[5] Batch [0-1]	Speed: 997.90 samples/sec	cross-entropy=10.553560	PM2.5-accuracy=0.000000
2020-06-09 14:59:07,606 [INFO]  Epoch[5] Train-cross-entropy=10.553560
2020-06-09 14:59:07,611 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,615 [INFO]  Epoch[5] Time cost=0.047
2020-06-09 14:59:07,622 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:07,640 [INFO]  Epoch[5] Validation-cross-entropy=1.616452
2020-06-09 14:59:07,645 [INFO]  Epoch[5] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,682 [INFO]  Epoch[6] Batch [0-1]	Speed: 1018.87 samples/sec	cross-entropy=10.314543	PM2.5-accuracy=0.000000
2020-06-09 14:59:07,687 [INFO]  Epoch[6] Train-cross-entropy=10.314543
2020-06-09 14:59:07,691 [INFO]  Epoch[6] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:07,695 [INFO]  Epoch[6] Time cost=0.045
2020-06-09 14:59:07,701 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:07,720 [INFO]  No improvement detected for 5 epochs compared to 0.5116268992424011 last error obtained: 1.6418261528015137, stopping here
2020-06-09 14:59:07,726 [INFO]
========== done (0.5786492824554443 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

32 rows have been imputed

2020-06-09 14:59:08,156 [INFO]
========== start: fit model
2020-06-09 14:59:08,161 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:08,215 [INFO]  Epoch[0] Batch [0-2]	Speed: 1012.28 samples/sec	cross-entropy=10.764598	PM2.5-accuracy=0.000000
2020-06-09 14:59:08,219 [INFO]  Epoch[0] Train-cross-entropy=10.764598
2020-06-09 14:59:08,224 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,228 [INFO]  Epoch[0] Time cost=0.061
2020-06-09 14:59:08,234 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:08,253 [INFO]  Epoch[0] Validation-cross-entropy=2.273558
2020-06-09 14:59:08,256 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,308 [INFO]  Epoch[1] Batch [0-2]	Speed: 1023.88 samples/sec	cross-entropy=5.878419	PM2.5-accuracy=0.000000
2020-06-09 14:59:08,313 [INFO]  Epoch[1] Train-cross-entropy=5.878419
2020-06-09 14:59:08,317 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,322 [INFO]  Epoch[1] Time cost=0.062
2020-06-09 14:59:08,329 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:08,348 [INFO]  Epoch[1] Validation-cross-entropy=4.660034
2020-06-09 14:59:08,351 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,405 [INFO]  Epoch[2] Batch [0-2]	Speed: 998.87 samples/sec	cross-entropy=5.638820	PM2.5-accuracy=0.000000
2020-06-09 14:59:08,410 [INFO]  Epoch[2] Train-cross-entropy=5.638820
2020-06-09 14:59:08,414 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,419 [INFO]  Epoch[2] Time cost=0.063
2020-06-09 14:59:08,427 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:08,445 [INFO]  Epoch[2] Validation-cross-entropy=6.023993
2020-06-09 14:59:08,449 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,502 [INFO]  Epoch[3] Batch [0-2]	Speed: 1012.68 samples/sec	cross-entropy=6.205784	PM2.5-accuracy=0.000000
2020-06-09 14:59:08,506 [INFO]  Epoch[3] Train-cross-entropy=6.205784
2020-06-09 14:59:08,510 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,513 [INFO]  Epoch[3] Time cost=0.060
2020-06-09 14:59:08,522 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:08,540 [INFO]  Epoch[3] Validation-cross-entropy=4.958241
2020-06-09 14:59:08,543 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,595 [INFO]  Epoch[4] Batch [0-2]	Speed: 1021.38 samples/sec	cross-entropy=5.697544	PM2.5-accuracy=0.000000
2020-06-09 14:59:08,600 [INFO]  Epoch[4] Train-cross-entropy=5.697544
2020-06-09 14:59:08,604 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,609 [INFO]  Epoch[4] Time cost=0.061
2020-06-09 14:59:08,615 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:08,634 [INFO]  Epoch[4] Validation-cross-entropy=3.112484
2020-06-09 14:59:08,639 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,693 [INFO]  Epoch[5] Batch [0-2]	Speed: 1004.44 samples/sec	cross-entropy=5.016663	PM2.5-accuracy=0.000000
2020-06-09 14:59:08,698 [INFO]  Epoch[5] Train-cross-entropy=5.016663
2020-06-09 14:59:08,703 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,707 [INFO]  Epoch[5] Time cost=0.063
2020-06-09 14:59:08,714 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:08,734 [INFO]  Epoch[5] Validation-cross-entropy=1.945114
2020-06-09 14:59:08,739 [INFO]  Epoch[5] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,792 [INFO]  Epoch[6] Batch [0-2]	Speed: 1005.04 samples/sec	cross-entropy=4.885614	PM2.5-accuracy=0.000000
2020-06-09 14:59:08,796 [INFO]  Epoch[6] Train-cross-entropy=4.885614
2020-06-09 14:59:08,801 [INFO]  Epoch[6] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,806 [INFO]  Epoch[6] Time cost=0.062
2020-06-09 14:59:08,812 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:08,830 [INFO]  Epoch[6] Validation-cross-entropy=1.637510
2020-06-09 14:59:08,835 [INFO]  Epoch[6] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,886 [INFO]  Epoch[7] Batch [0-2]	Speed: 1027.13 samples/sec	cross-entropy=5.049964	PM2.5-accuracy=0.000000
2020-06-09 14:59:08,890 [INFO]  Epoch[7] Train-cross-entropy=5.049964
2020-06-09 14:59:08,895 [INFO]  Epoch[7] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,899 [INFO]  Epoch[7] Time cost=0.060
2020-06-09 14:59:08,905 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:59:08,926 [INFO]  Epoch[7] Validation-cross-entropy=1.690650
2020-06-09 14:59:08,930 [INFO]  Epoch[7] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:08,983 [INFO]  Epoch[8] Batch [0-2]	Speed: 1005.58 samples/sec	cross-entropy=5.055396	PM2.5-accuracy=0.000000
2020-06-09 14:59:08,989 [INFO]  Epoch[8] Train-cross-entropy=5.055396
2020-06-09 14:59:08,993 [INFO]  Epoch[8] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,000 [INFO]  Epoch[8] Time cost=0.065
2020-06-09 14:59:09,009 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-09 14:59:09,032 [INFO]  Epoch[8] Validation-cross-entropy=1.823048
2020-06-09 14:59:09,038 [INFO]  Epoch[8] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,091 [INFO]  Epoch[9] Batch [0-2]	Speed: 999.83 samples/sec	cross-entropy=4.892208	PM2.5-accuracy=0.000000
2020-06-09 14:59:09,095 [INFO]  Epoch[9] Train-cross-entropy=4.892208
2020-06-09 14:59:09,100 [INFO]  Epoch[9] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,105 [INFO]  Epoch[9] Time cost=0.062
2020-06-09 14:59:09,111 [INFO]  Saved checkpoint to "datawig_imputation/model-0009.params"
2020-06-09 14:59:09,130 [INFO]  Epoch[9] Validation-cross-entropy=2.077170
2020-06-09 14:59:09,135 [INFO]  Epoch[9] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,187 [INFO]  Epoch[10] Batch [0-2]	Speed: 1008.99 samples/sec	cross-entropy=4.786933	PM2.5-accuracy=0.000000
2020-06-09 14:59:09,191 [INFO]  Epoch[10] Train-cross-entropy=4.786933
2020-06-09 14:59:09,196 [INFO]  Epoch[10] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,200 [INFO]  Epoch[10] Time cost=0.061
2020-06-09 14:59:09,206 [INFO]  Saved checkpoint to "datawig_imputation/model-0010.params"
2020-06-09 14:59:09,225 [INFO]  Epoch[10] Validation-cross-entropy=2.431185
2020-06-09 14:59:09,229 [INFO]  Epoch[10] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,282 [INFO]  Epoch[11] Batch [0-2]	Speed: 999.33 samples/sec	cross-entropy=4.792010	PM2.5-accuracy=0.000000
2020-06-09 14:59:09,287 [INFO]  Epoch[11] Train-cross-entropy=4.792010
2020-06-09 14:59:09,292 [INFO]  Epoch[11] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,296 [INFO]  Epoch[11] Time cost=0.062
2020-06-09 14:59:09,303 [INFO]  Saved checkpoint to "datawig_imputation/model-0011.params"
2020-06-09 14:59:09,322 [INFO]  No improvement detected for 5 epochs compared to 1.637510061264038 last error obtained: 2.6796255111694336, stopping here
2020-06-09 14:59:09,327 [INFO]
========== done (1.1708576679229736 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

30 rows have been imputed

2020-06-09 14:59:09,657 [INFO]
========== start: fit model
2020-06-09 14:59:09,663 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:09,718 [INFO]  Epoch[0] Batch [0-2]	Speed: 1006.64 samples/sec	cross-entropy=12.694298	PM2.5-accuracy=0.000000
2020-06-09 14:59:09,739 [INFO]  Epoch[0] Train-cross-entropy=11.142404
2020-06-09 14:59:09,744 [INFO]  Epoch[0] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,749 [INFO]  Epoch[0] Time cost=0.080
2020-06-09 14:59:09,755 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:09,773 [INFO]  Epoch[0] Validation-cross-entropy=6.505476
2020-06-09 14:59:09,777 [INFO]  Epoch[0] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,829 [INFO]  Epoch[1] Batch [0-2]	Speed: 1020.00 samples/sec	cross-entropy=8.627203	PM2.5-accuracy=0.000000
2020-06-09 14:59:09,850 [INFO]  Epoch[1] Train-cross-entropy=7.001240
2020-06-09 14:59:09,854 [INFO]  Epoch[1] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,859 [INFO]  Epoch[1] Time cost=0.077
2020-06-09 14:59:09,865 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:09,884 [INFO]  Epoch[1] Validation-cross-entropy=4.521196
2020-06-09 14:59:09,889 [INFO]  Epoch[1] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,942 [INFO]  Epoch[2] Batch [0-2]	Speed: 981.20 samples/sec	cross-entropy=10.099001	PM2.5-accuracy=0.000000
2020-06-09 14:59:09,964 [INFO]  Epoch[2] Train-cross-entropy=8.100149
2020-06-09 14:59:09,969 [INFO]  Epoch[2] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:09,973 [INFO]  Epoch[2] Time cost=0.080
2020-06-09 14:59:09,980 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:09,999 [INFO]  Epoch[2] Validation-cross-entropy=5.074518
2020-06-09 14:59:10,004 [INFO]  Epoch[2] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:10,063 [INFO]  Epoch[3] Batch [0-2]	Speed: 1008.96 samples/sec	cross-entropy=8.827969	PM2.5-accuracy=0.000000
2020-06-09 14:59:10,085 [INFO]  Epoch[3] Train-cross-entropy=7.217205
2020-06-09 14:59:10,090 [INFO]  Epoch[3] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:10,094 [INFO]  Epoch[3] Time cost=0.086
2020-06-09 14:59:10,101 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:10,119 [INFO]  Epoch[3] Validation-cross-entropy=7.429080
2020-06-09 14:59:10,124 [INFO]  Epoch[3] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:10,176 [INFO]  Epoch[4] Batch [0-2]	Speed: 1004.20 samples/sec	cross-entropy=7.735214	PM2.5-accuracy=0.000000
2020-06-09 14:59:10,198 [INFO]  Epoch[4] Train-cross-entropy=6.855572
2020-06-09 14:59:10,203 [INFO]  Epoch[4] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:10,208 [INFO]  Epoch[4] Time cost=0.080
2020-06-09 14:59:10,215 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:10,234 [INFO]  Epoch[4] Validation-cross-entropy=10.638556
2020-06-09 14:59:10,239 [INFO]  Epoch[4] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:10,293 [INFO]  Epoch[5] Batch [0-2]	Speed: 964.53 samples/sec	cross-entropy=7.505524	PM2.5-accuracy=0.000000
2020-06-09 14:59:10,317 [INFO]  Epoch[5] Train-cross-entropy=6.589574
2020-06-09 14:59:10,323 [INFO]  Epoch[5] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:10,328 [INFO]  Epoch[5] Time cost=0.084
2020-06-09 14:59:10,336 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:10,356 [INFO]  Epoch[5] Validation-cross-entropy=12.732685
2020-06-09 14:59:10,360 [INFO]  Epoch[5] Validation-PM2.5-accuracy=0.000000
2020-06-09 14:59:10,413 [INFO]  Epoch[6] Batch [0-2]	Speed: 979.98 samples/sec	cross-entropy=7.441166	PM2.5-accuracy=0.000000
2020-06-09 14:59:10,433 [INFO]  Epoch[6] Train-cross-entropy=6.216032
2020-06-09 14:59:10,437 [INFO]  Epoch[6] Train-PM2.5-accuracy=0.000000
2020-06-09 14:59:10,440 [INFO]  Epoch[6] Time cost=0.076
2020-06-09 14:59:10,447 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:10,466 [INFO]  No improvement detected for 5 epochs compared to 4.521195888519287 last error obtained: 12.955109596252441, stopping here
2020-06-09 14:59:10,471 [INFO]
========== done (0.8148107528686523 s) fit model

16 rows have been imputed

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [61]:
#calling Imputation for filling RH values
yr_2016_overall = imputation(yr_2016_PM_imputed, 'RH', 'RH_imputed', 'RH_updated')
yr_2017_overall = imputation(yr_2017_PM_imputed, 'RH', 'RH_imputed', 'RH_updated')
yr_2018_overall = imputation(yr_2018_PM_imputed, 'RH', 'RH_imputed', 'RH_updated')
yr_2019_overall = imputation(yr_2019_PM_imputed, 'RH', 'RH_imputed', 'RH_updated')
yr_2020_overall = imputation(yr_2020_PM_imputed, 'RH', 'RH_imputed', 'RH_updated')

2020-06-09 14:59:10,768 [INFO]
========== start: fit model
2020-06-09 14:59:10,772 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:10,828 [INFO]  Epoch[0] Batch [0-2]	Speed: 987.32 samples/sec	cross-entropy=17.469763	RH-accuracy=0.000000
2020-06-09 14:59:10,849 [INFO]  Epoch[0] Train-cross-entropy=15.322024
2020-06-09 14:59:10,853 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:10,857 [INFO]  Epoch[0] Time cost=0.079
2020-06-09 14:59:10,863 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:10,883 [INFO]  Epoch[0] Validation-cross-entropy=24.255781
2020-06-09 14:59:10,887 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:10,940 [INFO]  Epoch[1] Batch [0-2]	Speed: 996.78 samples/sec	cross-entropy=15.880390	RH-accuracy=0.000000
2020-06-09 14:59:10,961 [INFO]  Epoch[1] Train-cross-entropy=13.960451
2020-06-09 14:59:10,965 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:10,969 [INFO]  Epoch[1] Time cost=0.078
2020-06-09 14:59:10,982 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:11,002 [INFO]  Epoch[1] Validation-cross-entropy=26.811405
2020-06-09 14:59:11,006 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:11,066 [INFO]  Epoch[2] Batch [0-2]	Speed: 945.59 samples/sec	cross-entropy=15.449793	RH-accuracy=0.000000
2020-06-09 14:59:11,087 [INFO]  Epoch[2] Train-cross-entropy=13.581412
2020-06-09 14:59:11,092 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:11,096 [INFO]  Epoch[2] Time cost=0.086
2020-06-09 14:59:11,103 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:11,122 [INFO]  Epoch[2] Validation-cross-entropy=28.231926
2020-06-09 14:59:11,126 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:11,187 [INFO]  Epoch[3] Batch [0-2]	Speed: 803.95 samples/sec	cross-entropy=15.259220	RH-accuracy=0.000000
2020-06-09 14:59:11,208 [INFO]  Epoch[3] Train-cross-entropy=13.449936
2020-06-09 14:59:11,213 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:11,216 [INFO]  Epoch[3] Time cost=0.086
2020-06-09 14:59:11,223 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:11,241 [INFO]  Epoch[3] Validation-cross-entropy=28.558985
2020-06-09 14:59:11,245 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:11,297 [INFO]  Epoch[4] Batch [0-2]	Speed: 1015.16 samples/sec	cross-entropy=14.983880	RH-accuracy=0.000000
2020-06-09 14:59:11,317 [INFO]  Epoch[4] Train-cross-entropy=13.283373
2020-06-09 14:59:11,321 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:11,325 [INFO]  Epoch[4] Time cost=0.076
2020-06-09 14:59:11,331 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:11,349 [INFO]  Epoch[4] Validation-cross-entropy=28.559019
2020-06-09 14:59:11,353 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:11,405 [INFO]  Epoch[5] Batch [0-2]	Speed: 1003.82 samples/sec	cross-entropy=14.715503	RH-accuracy=0.000000
2020-06-09 14:59:11,425 [INFO]  Epoch[5] Train-cross-entropy=13.132561
2020-06-09 14:59:11,430 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:11,433 [INFO]  Epoch[5] Time cost=0.077
2020-06-09 14:59:11,440 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:11,459 [INFO]  No improvement detected for 5 epochs compared to 24.255781173706055 last error obtained: 28.807342529296875, stopping here
2020-06-09 14:59:11,464 [INFO]
========== done (0.6961483955383301 s) fit model

19 rows have been imputed

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
2020-06-09 14:59:11,859 [INFO]
========== start: fit model
2020-06-09 14:59:11,862 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:11,919 [INFO]  Epoch[0] Batch [0-2]	Speed: 1020.77 samples/sec	cross-entropy=16.617933	RH-accuracy=0.000000
2020-06-09 14:59:11,938 [INFO]  Epoch[0] Train-cross-entropy=16.185444
2020-06-09 14:59:11,942 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:11,946 [INFO]  Epoch[0] Time cost=0.077
2020-06-09 14:59:11,952 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:11,969 [INFO]  Epoch[0] Validation-cross-entropy=2.763333
2020-06-09 14:59:11,973 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:12,025 [INFO]  Epoch[1] Batch [0-2]	Speed: 987.80 samples/sec	cross-entropy=15.468218	RH-accuracy=0.000000
2020-06-09 14:59:12,050 [INFO]  Epoch[1] Train-cross-entropy=14.819918
2020-06-09 14:59:12,055 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:12,059 [INFO]  Epoch[1] Time cost=0.082
2020-06-09 14:59:12,065 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:12,084 [INFO]  Epoch[1] Validation-cross-entropy=2.279908
2020-06-09 14:59:12,089 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:12,144 [INFO]  Epoch[2] Batch [0-2]	Speed: 994.73 samples/sec	cross-entropy=15.342165	RH-accuracy=0.000000
2020-06-09 14:59:12,165 [INFO]  Epoch[2] Train-cross-entropy=14.241907
2020-06-09 14:59:12,169 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:12,173 [INFO]  Epoch[2] Time cost=0.080
2020-06-09 14:59:12,181 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:12,200 [INFO]  Epoch[2] Validation-cross-entropy=2.800742
2020-06-09 14:59:12,203 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:12,255 [INFO]  Epoch[3] Batch [0-2]	Speed: 1018.54 samples/sec	cross-entropy=15.498737	RH-accuracy=0.000000
2020-06-09 14:59:12,276 [INFO]  Epoch[3] Train-cross-entropy=14.078808
2020-06-09 14:59:12,280 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:12,284 [INFO]  Epoch[3] Time cost=0.076
2020-06-09 14:59:12,290 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:12,310 [INFO]  Epoch[3] Validation-cross-entropy=3.507462
2020-06-09 14:59:12,315 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:12,368 [INFO]  Epoch[4] Batch [0-2]	Speed: 993.15 samples/sec	cross-entropy=15.731875	RH-accuracy=0.000000
2020-06-09 14:59:12,390 [INFO]  Epoch[4] Train-cross-entropy=14.132471
2020-06-09 14:59:12,396 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:12,401 [INFO]  Epoch[4] Time cost=0.082
2020-06-09 14:59:12,410 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:12,430 [INFO]  Epoch[4] Validation-cross-entropy=3.132352
2020-06-09 14:59:12,436 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:12,490 [INFO]  Epoch[5] Batch [0-2]	Speed: 994.63 samples/sec	cross-entropy=15.713774	RH-accuracy=0.000000
2020-06-09 14:59:12,512 [INFO]  Epoch[5] Train-cross-entropy=14.115210
2020-06-09 14:59:12,517 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:12,520 [INFO]  Epoch[5] Time cost=0.079
2020-06-09 14:59:12,528 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:12,548 [INFO]  Epoch[5] Validation-cross-entropy=2.601483
2020-06-09 14:59:12,552 [INFO]  Epoch[5] Validation-RH-accuracy=0.000000
2020-06-09 14:59:12,603 [INFO]  Epoch[6] Batch [0-2]	Speed: 1009.49 samples/sec	cross-entropy=15.573164	RH-accuracy=0.000000
2020-06-09 14:59:12,625 [INFO]  Epoch[6] Train-cross-entropy=14.062488
2020-06-09 14:59:12,630 [INFO]  Epoch[6] Train-RH-accuracy=0.000000
2020-06-09 14:59:12,635 [INFO]  Epoch[6] Time cost=0.079
2020-06-09 14:59:12,642 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:12,661 [INFO]  No improvement detected for 5 epochs compared to 2.2799081802368164 last error obtained: 2.5095856189727783, stopping here
2020-06-09 14:59:12,666 [INFO]
========== done (0.8079116344451904 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

11 rows have been imputed

2020-06-09 14:59:12,991 [INFO]
========== start: fit model
2020-06-09 14:59:12,996 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:13,056 [INFO]  Epoch[0] Batch [0-2]	Speed: 888.17 samples/sec	cross-entropy=15.236794	RH-accuracy=0.000000
2020-06-09 14:59:13,077 [INFO]  Epoch[0] Train-cross-entropy=15.980288
2020-06-09 14:59:13,081 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:13,085 [INFO]  Epoch[0] Time cost=0.083
2020-06-09 14:59:13,091 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:13,110 [INFO]  Epoch[0] Validation-cross-entropy=6.754843
2020-06-09 14:59:13,114 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:13,165 [INFO]  Epoch[1] Batch [0-2]	Speed: 1014.41 samples/sec	cross-entropy=15.587337	RH-accuracy=0.000000
2020-06-09 14:59:13,188 [INFO]  Epoch[1] Train-cross-entropy=15.318995
2020-06-09 14:59:13,192 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:13,198 [INFO]  Epoch[1] Time cost=0.081
2020-06-09 14:59:13,204 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:13,225 [INFO]  Epoch[1] Validation-cross-entropy=10.374981
2020-06-09 14:59:13,230 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:13,283 [INFO]  Epoch[2] Batch [0-2]	Speed: 968.89 samples/sec	cross-entropy=16.055963	RH-accuracy=0.000000
2020-06-09 14:59:13,304 [INFO]  Epoch[2] Train-cross-entropy=15.363631
2020-06-09 14:59:13,309 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:13,314 [INFO]  Epoch[2] Time cost=0.081
2020-06-09 14:59:13,324 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:13,343 [INFO]  Epoch[2] Validation-cross-entropy=12.467282
2020-06-09 14:59:13,347 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:13,399 [INFO]  Epoch[3] Batch [0-2]	Speed: 993.89 samples/sec	cross-entropy=16.128170	RH-accuracy=0.000000
2020-06-09 14:59:13,421 [INFO]  Epoch[3] Train-cross-entropy=15.409970
2020-06-09 14:59:13,426 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:13,430 [INFO]  Epoch[3] Time cost=0.080
2020-06-09 14:59:13,438 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:13,457 [INFO]  Epoch[3] Validation-cross-entropy=11.457566
2020-06-09 14:59:13,462 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:13,515 [INFO]  Epoch[4] Batch [0-2]	Speed: 1000.03 samples/sec	cross-entropy=15.756362	RH-accuracy=0.000000
2020-06-09 14:59:13,537 [INFO]  Epoch[4] Train-cross-entropy=15.256933
2020-06-09 14:59:13,543 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:13,548 [INFO]  Epoch[4] Time cost=0.081
2020-06-09 14:59:13,555 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:13,576 [INFO]  Epoch[4] Validation-cross-entropy=9.920210
2020-06-09 14:59:13,580 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:13,633 [INFO]  Epoch[5] Batch [0-2]	Speed: 981.65 samples/sec	cross-entropy=15.533344	RH-accuracy=0.000000
2020-06-09 14:59:13,654 [INFO]  Epoch[5] Train-cross-entropy=15.227101
2020-06-09 14:59:13,659 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:13,662 [INFO]  Epoch[5] Time cost=0.078
2020-06-09 14:59:13,669 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:13,687 [INFO]  No improvement detected for 5 epochs compared to 6.754842758178711 last error obtained: 9.37977123260498, stopping here
2020-06-09 14:59:13,692 [INFO]
========== done (0.7020180225372314 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

11 rows have been imputed

2020-06-09 14:59:14,049 [INFO]
========== start: fit model
2020-06-09 14:59:14,053 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:14,095 [INFO]  Epoch[0] Batch [0-1]	Speed: 1026.19 samples/sec	cross-entropy=13.692802	RH-accuracy=0.000000
2020-06-09 14:59:14,099 [INFO]  Epoch[0] Train-cross-entropy=13.692802
2020-06-09 14:59:14,105 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:14,108 [INFO]  Epoch[0] Time cost=0.051
2020-06-09 14:59:14,115 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:14,133 [INFO]  Epoch[0] Validation-cross-entropy=0.084523
2020-06-09 14:59:14,138 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:14,174 [INFO]  Epoch[1] Batch [0-1]	Speed: 1001.92 samples/sec	cross-entropy=9.950670	RH-accuracy=0.000000
2020-06-09 14:59:14,179 [INFO]  Epoch[1] Train-cross-entropy=9.950670
2020-06-09 14:59:14,183 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:14,187 [INFO]  Epoch[1] Time cost=0.045
2020-06-09 14:59:14,193 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:14,211 [INFO]  Epoch[1] Validation-cross-entropy=0.192639
2020-06-09 14:59:14,216 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:14,253 [INFO]  Epoch[2] Batch [0-1]	Speed: 1002.93 samples/sec	cross-entropy=8.164223	RH-accuracy=0.000000
2020-06-09 14:59:14,258 [INFO]  Epoch[2] Train-cross-entropy=8.164223
2020-06-09 14:59:14,262 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:14,265 [INFO]  Epoch[2] Time cost=0.045
2020-06-09 14:59:14,272 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:14,290 [INFO]  Epoch[2] Validation-cross-entropy=0.562396
2020-06-09 14:59:14,294 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:14,331 [INFO]  Epoch[3] Batch [0-1]	Speed: 992.75 samples/sec	cross-entropy=7.586122	RH-accuracy=0.000000
2020-06-09 14:59:14,336 [INFO]  Epoch[3] Train-cross-entropy=7.586122
2020-06-09 14:59:14,340 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:14,344 [INFO]  Epoch[3] Time cost=0.046
2020-06-09 14:59:14,350 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:14,368 [INFO]  Epoch[3] Validation-cross-entropy=1.159699
2020-06-09 14:59:14,372 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:14,407 [INFO]  Epoch[4] Batch [0-1]	Speed: 1029.51 samples/sec	cross-entropy=7.746147	RH-accuracy=0.000000
2020-06-09 14:59:14,412 [INFO]  Epoch[4] Train-cross-entropy=7.746147
2020-06-09 14:59:14,417 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:14,422 [INFO]  Epoch[4] Time cost=0.046
2020-06-09 14:59:14,428 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:14,446 [INFO]  Epoch[4] Validation-cross-entropy=1.864539
2020-06-09 14:59:14,452 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:14,488 [INFO]  Epoch[5] Batch [0-1]	Speed: 1018.36 samples/sec	cross-entropy=8.083210	RH-accuracy=0.000000
2020-06-09 14:59:14,492 [INFO]  Epoch[5] Train-cross-entropy=8.083210
2020-06-09 14:59:14,497 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:14,501 [INFO]  Epoch[5] Time cost=0.046
2020-06-09 14:59:14,507 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:14,526 [INFO]  No improvement detected for 5 epochs compared to 0.08452270925045013 last error obtained: 2.4907784461975098, stopping here
2020-06-09 14:59:14,529 [INFO]
========== done (0.48062705993652344 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

42 rows have been imputed

2020-06-09 14:59:14,910 [INFO]
========== start: fit model
2020-06-09 14:59:14,916 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:14,955 [INFO]  Epoch[0] Batch [0-1]	Speed: 1003.21 samples/sec	cross-entropy=11.022488	RH-accuracy=0.000000
2020-06-09 14:59:14,959 [INFO]  Epoch[0] Train-cross-entropy=11.022488
2020-06-09 14:59:14,963 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:14,967 [INFO]  Epoch[0] Time cost=0.045
2020-06-09 14:59:14,973 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:14,992 [INFO]  Epoch[0] Validation-cross-entropy=3.611856
2020-06-09 14:59:14,995 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:15,032 [INFO]  Epoch[1] Batch [0-1]	Speed: 1024.25 samples/sec	cross-entropy=6.590054	RH-accuracy=0.000000
2020-06-09 14:59:15,036 [INFO]  Epoch[1] Train-cross-entropy=6.590054
2020-06-09 14:59:15,040 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:15,044 [INFO]  Epoch[1] Time cost=0.045
2020-06-09 14:59:15,050 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:15,067 [INFO]  Epoch[1] Validation-cross-entropy=6.015542
2020-06-09 14:59:15,073 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:15,112 [INFO]  Epoch[2] Batch [0-1]	Speed: 1019.47 samples/sec	cross-entropy=3.836275	RH-accuracy=0.000000
2020-06-09 14:59:15,117 [INFO]  Epoch[2] Train-cross-entropy=3.836275
2020-06-09 14:59:15,121 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:15,125 [INFO]  Epoch[2] Time cost=0.046
2020-06-09 14:59:15,132 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:15,151 [INFO]  Epoch[2] Validation-cross-entropy=8.643158
2020-06-09 14:59:15,156 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:15,193 [INFO]  Epoch[3] Batch [0-1]	Speed: 1009.64 samples/sec	cross-entropy=2.586115	RH-accuracy=0.000000
2020-06-09 14:59:15,198 [INFO]  Epoch[3] Train-cross-entropy=2.586115
2020-06-09 14:59:15,203 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:15,208 [INFO]  Epoch[3] Time cost=0.047
2020-06-09 14:59:15,215 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:15,234 [INFO]  Epoch[3] Validation-cross-entropy=11.129415
2020-06-09 14:59:15,240 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:15,279 [INFO]  Epoch[4] Batch [0-1]	Speed: 981.51 samples/sec	cross-entropy=2.541882	RH-accuracy=0.000000
2020-06-09 14:59:15,286 [INFO]  Epoch[4] Train-cross-entropy=2.541882
2020-06-09 14:59:15,292 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:15,297 [INFO]  Epoch[4] Time cost=0.051
2020-06-09 14:59:15,304 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:15,325 [INFO]  Epoch[4] Validation-cross-entropy=13.117871
2020-06-09 14:59:15,329 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:15,367 [INFO]  Epoch[5] Batch [0-1]	Speed: 1007.19 samples/sec	cross-entropy=3.060652	RH-accuracy=0.000000
2020-06-09 14:59:15,371 [INFO]  Epoch[5] Train-cross-entropy=3.060652
2020-06-09 14:59:15,375 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:15,379 [INFO]  Epoch[5] Time cost=0.045
2020-06-09 14:59:15,387 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:15,406 [INFO]  No improvement detected for 5 epochs compared to 3.6118555068969727 last error obtained: 14.30984878540039, stopping here
2020-06-09 14:59:15,411 [INFO]
========== done (0.5014874935150146 s) fit model

38 rows have been imputed

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
2020-06-09 14:59:15,781 [INFO]
========== start: fit model
2020-06-09 14:59:15,785 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:15,826 [INFO]  Epoch[0] Batch [0-1]	Speed: 997.71 samples/sec	cross-entropy=15.767568	RH-accuracy=0.000000
2020-06-09 14:59:15,831 [INFO]  Epoch[0] Train-cross-entropy=15.767568
2020-06-09 14:59:15,835 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:15,839 [INFO]  Epoch[0] Time cost=0.049
2020-06-09 14:59:15,845 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:15,864 [INFO]  Epoch[0] Validation-cross-entropy=20.840595
2020-06-09 14:59:15,868 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:15,904 [INFO]  Epoch[1] Batch [0-1]	Speed: 1003.08 samples/sec	cross-entropy=12.994169	RH-accuracy=0.000000
2020-06-09 14:59:15,909 [INFO]  Epoch[1] Train-cross-entropy=12.994169
2020-06-09 14:59:15,914 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:15,917 [INFO]  Epoch[1] Time cost=0.045
2020-06-09 14:59:15,923 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:15,941 [INFO]  Epoch[1] Validation-cross-entropy=18.944826
2020-06-09 14:59:15,945 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:15,981 [INFO]  Epoch[2] Batch [0-1]	Speed: 1019.23 samples/sec	cross-entropy=11.602028	RH-accuracy=0.000000
2020-06-09 14:59:15,986 [INFO]  Epoch[2] Train-cross-entropy=11.602028
2020-06-09 14:59:15,989 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:15,993 [INFO]  Epoch[2] Time cost=0.044
2020-06-09 14:59:15,999 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:16,017 [INFO]  Epoch[2] Validation-cross-entropy=17.170059
2020-06-09 14:59:16,021 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:16,056 [INFO]  Epoch[3] Batch [0-1]	Speed: 1030.08 samples/sec	cross-entropy=11.165517	RH-accuracy=0.000000
2020-06-09 14:59:16,060 [INFO]  Epoch[3] Train-cross-entropy=11.165517
2020-06-09 14:59:16,063 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:16,067 [INFO]  Epoch[3] Time cost=0.043
2020-06-09 14:59:16,073 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:16,094 [INFO]  Epoch[3] Validation-cross-entropy=15.603518
2020-06-09 14:59:16,099 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:16,135 [INFO]  Epoch[4] Batch [0-1]	Speed: 1009.14 samples/sec	cross-entropy=11.164970	RH-accuracy=0.000000
2020-06-09 14:59:16,139 [INFO]  Epoch[4] Train-cross-entropy=11.164970
2020-06-09 14:59:16,144 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:16,148 [INFO]  Epoch[4] Time cost=0.045
2020-06-09 14:59:16,154 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:16,173 [INFO]  Epoch[4] Validation-cross-entropy=14.370911
2020-06-09 14:59:16,176 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:16,214 [INFO]  Epoch[5] Batch [0-1]	Speed: 994.03 samples/sec	cross-entropy=11.243524	RH-accuracy=0.000000
2020-06-09 14:59:16,219 [INFO]  Epoch[5] Train-cross-entropy=11.243524
2020-06-09 14:59:16,222 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:16,226 [INFO]  Epoch[5] Time cost=0.045
2020-06-09 14:59:16,232 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:16,250 [INFO]  Epoch[5] Validation-cross-entropy=13.550374
2020-06-09 14:59:16,254 [INFO]  Epoch[5] Validation-RH-accuracy=0.000000
2020-06-09 14:59:16,291 [INFO]  Epoch[6] Batch [0-1]	Speed: 1013.94 samples/sec	cross-entropy=11.262917	RH-accuracy=0.000000
2020-06-09 14:59:16,294 [INFO]  Epoch[6] Train-cross-entropy=11.262917
2020-06-09 14:59:16,299 [INFO]  Epoch[6] Train-RH-accuracy=0.000000
2020-06-09 14:59:16,305 [INFO]  Epoch[6] Time cost=0.047
2020-06-09 14:59:16,312 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:16,330 [INFO]  Epoch[6] Validation-cross-entropy=13.127512
2020-06-09 14:59:16,333 [INFO]  Epoch[6] Validation-RH-accuracy=0.000000
2020-06-09 14:59:16,369 [INFO]  Epoch[7] Batch [0-1]	Speed: 1037.28 samples/sec	cross-entropy=11.205266	RH-accuracy=0.000000
2020-06-09 14:59:16,374 [INFO]  Epoch[7] Train-cross-entropy=11.205266
2020-06-09 14:59:16,378 [INFO]  Epoch[7] Train-RH-accuracy=0.000000
2020-06-09 14:59:16,383 [INFO]  Epoch[7] Time cost=0.045
2020-06-09 14:59:16,389 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:59:16,408 [INFO]  Epoch[7] Validation-cross-entropy=13.047735
2020-06-09 14:59:16,412 [INFO]  Epoch[7] Validation-RH-accuracy=0.000000
2020-06-09 14:59:16,450 [INFO]  Epoch[8] Batch [0-1]	Speed: 1015.68 samples/sec	cross-entropy=11.098429	RH-accuracy=0.000000
2020-06-09 14:59:16,455 [INFO]  Epoch[8] Train-cross-entropy=11.098429
2020-06-09 14:59:16,460 [INFO]  Epoch[8] Train-RH-accuracy=0.000000
2020-06-09 14:59:16,464 [INFO]  Epoch[8] Time cost=0.047
2020-06-09 14:59:16,471 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-09 14:59:16,491 [INFO]  Epoch[8] Validation-cross-entropy=13.252394
2020-06-09 14:59:16,497 [INFO]  Epoch[8] Validation-RH-accuracy=0.000000
2020-06-09 14:59:16,534 [INFO]  Epoch[9] Batch [0-1]	Speed: 1005.99 samples/sec	cross-entropy=10.969429	RH-accuracy=0.000000
2020-06-09 14:59:16,540 [INFO]  Epoch[9] Train-cross-entropy=10.969429
2020-06-09 14:59:16,545 [INFO]  Epoch[9] Train-RH-accuracy=0.000000
2020-06-09 14:59:16,550 [INFO]  Epoch[9] Time cost=0.048
2020-06-09 14:59:16,557 [INFO]  Saved checkpoint to "datawig_imputation/model-0009.params"
2020-06-09 14:59:16,577 [INFO]  Epoch[9] Validation-cross-entropy=13.681465
2020-06-09 14:59:16,582 [INFO]  Epoch[9] Validation-RH-accuracy=0.000000
2020-06-09 14:59:16,619 [INFO]  Epoch[10] Batch [0-1]	Speed: 1013.93 samples/sec	cross-entropy=10.834451	RH-accuracy=0.000000
2020-06-09 14:59:16,624 [INFO]  Epoch[10] Train-cross-entropy=10.834451
2020-06-09 14:59:16,629 [INFO]  Epoch[10] Train-RH-accuracy=0.000000
2020-06-09 14:59:16,633 [INFO]  Epoch[10] Time cost=0.046
2020-06-09 14:59:16,640 [INFO]  Saved checkpoint to "datawig_imputation/model-0010.params"
2020-06-09 14:59:16,659 [INFO]  Epoch[10] Validation-cross-entropy=14.266004
2020-06-09 14:59:16,664 [INFO]  Epoch[10] Validation-RH-accuracy=0.000000
2020-06-09 14:59:16,700 [INFO]  Epoch[11] Batch [0-1]	Speed: 1024.75 samples/sec	cross-entropy=10.707853	RH-accuracy=0.000000
2020-06-09 14:59:16,706 [INFO]  Epoch[11] Train-cross-entropy=10.707853
2020-06-09 14:59:16,710 [INFO]  Epoch[11] Train-RH-accuracy=0.000000
2020-06-09 14:59:16,715 [INFO]  Epoch[11] Time cost=0.046
2020-06-09 14:59:16,722 [INFO]  Saved checkpoint to "datawig_imputation/model-0011.params"
2020-06-09 14:59:16,742 [INFO]  No improvement detected for 5 epochs compared to 13.127511978149414 last error obtained: 14.925149917602539, stopping here
2020-06-09 14:59:16,748 [INFO]
========== done (0.9667961597442627 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

44 rows have been imputed

2020-06-09 14:59:17,144 [INFO]
========== start: fit model
2020-06-09 14:59:17,149 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:17,204 [INFO]  Epoch[0] Batch [0-2]	Speed: 985.00 samples/sec	cross-entropy=11.801728	RH-accuracy=0.000000
2020-06-09 14:59:17,208 [INFO]  Epoch[0] Train-cross-entropy=11.801728
2020-06-09 14:59:17,211 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:17,215 [INFO]  Epoch[0] Time cost=0.061
2020-06-09 14:59:17,222 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:17,242 [INFO]  Epoch[0] Validation-cross-entropy=11.188911
2020-06-09 14:59:17,247 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:17,302 [INFO]  Epoch[1] Batch [0-2]	Speed: 969.17 samples/sec	cross-entropy=10.429970	RH-accuracy=0.000000
2020-06-09 14:59:17,309 [INFO]  Epoch[1] Train-cross-entropy=10.429970
2020-06-09 14:59:17,314 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:17,320 [INFO]  Epoch[1] Time cost=0.068
2020-06-09 14:59:17,327 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:17,347 [INFO]  Epoch[1] Validation-cross-entropy=10.893596
2020-06-09 14:59:17,352 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:17,405 [INFO]  Epoch[2] Batch [0-2]	Speed: 1000.30 samples/sec	cross-entropy=10.597532	RH-accuracy=0.000000
2020-06-09 14:59:17,411 [INFO]  Epoch[2] Train-cross-entropy=10.597532
2020-06-09 14:59:17,415 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:17,419 [INFO]  Epoch[2] Time cost=0.063
2020-06-09 14:59:17,427 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:17,447 [INFO]  Epoch[2] Validation-cross-entropy=10.673499
2020-06-09 14:59:17,451 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:17,504 [INFO]  Epoch[3] Batch [0-2]	Speed: 1010.58 samples/sec	cross-entropy=10.508775	RH-accuracy=0.000000
2020-06-09 14:59:17,508 [INFO]  Epoch[3] Train-cross-entropy=10.508775
2020-06-09 14:59:17,513 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:17,517 [INFO]  Epoch[3] Time cost=0.061
2020-06-09 14:59:17,523 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:17,542 [INFO]  Epoch[3] Validation-cross-entropy=10.437453
2020-06-09 14:59:17,545 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:17,598 [INFO]  Epoch[4] Batch [0-2]	Speed: 1017.80 samples/sec	cross-entropy=10.264082	RH-accuracy=0.000000
2020-06-09 14:59:17,602 [INFO]  Epoch[4] Train-cross-entropy=10.264082
2020-06-09 14:59:17,606 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:17,610 [INFO]  Epoch[4] Time cost=0.061
2020-06-09 14:59:17,617 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:17,635 [INFO]  Epoch[4] Validation-cross-entropy=10.282411
2020-06-09 14:59:17,639 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:17,691 [INFO]  Epoch[5] Batch [0-2]	Speed: 1006.63 samples/sec	cross-entropy=10.108543	RH-accuracy=0.000000
2020-06-09 14:59:17,696 [INFO]  Epoch[5] Train-cross-entropy=10.108543
2020-06-09 14:59:17,700 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:17,704 [INFO]  Epoch[5] Time cost=0.061
2020-06-09 14:59:17,710 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:17,729 [INFO]  Epoch[5] Validation-cross-entropy=10.246600
2020-06-09 14:59:17,734 [INFO]  Epoch[5] Validation-RH-accuracy=0.000000
2020-06-09 14:59:17,787 [INFO]  Epoch[6] Batch [0-2]	Speed: 987.37 samples/sec	cross-entropy=10.038900	RH-accuracy=0.000000
2020-06-09 14:59:17,793 [INFO]  Epoch[6] Train-cross-entropy=10.038900
2020-06-09 14:59:17,797 [INFO]  Epoch[6] Train-RH-accuracy=0.000000
2020-06-09 14:59:17,802 [INFO]  Epoch[6] Time cost=0.064
2020-06-09 14:59:17,809 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:17,828 [INFO]  Epoch[6] Validation-cross-entropy=10.305990
2020-06-09 14:59:17,833 [INFO]  Epoch[6] Validation-RH-accuracy=0.000000
2020-06-09 14:59:17,885 [INFO]  Epoch[7] Batch [0-2]	Speed: 1021.23 samples/sec	cross-entropy=9.978871	RH-accuracy=0.000000
2020-06-09 14:59:17,891 [INFO]  Epoch[7] Train-cross-entropy=9.978871
2020-06-09 14:59:17,896 [INFO]  Epoch[7] Train-RH-accuracy=0.000000
2020-06-09 14:59:17,901 [INFO]  Epoch[7] Time cost=0.064
2020-06-09 14:59:17,909 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:59:17,930 [INFO]  Epoch[7] Validation-cross-entropy=10.416344
2020-06-09 14:59:17,934 [INFO]  Epoch[7] Validation-RH-accuracy=0.000000
2020-06-09 14:59:17,987 [INFO]  Epoch[8] Batch [0-2]	Speed: 1010.77 samples/sec	cross-entropy=9.920569	RH-accuracy=0.000000
2020-06-09 14:59:17,992 [INFO]  Epoch[8] Train-cross-entropy=9.920569
2020-06-09 14:59:17,997 [INFO]  Epoch[8] Train-RH-accuracy=0.000000
2020-06-09 14:59:18,002 [INFO]  Epoch[8] Time cost=0.063
2020-06-09 14:59:18,008 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-09 14:59:18,027 [INFO]  Epoch[8] Validation-cross-entropy=10.531380
2020-06-09 14:59:18,032 [INFO]  Epoch[8] Validation-RH-accuracy=0.000000
2020-06-09 14:59:18,085 [INFO]  Epoch[9] Batch [0-2]	Speed: 1001.91 samples/sec	cross-entropy=9.897053	RH-accuracy=0.000000
2020-06-09 14:59:18,091 [INFO]  Epoch[9] Train-cross-entropy=9.897053
2020-06-09 14:59:18,097 [INFO]  Epoch[9] Train-RH-accuracy=0.000000
2020-06-09 14:59:18,103 [INFO]  Epoch[9] Time cost=0.066
2020-06-09 14:59:18,112 [INFO]  Saved checkpoint to "datawig_imputation/model-0009.params"
2020-06-09 14:59:18,137 [INFO]  No improvement detected for 5 epochs compared to 10.282410621643066 last error obtained: 10.603793144226074, stopping here
2020-06-09 14:59:18,141 [INFO]
========== done (0.9964926242828369 s) fit model

20 rows have been imputed

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
2020-06-09 14:59:18,494 [INFO]
========== start: fit model
2020-06-09 14:59:18,497 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:18,554 [INFO]  Epoch[0] Batch [0-2]	Speed: 1025.42 samples/sec	cross-entropy=13.014942	RH-accuracy=0.000000
2020-06-09 14:59:18,558 [INFO]  Epoch[0] Train-cross-entropy=13.014942
2020-06-09 14:59:18,562 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:18,566 [INFO]  Epoch[0] Time cost=0.063
2020-06-09 14:59:18,573 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:18,591 [INFO]  Epoch[0] Validation-cross-entropy=2.382299
2020-06-09 14:59:18,596 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:18,648 [INFO]  Epoch[1] Batch [0-2]	Speed: 998.60 samples/sec	cross-entropy=10.839032	RH-accuracy=0.000000
2020-06-09 14:59:18,653 [INFO]  Epoch[1] Train-cross-entropy=10.839032
2020-06-09 14:59:18,658 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:18,662 [INFO]  Epoch[1] Time cost=0.063
2020-06-09 14:59:18,669 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:18,689 [INFO]  Epoch[1] Validation-cross-entropy=4.286576
2020-06-09 14:59:18,694 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:18,748 [INFO]  Epoch[2] Batch [0-2]	Speed: 996.39 samples/sec	cross-entropy=10.952905	RH-accuracy=0.000000
2020-06-09 14:59:18,754 [INFO]  Epoch[2] Train-cross-entropy=10.952905
2020-06-09 14:59:18,758 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:18,763 [INFO]  Epoch[2] Time cost=0.064
2020-06-09 14:59:18,770 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:18,789 [INFO]  Epoch[2] Validation-cross-entropy=4.547948
2020-06-09 14:59:18,794 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:18,845 [INFO]  Epoch[3] Batch [0-2]	Speed: 1023.27 samples/sec	cross-entropy=10.510108	RH-accuracy=0.000000
2020-06-09 14:59:18,851 [INFO]  Epoch[3] Train-cross-entropy=10.510108
2020-06-09 14:59:18,855 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:18,859 [INFO]  Epoch[3] Time cost=0.061
2020-06-09 14:59:18,866 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:18,886 [INFO]  Epoch[3] Validation-cross-entropy=3.397942
2020-06-09 14:59:18,891 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:18,943 [INFO]  Epoch[4] Batch [0-2]	Speed: 1006.55 samples/sec	cross-entropy=10.027947	RH-accuracy=0.000000
2020-06-09 14:59:18,951 [INFO]  Epoch[4] Train-cross-entropy=10.027947
2020-06-09 14:59:18,955 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:18,960 [INFO]  Epoch[4] Time cost=0.065
2020-06-09 14:59:18,967 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:18,986 [INFO]  Epoch[4] Validation-cross-entropy=2.561628
2020-06-09 14:59:18,992 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:19,048 [INFO]  Epoch[5] Batch [0-2]	Speed: 965.62 samples/sec	cross-entropy=9.928089	RH-accuracy=0.000000
2020-06-09 14:59:19,053 [INFO]  Epoch[5] Train-cross-entropy=9.928089
2020-06-09 14:59:19,058 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:19,062 [INFO]  Epoch[5] Time cost=0.065
2020-06-09 14:59:19,069 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:19,087 [INFO]  Epoch[5] Validation-cross-entropy=2.316165
2020-06-09 14:59:19,092 [INFO]  Epoch[5] Validation-RH-accuracy=0.000000
2020-06-09 14:59:19,148 [INFO]  Epoch[6] Batch [0-2]	Speed: 888.56 samples/sec	cross-entropy=9.959407	RH-accuracy=0.000000
2020-06-09 14:59:19,152 [INFO]  Epoch[6] Train-cross-entropy=9.959407
2020-06-09 14:59:19,157 [INFO]  Epoch[6] Train-RH-accuracy=0.000000
2020-06-09 14:59:19,161 [INFO]  Epoch[6] Time cost=0.065
2020-06-09 14:59:19,168 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:19,188 [INFO]  Epoch[6] Validation-cross-entropy=2.271633
2020-06-09 14:59:19,192 [INFO]  Epoch[6] Validation-RH-accuracy=0.000000
2020-06-09 14:59:19,245 [INFO]  Epoch[7] Batch [0-2]	Speed: 1010.01 samples/sec	cross-entropy=9.880025	RH-accuracy=0.000000
2020-06-09 14:59:19,250 [INFO]  Epoch[7] Train-cross-entropy=9.880025
2020-06-09 14:59:19,256 [INFO]  Epoch[7] Train-RH-accuracy=0.000000
2020-06-09 14:59:19,262 [INFO]  Epoch[7] Time cost=0.065
2020-06-09 14:59:19,271 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:59:19,292 [INFO]  Epoch[7] Validation-cross-entropy=2.298237
2020-06-09 14:59:19,299 [INFO]  Epoch[7] Validation-RH-accuracy=0.000000
2020-06-09 14:59:19,353 [INFO]  Epoch[8] Batch [0-2]	Speed: 998.19 samples/sec	cross-entropy=9.753975	RH-accuracy=0.000000
2020-06-09 14:59:19,358 [INFO]  Epoch[8] Train-cross-entropy=9.753975
2020-06-09 14:59:19,363 [INFO]  Epoch[8] Train-RH-accuracy=0.000000
2020-06-09 14:59:19,367 [INFO]  Epoch[8] Time cost=0.062
2020-06-09 14:59:19,373 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-09 14:59:19,392 [INFO]  Epoch[8] Validation-cross-entropy=2.488055
2020-06-09 14:59:19,396 [INFO]  Epoch[8] Validation-RH-accuracy=0.000000
2020-06-09 14:59:19,447 [INFO]  Epoch[9] Batch [0-2]	Speed: 1019.12 samples/sec	cross-entropy=9.703452	RH-accuracy=0.000000
2020-06-09 14:59:19,453 [INFO]  Epoch[9] Train-cross-entropy=9.703452
2020-06-09 14:59:19,458 [INFO]  Epoch[9] Train-RH-accuracy=0.000000
2020-06-09 14:59:19,463 [INFO]  Epoch[9] Time cost=0.063
2020-06-09 14:59:19,469 [INFO]  Saved checkpoint to "datawig_imputation/model-0009.params"
2020-06-09 14:59:19,490 [INFO]  Epoch[9] Validation-cross-entropy=2.759079
2020-06-09 14:59:19,495 [INFO]  Epoch[9] Validation-RH-accuracy=0.000000
2020-06-09 14:59:19,548 [INFO]  Epoch[10] Batch [0-2]	Speed: 1002.69 samples/sec	cross-entropy=9.706509	RH-accuracy=0.000000
2020-06-09 14:59:19,553 [INFO]  Epoch[10] Train-cross-entropy=9.706509
2020-06-09 14:59:19,558 [INFO]  Epoch[10] Train-RH-accuracy=0.000000
2020-06-09 14:59:19,563 [INFO]  Epoch[10] Time cost=0.063
2020-06-09 14:59:19,570 [INFO]  Saved checkpoint to "datawig_imputation/model-0010.params"
2020-06-09 14:59:19,590 [INFO]  Epoch[10] Validation-cross-entropy=2.877927
2020-06-09 14:59:19,595 [INFO]  Epoch[10] Validation-RH-accuracy=0.000000
2020-06-09 14:59:19,649 [INFO]  Epoch[11] Batch [0-2]	Speed: 1003.02 samples/sec	cross-entropy=9.687738	RH-accuracy=0.000000
2020-06-09 14:59:19,655 [INFO]  Epoch[11] Train-cross-entropy=9.687738
2020-06-09 14:59:19,660 [INFO]  Epoch[11] Train-RH-accuracy=0.000000
2020-06-09 14:59:19,664 [INFO]  Epoch[11] Time cost=0.064
2020-06-09 14:59:19,671 [INFO]  Saved checkpoint to "datawig_imputation/model-0011.params"
2020-06-09 14:59:19,691 [INFO]  No improvement detected for 5 epochs compared to 2.2716331481933594 last error obtained: 2.7723052501678467, stopping here
2020-06-09 14:59:19,695 [INFO]
========== done (1.2015671730041504 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

13 rows have been imputed

2020-06-09 14:59:19,984 [INFO]
========== start: fit model
2020-06-09 14:59:19,989 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:20,043 [INFO]  Epoch[0] Batch [0-2]	Speed: 1013.94 samples/sec	cross-entropy=14.809547	RH-accuracy=0.000000
2020-06-09 14:59:20,048 [INFO]  Epoch[0] Train-cross-entropy=14.809547
2020-06-09 14:59:20,052 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:20,056 [INFO]  Epoch[0] Time cost=0.062
2020-06-09 14:59:20,062 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:20,081 [INFO]  Epoch[0] Validation-cross-entropy=0.827293
2020-06-09 14:59:20,084 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:20,140 [INFO]  Epoch[1] Batch [0-2]	Speed: 922.03 samples/sec	cross-entropy=11.347820	RH-accuracy=0.000000
2020-06-09 14:59:20,144 [INFO]  Epoch[1] Train-cross-entropy=11.347820
2020-06-09 14:59:20,153 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:20,158 [INFO]  Epoch[1] Time cost=0.069
2020-06-09 14:59:20,165 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:20,185 [INFO]  Epoch[1] Validation-cross-entropy=1.390494
2020-06-09 14:59:20,190 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:20,244 [INFO]  Epoch[2] Batch [0-2]	Speed: 993.43 samples/sec	cross-entropy=11.150044	RH-accuracy=0.000000
2020-06-09 14:59:20,249 [INFO]  Epoch[2] Train-cross-entropy=11.150044
2020-06-09 14:59:20,253 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:20,257 [INFO]  Epoch[2] Time cost=0.063
2020-06-09 14:59:20,264 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:20,282 [INFO]  Epoch[2] Validation-cross-entropy=1.827638
2020-06-09 14:59:20,287 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:20,339 [INFO]  Epoch[3] Batch [0-2]	Speed: 1011.85 samples/sec	cross-entropy=11.214705	RH-accuracy=0.000000
2020-06-09 14:59:20,344 [INFO]  Epoch[3] Train-cross-entropy=11.214705
2020-06-09 14:59:20,348 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:20,352 [INFO]  Epoch[3] Time cost=0.061
2020-06-09 14:59:20,358 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:20,378 [INFO]  Epoch[3] Validation-cross-entropy=1.609191
2020-06-09 14:59:20,382 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:20,434 [INFO]  Epoch[4] Batch [0-2]	Speed: 1005.00 samples/sec	cross-entropy=10.909155	RH-accuracy=0.000000
2020-06-09 14:59:20,439 [INFO]  Epoch[4] Train-cross-entropy=10.909155
2020-06-09 14:59:20,443 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:20,447 [INFO]  Epoch[4] Time cost=0.061
2020-06-09 14:59:20,453 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:20,472 [INFO]  Epoch[4] Validation-cross-entropy=1.303718
2020-06-09 14:59:20,476 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:20,529 [INFO]  Epoch[5] Batch [0-2]	Speed: 987.57 samples/sec	cross-entropy=10.533904	RH-accuracy=0.000000
2020-06-09 14:59:20,534 [INFO]  Epoch[5] Train-cross-entropy=10.533904
2020-06-09 14:59:20,538 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:20,542 [INFO]  Epoch[5] Time cost=0.062
2020-06-09 14:59:20,549 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:20,567 [INFO]  No improvement detected for 5 epochs compared to 0.8272928595542908 last error obtained: 1.0287785530090332, stopping here
2020-06-09 14:59:20,571 [INFO]
========== done (0.588038444519043 s) fit model

19 rows have been imputed

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
2020-06-09 14:59:20,934 [INFO]
========== start: fit model
2020-06-09 14:59:20,941 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:20,995 [INFO]  Epoch[0] Batch [0-2]	Speed: 1021.30 samples/sec	cross-entropy=16.182154	RH-accuracy=0.000000
2020-06-09 14:59:21,000 [INFO]  Epoch[0] Train-cross-entropy=16.182154
2020-06-09 14:59:21,004 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:21,008 [INFO]  Epoch[0] Time cost=0.062
2020-06-09 14:59:21,014 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:21,032 [INFO]  Epoch[0] Validation-cross-entropy=11.823037
2020-06-09 14:59:21,037 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:21,089 [INFO]  Epoch[1] Batch [0-2]	Speed: 1006.88 samples/sec	cross-entropy=14.363991	RH-accuracy=0.000000
2020-06-09 14:59:21,094 [INFO]  Epoch[1] Train-cross-entropy=14.363991
2020-06-09 14:59:21,099 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:21,104 [INFO]  Epoch[1] Time cost=0.063
2020-06-09 14:59:21,111 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:21,131 [INFO]  Epoch[1] Validation-cross-entropy=11.736420
2020-06-09 14:59:21,136 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:21,195 [INFO]  Epoch[2] Batch [0-2]	Speed: 988.03 samples/sec	cross-entropy=13.969060	RH-accuracy=0.000000
2020-06-09 14:59:21,200 [INFO]  Epoch[2] Train-cross-entropy=13.969060
2020-06-09 14:59:21,205 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:21,210 [INFO]  Epoch[2] Time cost=0.070
2020-06-09 14:59:21,217 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:21,238 [INFO]  Epoch[2] Validation-cross-entropy=11.976752
2020-06-09 14:59:21,242 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:21,294 [INFO]  Epoch[3] Batch [0-2]	Speed: 1018.06 samples/sec	cross-entropy=13.787292	RH-accuracy=0.000000
2020-06-09 14:59:21,299 [INFO]  Epoch[3] Train-cross-entropy=13.787292
2020-06-09 14:59:21,303 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:21,308 [INFO]  Epoch[3] Time cost=0.062
2020-06-09 14:59:21,314 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:21,333 [INFO]  Epoch[3] Validation-cross-entropy=11.963013
2020-06-09 14:59:21,338 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:21,391 [INFO]  Epoch[4] Batch [0-2]	Speed: 1003.90 samples/sec	cross-entropy=13.455637	RH-accuracy=0.000000
2020-06-09 14:59:21,397 [INFO]  Epoch[4] Train-cross-entropy=13.455637
2020-06-09 14:59:21,400 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:21,405 [INFO]  Epoch[4] Time cost=0.062
2020-06-09 14:59:21,412 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:21,431 [INFO]  Epoch[4] Validation-cross-entropy=11.828711
2020-06-09 14:59:21,436 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:21,488 [INFO]  Epoch[5] Batch [0-2]	Speed: 1006.61 samples/sec	cross-entropy=13.149229	RH-accuracy=0.000000
2020-06-09 14:59:21,493 [INFO]  Epoch[5] Train-cross-entropy=13.149229
2020-06-09 14:59:21,497 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:21,501 [INFO]  Epoch[5] Time cost=0.061
2020-06-09 14:59:21,507 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:21,526 [INFO]  Epoch[5] Validation-cross-entropy=11.741854
2020-06-09 14:59:21,530 [INFO]  Epoch[5] Validation-RH-accuracy=0.000000
2020-06-09 14:59:21,582 [INFO]  Epoch[6] Batch [0-2]	Speed: 1020.35 samples/sec	cross-entropy=12.974728	RH-accuracy=0.000000
2020-06-09 14:59:21,586 [INFO]  Epoch[6] Train-cross-entropy=12.974728
2020-06-09 14:59:21,591 [INFO]  Epoch[6] Train-RH-accuracy=0.000000
2020-06-09 14:59:21,594 [INFO]  Epoch[6] Time cost=0.061
2020-06-09 14:59:21,600 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:21,619 [INFO]  Epoch[6] Validation-cross-entropy=11.702255
2020-06-09 14:59:21,623 [INFO]  Epoch[6] Validation-RH-accuracy=0.000000
2020-06-09 14:59:21,675 [INFO]  Epoch[7] Batch [0-2]	Speed: 996.38 samples/sec	cross-entropy=12.880846	RH-accuracy=0.000000
2020-06-09 14:59:21,680 [INFO]  Epoch[7] Train-cross-entropy=12.880846
2020-06-09 14:59:21,684 [INFO]  Epoch[7] Train-RH-accuracy=0.000000
2020-06-09 14:59:21,688 [INFO]  Epoch[7] Time cost=0.061
2020-06-09 14:59:21,697 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:59:21,716 [INFO]  Epoch[7] Validation-cross-entropy=11.652676
2020-06-09 14:59:21,720 [INFO]  Epoch[7] Validation-RH-accuracy=0.000000
2020-06-09 14:59:21,773 [INFO]  Epoch[8] Batch [0-2]	Speed: 999.10 samples/sec	cross-entropy=12.807820	RH-accuracy=0.000000
2020-06-09 14:59:21,778 [INFO]  Epoch[8] Train-cross-entropy=12.807820
2020-06-09 14:59:21,782 [INFO]  Epoch[8] Train-RH-accuracy=0.000000
2020-06-09 14:59:21,786 [INFO]  Epoch[8] Time cost=0.062
2020-06-09 14:59:21,792 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-09 14:59:21,811 [INFO]  Epoch[8] Validation-cross-entropy=11.573067
2020-06-09 14:59:21,815 [INFO]  Epoch[8] Validation-RH-accuracy=0.000000
2020-06-09 14:59:21,867 [INFO]  Epoch[9] Batch [0-2]	Speed: 1025.12 samples/sec	cross-entropy=12.748888	RH-accuracy=0.000000
2020-06-09 14:59:21,872 [INFO]  Epoch[9] Train-cross-entropy=12.748888
2020-06-09 14:59:21,876 [INFO]  Epoch[9] Train-RH-accuracy=0.000000
2020-06-09 14:59:21,881 [INFO]  Epoch[9] Time cost=0.061
2020-06-09 14:59:21,889 [INFO]  Saved checkpoint to "datawig_imputation/model-0009.params"
2020-06-09 14:59:21,907 [INFO]  Epoch[9] Validation-cross-entropy=11.486305
2020-06-09 14:59:21,911 [INFO]  Epoch[9] Validation-RH-accuracy=0.000000
2020-06-09 14:59:21,962 [INFO]  Epoch[10] Batch [0-2]	Speed: 1017.41 samples/sec	cross-entropy=12.700296	RH-accuracy=0.000000
2020-06-09 14:59:21,967 [INFO]  Epoch[10] Train-cross-entropy=12.700296
2020-06-09 14:59:21,971 [INFO]  Epoch[10] Train-RH-accuracy=0.000000
2020-06-09 14:59:21,975 [INFO]  Epoch[10] Time cost=0.061
2020-06-09 14:59:21,982 [INFO]  Saved checkpoint to "datawig_imputation/model-0010.params"
2020-06-09 14:59:22,001 [INFO]  Epoch[10] Validation-cross-entropy=11.413923
2020-06-09 14:59:22,005 [INFO]  Epoch[10] Validation-RH-accuracy=0.000000
2020-06-09 14:59:22,058 [INFO]  Epoch[11] Batch [0-2]	Speed: 996.21 samples/sec	cross-entropy=12.663396	RH-accuracy=0.000000
2020-06-09 14:59:22,063 [INFO]  Epoch[11] Train-cross-entropy=12.663396
2020-06-09 14:59:22,067 [INFO]  Epoch[11] Train-RH-accuracy=0.000000
2020-06-09 14:59:22,071 [INFO]  Epoch[11] Time cost=0.062
2020-06-09 14:59:22,077 [INFO]  Saved checkpoint to "datawig_imputation/model-0011.params"
2020-06-09 14:59:22,096 [INFO]  Epoch[11] Validation-cross-entropy=11.348181
2020-06-09 14:59:22,100 [INFO]  Epoch[11] Validation-RH-accuracy=0.000000
2020-06-09 14:59:22,153 [INFO]  Epoch[12] Batch [0-2]	Speed: 1014.86 samples/sec	cross-entropy=12.636652	RH-accuracy=0.000000
2020-06-09 14:59:22,158 [INFO]  Epoch[12] Train-cross-entropy=12.636652
2020-06-09 14:59:22,163 [INFO]  Epoch[12] Train-RH-accuracy=0.000000
2020-06-09 14:59:22,173 [INFO]  Epoch[12] Time cost=0.069
2020-06-09 14:59:22,180 [INFO]  Saved checkpoint to "datawig_imputation/model-0012.params"
2020-06-09 14:59:22,200 [INFO]  Epoch[12] Validation-cross-entropy=11.269387
2020-06-09 14:59:22,204 [INFO]  Epoch[12] Validation-RH-accuracy=0.000000
2020-06-09 14:59:22,260 [INFO]  Epoch[13] Batch [0-2]	Speed: 1011.74 samples/sec	cross-entropy=12.608385	RH-accuracy=0.000000
2020-06-09 14:59:22,265 [INFO]  Epoch[13] Train-cross-entropy=12.608385
2020-06-09 14:59:22,270 [INFO]  Epoch[13] Train-RH-accuracy=0.000000
2020-06-09 14:59:22,274 [INFO]  Epoch[13] Time cost=0.066
2020-06-09 14:59:22,281 [INFO]  Saved checkpoint to "datawig_imputation/model-0013.params"
2020-06-09 14:59:22,301 [INFO]  Epoch[13] Validation-cross-entropy=11.174472
2020-06-09 14:59:22,306 [INFO]  Epoch[13] Validation-RH-accuracy=0.000000
2020-06-09 14:59:22,360 [INFO]  Epoch[14] Batch [0-2]	Speed: 989.72 samples/sec	cross-entropy=12.571878	RH-accuracy=0.000000
2020-06-09 14:59:22,366 [INFO]  Epoch[14] Train-cross-entropy=12.571878
2020-06-09 14:59:22,370 [INFO]  Epoch[14] Train-RH-accuracy=0.000000
2020-06-09 14:59:22,375 [INFO]  Epoch[14] Time cost=0.064
2020-06-09 14:59:22,382 [INFO]  Saved checkpoint to "datawig_imputation/model-0014.params"
2020-06-09 14:59:22,401 [INFO]  Epoch[14] Validation-cross-entropy=11.076468
2020-06-09 14:59:22,406 [INFO]  Epoch[14] Validation-RH-accuracy=0.000000
2020-06-09 14:59:22,459 [INFO]  Epoch[15] Batch [0-2]	Speed: 1012.57 samples/sec	cross-entropy=12.534646	RH-accuracy=0.000000
2020-06-09 14:59:22,464 [INFO]  Epoch[15] Train-cross-entropy=12.534646
2020-06-09 14:59:22,469 [INFO]  Epoch[15] Train-RH-accuracy=0.000000
2020-06-09 14:59:22,474 [INFO]  Epoch[15] Time cost=0.063
2020-06-09 14:59:22,480 [INFO]  Saved checkpoint to "datawig_imputation/model-0015.params"
2020-06-09 14:59:22,499 [INFO]  Epoch[15] Validation-cross-entropy=10.989605
2020-06-09 14:59:22,504 [INFO]  Epoch[15] Validation-RH-accuracy=0.000000
2020-06-09 14:59:22,556 [INFO]  Epoch[16] Batch [0-2]	Speed: 1027.10 samples/sec	cross-entropy=12.502342	RH-accuracy=0.000000
2020-06-09 14:59:22,561 [INFO]  Epoch[16] Train-cross-entropy=12.502342
2020-06-09 14:59:22,566 [INFO]  Epoch[16] Train-RH-accuracy=0.000000
2020-06-09 14:59:22,571 [INFO]  Epoch[16] Time cost=0.063
2020-06-09 14:59:22,578 [INFO]  Saved checkpoint to "datawig_imputation/model-0016.params"
2020-06-09 14:59:22,597 [INFO]  Epoch[16] Validation-cross-entropy=10.919458
2020-06-09 14:59:22,603 [INFO]  Epoch[16] Validation-RH-accuracy=0.000000
2020-06-09 14:59:22,656 [INFO]  Epoch[17] Batch [0-2]	Speed: 989.34 samples/sec	cross-entropy=12.473201	RH-accuracy=0.000000
2020-06-09 14:59:22,662 [INFO]  Epoch[17] Train-cross-entropy=12.473201
2020-06-09 14:59:22,667 [INFO]  Epoch[17] Train-RH-accuracy=0.000000
2020-06-09 14:59:22,672 [INFO]  Epoch[17] Time cost=0.065
2020-06-09 14:59:22,680 [INFO]  Saved checkpoint to "datawig_imputation/model-0017.params"
2020-06-09 14:59:22,699 [INFO]  Epoch[17] Validation-cross-entropy=10.865148
2020-06-09 14:59:22,703 [INFO]  Epoch[17] Validation-RH-accuracy=0.000000
2020-06-09 14:59:22,756 [INFO]  Epoch[18] Batch [0-2]	Speed: 1014.32 samples/sec	cross-entropy=12.445001	RH-accuracy=0.000000
2020-06-09 14:59:22,761 [INFO]  Epoch[18] Train-cross-entropy=12.445001
2020-06-09 14:59:22,766 [INFO]  Epoch[18] Train-RH-accuracy=0.000000
2020-06-09 14:59:22,770 [INFO]  Epoch[18] Time cost=0.062
2020-06-09 14:59:22,778 [INFO]  Saved checkpoint to "datawig_imputation/model-0018.params"
2020-06-09 14:59:22,796 [INFO]  Epoch[18] Validation-cross-entropy=10.823713
2020-06-09 14:59:22,800 [INFO]  Epoch[18] Validation-RH-accuracy=0.000000
2020-06-09 14:59:22,852 [INFO]  Epoch[19] Batch [0-2]	Speed: 1026.47 samples/sec	cross-entropy=12.417236	RH-accuracy=0.000000
2020-06-09 14:59:22,857 [INFO]  Epoch[19] Train-cross-entropy=12.417236
2020-06-09 14:59:22,862 [INFO]  Epoch[19] Train-RH-accuracy=0.000000
2020-06-09 14:59:22,866 [INFO]  Epoch[19] Time cost=0.062
2020-06-09 14:59:22,874 [INFO]  Saved checkpoint to "datawig_imputation/model-0019.params"
2020-06-09 14:59:22,894 [INFO]  Epoch[19] Validation-cross-entropy=10.792938
2020-06-09 14:59:22,899 [INFO]  Epoch[19] Validation-RH-accuracy=0.000000
2020-06-09 14:59:22,953 [INFO]  Epoch[20] Batch [0-2]	Speed: 998.89 samples/sec	cross-entropy=12.390937	RH-accuracy=0.000000
2020-06-09 14:59:22,958 [INFO]  Epoch[20] Train-cross-entropy=12.390937
2020-06-09 14:59:22,963 [INFO]  Epoch[20] Train-RH-accuracy=0.000000
2020-06-09 14:59:22,968 [INFO]  Epoch[20] Time cost=0.064
2020-06-09 14:59:22,975 [INFO]  Saved checkpoint to "datawig_imputation/model-0020.params"
2020-06-09 14:59:22,995 [INFO]  Epoch[20] Validation-cross-entropy=10.769363
2020-06-09 14:59:23,000 [INFO]  Epoch[20] Validation-RH-accuracy=0.000000
2020-06-09 14:59:23,053 [INFO]  Epoch[21] Batch [0-2]	Speed: 1011.09 samples/sec	cross-entropy=12.367796	RH-accuracy=0.000000
2020-06-09 14:59:23,058 [INFO]  Epoch[21] Train-cross-entropy=12.367796
2020-06-09 14:59:23,062 [INFO]  Epoch[21] Train-RH-accuracy=0.000000
2020-06-09 14:59:23,067 [INFO]  Epoch[21] Time cost=0.062
2020-06-09 14:59:23,073 [INFO]  Saved checkpoint to "datawig_imputation/model-0021.params"
2020-06-09 14:59:23,092 [INFO]  Epoch[21] Validation-cross-entropy=10.752184
2020-06-09 14:59:23,096 [INFO]  Epoch[21] Validation-RH-accuracy=0.000000
2020-06-09 14:59:23,148 [INFO]  Epoch[22] Batch [0-2]	Speed: 1018.19 samples/sec	cross-entropy=12.347224	RH-accuracy=0.000000
2020-06-09 14:59:23,154 [INFO]  Epoch[22] Train-cross-entropy=12.347224
2020-06-09 14:59:23,160 [INFO]  Epoch[22] Train-RH-accuracy=0.000000
2020-06-09 14:59:23,165 [INFO]  Epoch[22] Time cost=0.065
2020-06-09 14:59:23,174 [INFO]  Saved checkpoint to "datawig_imputation/model-0022.params"
2020-06-09 14:59:23,195 [INFO]  Epoch[22] Validation-cross-entropy=10.737627
2020-06-09 14:59:23,200 [INFO]  Epoch[22] Validation-RH-accuracy=0.000000
2020-06-09 14:59:23,256 [INFO]  Epoch[23] Batch [0-2]	Speed: 991.44 samples/sec	cross-entropy=12.327136	RH-accuracy=0.000000
2020-06-09 14:59:23,260 [INFO]  Epoch[23] Train-cross-entropy=12.327136
2020-06-09 14:59:23,265 [INFO]  Epoch[23] Train-RH-accuracy=0.000000
2020-06-09 14:59:23,269 [INFO]  Epoch[23] Time cost=0.065
2020-06-09 14:59:23,276 [INFO]  Saved checkpoint to "datawig_imputation/model-0023.params"
2020-06-09 14:59:23,295 [INFO]  Epoch[23] Validation-cross-entropy=10.724464
2020-06-09 14:59:23,298 [INFO]  Epoch[23] Validation-RH-accuracy=0.000000
2020-06-09 14:59:23,352 [INFO]  Epoch[24] Batch [0-2]	Speed: 997.72 samples/sec	cross-entropy=12.306456	RH-accuracy=0.000000
2020-06-09 14:59:23,356 [INFO]  Epoch[24] Train-cross-entropy=12.306456
2020-06-09 14:59:23,361 [INFO]  Epoch[24] Train-RH-accuracy=0.000000
2020-06-09 14:59:23,365 [INFO]  Epoch[24] Time cost=0.062
2020-06-09 14:59:23,373 [INFO]  Saved checkpoint to "datawig_imputation/model-0024.params"
2020-06-09 14:59:23,392 [INFO]  Epoch[24] Validation-cross-entropy=10.712212
2020-06-09 14:59:23,397 [INFO]  Epoch[24] Validation-RH-accuracy=0.000000
2020-06-09 14:59:23,449 [INFO]  Epoch[25] Batch [0-2]	Speed: 1014.20 samples/sec	cross-entropy=12.285729	RH-accuracy=0.000000
2020-06-09 14:59:23,455 [INFO]  Epoch[25] Train-cross-entropy=12.285729
2020-06-09 14:59:23,461 [INFO]  Epoch[25] Train-RH-accuracy=0.000000
2020-06-09 14:59:23,467 [INFO]  Epoch[25] Time cost=0.065
2020-06-09 14:59:23,475 [INFO]  Saved checkpoint to "datawig_imputation/model-0025.params"
2020-06-09 14:59:23,495 [INFO]  Epoch[25] Validation-cross-entropy=10.698883
2020-06-09 14:59:23,501 [INFO]  Epoch[25] Validation-RH-accuracy=0.000000
2020-06-09 14:59:23,556 [INFO]  Epoch[26] Batch [0-2]	Speed: 991.90 samples/sec	cross-entropy=12.265888	RH-accuracy=0.000000
2020-06-09 14:59:23,562 [INFO]  Epoch[26] Train-cross-entropy=12.265888
2020-06-09 14:59:23,567 [INFO]  Epoch[26] Train-RH-accuracy=0.000000
2020-06-09 14:59:23,571 [INFO]  Epoch[26] Time cost=0.065
2020-06-09 14:59:23,578 [INFO]  Saved checkpoint to "datawig_imputation/model-0026.params"
2020-06-09 14:59:23,598 [INFO]  Epoch[26] Validation-cross-entropy=10.685200
2020-06-09 14:59:23,603 [INFO]  Epoch[26] Validation-RH-accuracy=0.000000
2020-06-09 14:59:23,655 [INFO]  Epoch[27] Batch [0-2]	Speed: 1007.63 samples/sec	cross-entropy=12.247491	RH-accuracy=0.000000
2020-06-09 14:59:23,661 [INFO]  Epoch[27] Train-cross-entropy=12.247491
2020-06-09 14:59:23,665 [INFO]  Epoch[27] Train-RH-accuracy=0.000000
2020-06-09 14:59:23,670 [INFO]  Epoch[27] Time cost=0.063
2020-06-09 14:59:23,677 [INFO]  Saved checkpoint to "datawig_imputation/model-0027.params"
2020-06-09 14:59:23,695 [INFO]  Epoch[27] Validation-cross-entropy=10.669774
2020-06-09 14:59:23,699 [INFO]  Epoch[27] Validation-RH-accuracy=0.000000
2020-06-09 14:59:23,751 [INFO]  Epoch[28] Batch [0-2]	Speed: 1021.07 samples/sec	cross-entropy=12.230467	RH-accuracy=0.000000
2020-06-09 14:59:23,756 [INFO]  Epoch[28] Train-cross-entropy=12.230467
2020-06-09 14:59:23,761 [INFO]  Epoch[28] Train-RH-accuracy=0.000000
2020-06-09 14:59:23,766 [INFO]  Epoch[28] Time cost=0.062
2020-06-09 14:59:23,773 [INFO]  Saved checkpoint to "datawig_imputation/model-0028.params"
2020-06-09 14:59:23,794 [INFO]  Epoch[28] Validation-cross-entropy=10.651091
2020-06-09 14:59:23,800 [INFO]  Epoch[28] Validation-RH-accuracy=0.000000
2020-06-09 14:59:23,858 [INFO]  Epoch[29] Batch [0-2]	Speed: 932.42 samples/sec	cross-entropy=12.213554	RH-accuracy=0.000000
2020-06-09 14:59:23,864 [INFO]  Epoch[29] Train-cross-entropy=12.213554
2020-06-09 14:59:23,869 [INFO]  Epoch[29] Train-RH-accuracy=0.000000
2020-06-09 14:59:23,873 [INFO]  Epoch[29] Time cost=0.069
2020-06-09 14:59:23,881 [INFO]  Saved checkpoint to "datawig_imputation/model-0029.params"
2020-06-09 14:59:23,899 [INFO]  Epoch[29] Validation-cross-entropy=10.630549
2020-06-09 14:59:23,903 [INFO]  Epoch[29] Validation-RH-accuracy=0.000000
2020-06-09 14:59:23,956 [INFO]  Epoch[30] Batch [0-2]	Speed: 1001.44 samples/sec	cross-entropy=12.197344	RH-accuracy=0.000000
2020-06-09 14:59:23,961 [INFO]  Epoch[30] Train-cross-entropy=12.197344
2020-06-09 14:59:23,965 [INFO]  Epoch[30] Train-RH-accuracy=0.000000
2020-06-09 14:59:23,969 [INFO]  Epoch[30] Time cost=0.061
2020-06-09 14:59:23,975 [INFO]  Saved checkpoint to "datawig_imputation/model-0030.params"
2020-06-09 14:59:23,994 [INFO]  Epoch[30] Validation-cross-entropy=10.610529
2020-06-09 14:59:23,998 [INFO]  Epoch[30] Validation-RH-accuracy=0.000000
2020-06-09 14:59:24,050 [INFO]  Epoch[31] Batch [0-2]	Speed: 1026.53 samples/sec	cross-entropy=12.181493	RH-accuracy=0.000000
2020-06-09 14:59:24,055 [INFO]  Epoch[31] Train-cross-entropy=12.181493
2020-06-09 14:59:24,061 [INFO]  Epoch[31] Train-RH-accuracy=0.000000
2020-06-09 14:59:24,065 [INFO]  Epoch[31] Time cost=0.063
2020-06-09 14:59:24,072 [INFO]  Saved checkpoint to "datawig_imputation/model-0031.params"
2020-06-09 14:59:24,091 [INFO]  Epoch[31] Validation-cross-entropy=10.588120
2020-06-09 14:59:24,096 [INFO]  Epoch[31] Validation-RH-accuracy=0.000000
2020-06-09 14:59:24,149 [INFO]  Epoch[32] Batch [0-2]	Speed: 1004.30 samples/sec	cross-entropy=12.167669	RH-accuracy=0.000000
2020-06-09 14:59:24,155 [INFO]  Epoch[32] Train-cross-entropy=12.167669
2020-06-09 14:59:24,160 [INFO]  Epoch[32] Train-RH-accuracy=0.000000
2020-06-09 14:59:24,165 [INFO]  Epoch[32] Time cost=0.065
2020-06-09 14:59:24,172 [INFO]  Saved checkpoint to "datawig_imputation/model-0032.params"
2020-06-09 14:59:24,197 [INFO]  Epoch[32] Validation-cross-entropy=10.562828
2020-06-09 14:59:24,202 [INFO]  Epoch[32] Validation-RH-accuracy=0.000000
2020-06-09 14:59:24,255 [INFO]  Epoch[33] Batch [0-2]	Speed: 1003.35 samples/sec	cross-entropy=12.154027	RH-accuracy=0.000000
2020-06-09 14:59:24,260 [INFO]  Epoch[33] Train-cross-entropy=12.154027
2020-06-09 14:59:24,265 [INFO]  Epoch[33] Train-RH-accuracy=0.000000
2020-06-09 14:59:24,270 [INFO]  Epoch[33] Time cost=0.063
2020-06-09 14:59:24,277 [INFO]  Saved checkpoint to "datawig_imputation/model-0033.params"
2020-06-09 14:59:24,295 [INFO]  Epoch[33] Validation-cross-entropy=10.539029
2020-06-09 14:59:24,300 [INFO]  Epoch[33] Validation-RH-accuracy=0.000000
2020-06-09 14:59:24,353 [INFO]  Epoch[34] Batch [0-2]	Speed: 1008.68 samples/sec	cross-entropy=12.141239	RH-accuracy=0.000000
2020-06-09 14:59:24,359 [INFO]  Epoch[34] Train-cross-entropy=12.141239
2020-06-09 14:59:24,366 [INFO]  Epoch[34] Train-RH-accuracy=0.000000

9 rows have been imputed

2020-06-09 14:59:33,217 [INFO]
========== start: fit model
2020-06-09 14:59:33,225 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:33,281 [INFO]  Epoch[0] Batch [0-2]	Speed: 988.81 samples/sec	cross-entropy=14.164877	RH-accuracy=0.000000
2020-06-09 14:59:33,288 [INFO]  Epoch[0] Train-cross-entropy=14.164877
2020-06-09 14:59:33,293 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:33,298 [INFO]  Epoch[0] Time cost=0.066
2020-06-09 14:59:33,310 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:33,330 [INFO]  Epoch[0] Validation-cross-entropy=13.939836
2020-06-09 14:59:33,335 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:33,388 [INFO]  Epoch[1] Batch [0-2]	Speed: 977.24 samples/sec	cross-entropy=12.347083	RH-accuracy=0.000000
2020-06-09 14:59:33,393 [INFO]  Epoch[1] Train-cross-entropy=12.347083
2020-06-09 14:59:33,397 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:33,401 [INFO]  Epoch[1] Time cost=0.062
2020-06-09 14:59:33,407 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:33,428 [INFO]  Epoch[1] Validation-cross-entropy=9.686850
2020-06-09 14:59:33,432 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:33,484 [INFO]  Epoch[2] Batch [0-2]	Speed: 1023.66 samples/sec	cross-entropy=11.963156	RH-accuracy=0.000000
2020-06-09 14:59:33,489 [INFO]  Epoch[2] Train-cross-entropy=11.963156
2020-06-09 14:59:33,493 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:33,497 [INFO]  Epoch[2] Time cost=0.061
2020-06-09 14:59:33,504 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:33,523 [INFO]  Epoch[2] Validation-cross-entropy=8.027698
2020-06-09 14:59:33,527 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:33,582 [INFO]  Epoch[3] Batch [0-2]	Speed: 993.98 samples/sec	cross-entropy=11.740370	RH-accuracy=0.000000
2020-06-09 14:59:33,588 [INFO]  Epoch[3] Train-cross-entropy=11.740370
2020-06-09 14:59:33,593 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:33,598 [INFO]  Epoch[3] Time cost=0.065
2020-06-09 14:59:33,606 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:33,626 [INFO]  Epoch[3] Validation-cross-entropy=7.694323
2020-06-09 14:59:33,630 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:33,690 [INFO]  Epoch[4] Batch [0-2]	Speed: 960.73 samples/sec	cross-entropy=11.572347	RH-accuracy=0.000000
2020-06-09 14:59:33,696 [INFO]  Epoch[4] Train-cross-entropy=11.572347
2020-06-09 14:59:33,701 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:33,707 [INFO]  Epoch[4] Time cost=0.068
2020-06-09 14:59:33,715 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:33,735 [INFO]  Epoch[4] Validation-cross-entropy=7.911392
2020-06-09 14:59:33,740 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:33,794 [INFO]  Epoch[5] Batch [0-2]	Speed: 1007.61 samples/sec	cross-entropy=11.474301	RH-accuracy=0.000000
2020-06-09 14:59:33,800 [INFO]  Epoch[5] Train-cross-entropy=11.474301
2020-06-09 14:59:33,806 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:33,813 [INFO]  Epoch[5] Time cost=0.067
2020-06-09 14:59:33,821 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:33,841 [INFO]  Epoch[5] Validation-cross-entropy=8.246421
2020-06-09 14:59:33,846 [INFO]  Epoch[5] Validation-RH-accuracy=0.000000
2020-06-09 14:59:33,900 [INFO]  Epoch[6] Batch [0-2]	Speed: 986.79 samples/sec	cross-entropy=11.405700	RH-accuracy=0.000000
2020-06-09 14:59:33,905 [INFO]  Epoch[6] Train-cross-entropy=11.405700
2020-06-09 14:59:33,910 [INFO]  Epoch[6] Train-RH-accuracy=0.000000
2020-06-09 14:59:33,915 [INFO]  Epoch[6] Time cost=0.065
2020-06-09 14:59:33,923 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:33,943 [INFO]  Epoch[6] Validation-cross-entropy=8.402230
2020-06-09 14:59:33,948 [INFO]  Epoch[6] Validation-RH-accuracy=0.000000
2020-06-09 14:59:34,002 [INFO]  Epoch[7] Batch [0-2]	Speed: 976.95 samples/sec	cross-entropy=11.343904	RH-accuracy=0.000000
2020-06-09 14:59:34,007 [INFO]  Epoch[7] Train-cross-entropy=11.343904
2020-06-09 14:59:34,013 [INFO]  Epoch[7] Train-RH-accuracy=0.000000
2020-06-09 14:59:34,017 [INFO]  Epoch[7] Time cost=0.065
2020-06-09 14:59:34,024 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:59:34,044 [INFO]  Epoch[7] Validation-cross-entropy=8.243455
2020-06-09 14:59:34,048 [INFO]  Epoch[7] Validation-RH-accuracy=0.000000
2020-06-09 14:59:34,105 [INFO]  Epoch[8] Batch [0-2]	Speed: 884.12 samples/sec	cross-entropy=11.278828	RH-accuracy=0.000000
2020-06-09 14:59:34,112 [INFO]  Epoch[8] Train-cross-entropy=11.278828
2020-06-09 14:59:34,120 [INFO]  Epoch[8] Train-RH-accuracy=0.000000
2020-06-09 14:59:34,126 [INFO]  Epoch[8] Time cost=0.074
2020-06-09 14:59:34,134 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-09 14:59:34,155 [INFO]  No improvement detected for 5 epochs compared to 7.6943230628967285 last error obtained: 7.832789421081543, stopping here
2020-06-09 14:59:34,161 [INFO]
========== done (0.943709135055542 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

10 rows have been imputed

2020-06-09 14:59:34,615 [INFO]
========== start: fit model
2020-06-09 14:59:34,621 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:34,676 [INFO]  Epoch[0] Batch [0-2]	Speed: 1009.01 samples/sec	cross-entropy=16.124899	RH-accuracy=0.000000
2020-06-09 14:59:34,699 [INFO]  Epoch[0] Train-cross-entropy=12.331328
2020-06-09 14:59:34,705 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:34,711 [INFO]  Epoch[0] Time cost=0.084
2020-06-09 14:59:34,719 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:34,739 [INFO]  Epoch[0] Validation-cross-entropy=42.095352
2020-06-09 14:59:34,745 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:34,799 [INFO]  Epoch[1] Batch [0-2]	Speed: 986.61 samples/sec	cross-entropy=14.267372	RH-accuracy=0.000000
2020-06-09 14:59:34,822 [INFO]  Epoch[1] Train-cross-entropy=10.706051
2020-06-09 14:59:34,826 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:34,832 [INFO]  Epoch[1] Time cost=0.081
2020-06-09 14:59:34,840 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:34,859 [INFO]  Epoch[1] Validation-cross-entropy=51.694199
2020-06-09 14:59:34,864 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:34,922 [INFO]  Epoch[2] Batch [0-2]	Speed: 894.16 samples/sec	cross-entropy=14.220845	RH-accuracy=0.000000
2020-06-09 14:59:34,944 [INFO]  Epoch[2] Train-cross-entropy=10.668929
2020-06-09 14:59:34,949 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:34,954 [INFO]  Epoch[2] Time cost=0.085
2020-06-09 14:59:34,962 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:34,980 [INFO]  Epoch[2] Validation-cross-entropy=58.132309
2020-06-09 14:59:34,985 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:35,039 [INFO]  Epoch[3] Batch [0-2]	Speed: 987.88 samples/sec	cross-entropy=14.038165	RH-accuracy=0.000000
2020-06-09 14:59:35,061 [INFO]  Epoch[3] Train-cross-entropy=10.647651
2020-06-09 14:59:35,066 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:35,071 [INFO]  Epoch[3] Time cost=0.081
2020-06-09 14:59:35,078 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:35,098 [INFO]  Epoch[3] Validation-cross-entropy=60.271744
2020-06-09 14:59:35,103 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:35,159 [INFO]  Epoch[4] Batch [0-2]	Speed: 958.72 samples/sec	cross-entropy=14.016897	RH-accuracy=0.000000
2020-06-09 14:59:35,181 [INFO]  Epoch[4] Train-cross-entropy=10.706051
2020-06-09 14:59:35,185 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:35,189 [INFO]  Epoch[4] Time cost=0.081
2020-06-09 14:59:35,196 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:35,215 [INFO]  Epoch[4] Validation-cross-entropy=59.251335
2020-06-09 14:59:35,219 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:35,271 [INFO]  Epoch[5] Batch [0-2]	Speed: 1015.68 samples/sec	cross-entropy=13.966985	RH-accuracy=0.000000
2020-06-09 14:59:35,291 [INFO]  Epoch[5] Train-cross-entropy=10.593407
2020-06-09 14:59:35,296 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:35,301 [INFO]  Epoch[5] Time cost=0.078
2020-06-09 14:59:35,308 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:35,330 [INFO]  No improvement detected for 5 epochs compared to 42.09535217285156 last error obtained: 56.97907257080078, stopping here
2020-06-09 14:59:35,334 [INFO]
========== done (0.7191226482391357 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

13 rows have been imputed

2020-06-09 14:59:35,645 [INFO]
========== start: fit model
2020-06-09 14:59:35,652 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:35,690 [INFO]  Epoch[0] Batch [0-1]	Speed: 1012.14 samples/sec	cross-entropy=50.784730	RH-accuracy=0.000000
2020-06-09 14:59:35,695 [INFO]  Epoch[0] Train-cross-entropy=50.784730
2020-06-09 14:59:35,699 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:35,703 [INFO]  Epoch[0] Time cost=0.047
2020-06-09 14:59:35,710 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:35,728 [INFO]  Epoch[0] Validation-cross-entropy=2.019684
2020-06-09 14:59:35,733 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:35,771 [INFO]  Epoch[1] Batch [0-1]	Speed: 993.07 samples/sec	cross-entropy=47.382836	RH-accuracy=0.000000
2020-06-09 14:59:35,776 [INFO]  Epoch[1] Train-cross-entropy=47.382836
2020-06-09 14:59:35,781 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:35,785 [INFO]  Epoch[1] Time cost=0.046
2020-06-09 14:59:35,791 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:35,810 [INFO]  Epoch[1] Validation-cross-entropy=1.154674
2020-06-09 14:59:35,814 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:35,850 [INFO]  Epoch[2] Batch [0-1]	Speed: 1018.62 samples/sec	cross-entropy=44.451321	RH-accuracy=0.000000
2020-06-09 14:59:35,856 [INFO]  Epoch[2] Train-cross-entropy=44.451321
2020-06-09 14:59:35,860 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:35,865 [INFO]  Epoch[2] Time cost=0.047
2020-06-09 14:59:35,871 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:35,891 [INFO]  Epoch[2] Validation-cross-entropy=0.555209
2020-06-09 14:59:35,894 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:35,932 [INFO]  Epoch[3] Batch [0-1]	Speed: 968.33 samples/sec	cross-entropy=41.799943	RH-accuracy=0.000000
2020-06-09 14:59:35,937 [INFO]  Epoch[3] Train-cross-entropy=41.799943
2020-06-09 14:59:35,941 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:35,946 [INFO]  Epoch[3] Time cost=0.047
2020-06-09 14:59:35,954 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:35,973 [INFO]  Epoch[3] Validation-cross-entropy=0.253149
2020-06-09 14:59:35,979 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:36,020 [INFO]  Epoch[4] Batch [0-1]	Speed: 900.42 samples/sec	cross-entropy=39.466432	RH-accuracy=0.000000
2020-06-09 14:59:36,026 [INFO]  Epoch[4] Train-cross-entropy=39.466432
2020-06-09 14:59:36,032 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:36,037 [INFO]  Epoch[4] Time cost=0.052
2020-06-09 14:59:36,045 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:36,065 [INFO]  Epoch[4] Validation-cross-entropy=0.153988
2020-06-09 14:59:36,070 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:36,108 [INFO]  Epoch[5] Batch [0-1]	Speed: 975.97 samples/sec	cross-entropy=37.441998	RH-accuracy=0.000000
2020-06-09 14:59:36,114 [INFO]  Epoch[5] Train-cross-entropy=37.441998
2020-06-09 14:59:36,119 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:36,123 [INFO]  Epoch[5] Time cost=0.049
2020-06-09 14:59:36,131 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:36,150 [INFO]  Epoch[5] Validation-cross-entropy=0.144885
2020-06-09 14:59:36,155 [INFO]  Epoch[5] Validation-RH-accuracy=0.000000
2020-06-09 14:59:36,192 [INFO]  Epoch[6] Batch [0-1]	Speed: 1020.87 samples/sec	cross-entropy=35.691911	RH-accuracy=0.000000
2020-06-09 14:59:36,196 [INFO]  Epoch[6] Train-cross-entropy=35.691911
2020-06-09 14:59:36,201 [INFO]  Epoch[6] Train-RH-accuracy=0.000000
2020-06-09 14:59:36,205 [INFO]  Epoch[6] Time cost=0.045
2020-06-09 14:59:36,211 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:36,230 [INFO]  Epoch[6] Validation-cross-entropy=0.142310
2020-06-09 14:59:36,234 [INFO]  Epoch[6] Validation-RH-accuracy=0.000000
2020-06-09 14:59:36,271 [INFO]  Epoch[7] Batch [0-1]	Speed: 1009.32 samples/sec	cross-entropy=34.164971	RH-accuracy=0.000000
2020-06-09 14:59:36,276 [INFO]  Epoch[7] Train-cross-entropy=34.164971
2020-06-09 14:59:36,280 [INFO]  Epoch[7] Train-RH-accuracy=0.000000
2020-06-09 14:59:36,284 [INFO]  Epoch[7] Time cost=0.045
2020-06-09 14:59:36,290 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:59:36,313 [INFO]  Epoch[7] Validation-cross-entropy=0.119056
2020-06-09 14:59:36,318 [INFO]  Epoch[7] Validation-RH-accuracy=0.000000
2020-06-09 14:59:36,361 [INFO]  Epoch[8] Batch [0-1]	Speed: 882.08 samples/sec	cross-entropy=32.822905	RH-accuracy=0.000000
2020-06-09 14:59:36,366 [INFO]  Epoch[8] Train-cross-entropy=32.822905
2020-06-09 14:59:36,370 [INFO]  Epoch[8] Train-RH-accuracy=0.000000
2020-06-09 14:59:36,375 [INFO]  Epoch[8] Time cost=0.052
2020-06-09 14:59:36,381 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-09 14:59:36,400 [INFO]  Epoch[8] Validation-cross-entropy=0.106668
2020-06-09 14:59:36,405 [INFO]  Epoch[8] Validation-RH-accuracy=0.000000
2020-06-09 14:59:36,442 [INFO]  Epoch[9] Batch [0-1]	Speed: 1007.75 samples/sec	cross-entropy=31.630214	RH-accuracy=0.000000
2020-06-09 14:59:36,446 [INFO]  Epoch[9] Train-cross-entropy=31.630214
2020-06-09 14:59:36,451 [INFO]  Epoch[9] Train-RH-accuracy=0.000000
2020-06-09 14:59:36,454 [INFO]  Epoch[9] Time cost=0.045
2020-06-09 14:59:36,461 [INFO]  Saved checkpoint to "datawig_imputation/model-0009.params"
2020-06-09 14:59:36,480 [INFO]  Epoch[9] Validation-cross-entropy=0.187857
2020-06-09 14:59:36,483 [INFO]  Epoch[9] Validation-RH-accuracy=0.000000
2020-06-09 14:59:36,522 [INFO]  Epoch[10] Batch [0-1]	Speed: 945.26 samples/sec	cross-entropy=30.549914	RH-accuracy=0.000000
2020-06-09 14:59:36,526 [INFO]  Epoch[10] Train-cross-entropy=30.549914
2020-06-09 14:59:36,530 [INFO]  Epoch[10] Train-RH-accuracy=0.000000
2020-06-09 14:59:36,534 [INFO]  Epoch[10] Time cost=0.046
2020-06-09 14:59:36,540 [INFO]  Saved checkpoint to "datawig_imputation/model-0010.params"
2020-06-09 14:59:36,558 [INFO]  Epoch[10] Validation-cross-entropy=0.484403
2020-06-09 14:59:36,562 [INFO]  Epoch[10] Validation-RH-accuracy=0.000000
2020-06-09 14:59:36,599 [INFO]  Epoch[11] Batch [0-1]	Speed: 1014.60 samples/sec	cross-entropy=29.567641	RH-accuracy=0.000000
2020-06-09 14:59:36,603 [INFO]  Epoch[11] Train-cross-entropy=29.567641
2020-06-09 14:59:36,607 [INFO]  Epoch[11] Train-RH-accuracy=0.000000
2020-06-09 14:59:36,611 [INFO]  Epoch[11] Time cost=0.045
2020-06-09 14:59:36,618 [INFO]  Saved checkpoint to "datawig_imputation/model-0011.params"
2020-06-09 14:59:36,636 [INFO]  Epoch[11] Validation-cross-entropy=1.129090
2020-06-09 14:59:36,640 [INFO]  Epoch[11] Validation-RH-accuracy=0.000000
2020-06-09 14:59:36,678 [INFO]  Epoch[12] Batch [0-1]	Speed: 974.22 samples/sec	cross-entropy=28.660155	RH-accuracy=0.000000
2020-06-09 14:59:36,683 [INFO]  Epoch[12] Train-cross-entropy=28.660155
2020-06-09 14:59:36,688 [INFO]  Epoch[12] Train-RH-accuracy=0.000000
2020-06-09 14:59:36,692 [INFO]  Epoch[12] Time cost=0.047
2020-06-09 14:59:36,699 [INFO]  Saved checkpoint to "datawig_imputation/model-0012.params"
2020-06-09 14:59:36,717 [INFO]  No improvement detected for 5 epochs compared to 0.11905559152364731 last error obtained: 2.2364068031311035, stopping here
2020-06-09 14:59:36,722 [INFO]
========== done (1.0776572227478027 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

32 rows have been imputed

2020-06-09 14:59:37,006 [INFO]
========== start: fit model
2020-06-09 14:59:37,011 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:37,052 [INFO]  Epoch[0] Batch [0-1]	Speed: 1011.24 samples/sec	cross-entropy=16.811348	RH-accuracy=0.000000
2020-06-09 14:59:37,057 [INFO]  Epoch[0] Train-cross-entropy=16.811348
2020-06-09 14:59:37,061 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,065 [INFO]  Epoch[0] Time cost=0.049
2020-06-09 14:59:37,071 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:37,089 [INFO]  Epoch[0] Validation-cross-entropy=50.148392
2020-06-09 14:59:37,093 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:37,128 [INFO]  Epoch[1] Batch [0-1]	Speed: 1033.16 samples/sec	cross-entropy=16.168075	RH-accuracy=0.000000
2020-06-09 14:59:37,133 [INFO]  Epoch[1] Train-cross-entropy=16.168075
2020-06-09 14:59:37,137 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,140 [INFO]  Epoch[1] Time cost=0.044
2020-06-09 14:59:37,147 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:37,165 [INFO]  Epoch[1] Validation-cross-entropy=50.224617
2020-06-09 14:59:37,169 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:37,205 [INFO]  Epoch[2] Batch [0-1]	Speed: 1011.64 samples/sec	cross-entropy=15.942065	RH-accuracy=0.000000
2020-06-09 14:59:37,210 [INFO]  Epoch[2] Train-cross-entropy=15.942065
2020-06-09 14:59:37,215 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,220 [INFO]  Epoch[2] Time cost=0.047
2020-06-09 14:59:37,227 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:37,245 [INFO]  Epoch[2] Validation-cross-entropy=49.138805
2020-06-09 14:59:37,250 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:37,287 [INFO]  Epoch[3] Batch [0-1]	Speed: 991.69 samples/sec	cross-entropy=15.806442	RH-accuracy=0.000000
2020-06-09 14:59:37,292 [INFO]  Epoch[3] Train-cross-entropy=15.806442
2020-06-09 14:59:37,297 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,301 [INFO]  Epoch[3] Time cost=0.046
2020-06-09 14:59:37,307 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:37,326 [INFO]  Epoch[3] Validation-cross-entropy=47.805988
2020-06-09 14:59:37,330 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:37,371 [INFO]  Epoch[4] Batch [0-1]	Speed: 855.59 samples/sec	cross-entropy=15.761049	RH-accuracy=0.000000
2020-06-09 14:59:37,376 [INFO]  Epoch[4] Train-cross-entropy=15.761049
2020-06-09 14:59:37,381 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,385 [INFO]  Epoch[4] Time cost=0.051
2020-06-09 14:59:37,392 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:37,412 [INFO]  Epoch[4] Validation-cross-entropy=46.602657
2020-06-09 14:59:37,416 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:37,452 [INFO]  Epoch[5] Batch [0-1]	Speed: 1024.16 samples/sec	cross-entropy=15.753623	RH-accuracy=0.000000
2020-06-09 14:59:37,457 [INFO]  Epoch[5] Train-cross-entropy=15.753623
2020-06-09 14:59:37,460 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,465 [INFO]  Epoch[5] Time cost=0.045
2020-06-09 14:59:37,472 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:37,490 [INFO]  Epoch[5] Validation-cross-entropy=45.686150
2020-06-09 14:59:37,495 [INFO]  Epoch[5] Validation-RH-accuracy=0.000000
2020-06-09 14:59:37,539 [INFO]  Epoch[6] Batch [0-1]	Speed: 1009.61 samples/sec	cross-entropy=15.748106	RH-accuracy=0.000000
2020-06-09 14:59:37,544 [INFO]  Epoch[6] Train-cross-entropy=15.748106
2020-06-09 14:59:37,548 [INFO]  Epoch[6] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,552 [INFO]  Epoch[6] Time cost=0.048
2020-06-09 14:59:37,558 [INFO]  Saved checkpoint to "datawig_imputation/model-0006.params"
2020-06-09 14:59:37,578 [INFO]  Epoch[6] Validation-cross-entropy=45.097584
2020-06-09 14:59:37,583 [INFO]  Epoch[6] Validation-RH-accuracy=0.000000
2020-06-09 14:59:37,620 [INFO]  Epoch[7] Batch [0-1]	Speed: 1006.67 samples/sec	cross-entropy=15.742908	RH-accuracy=0.000000
2020-06-09 14:59:37,625 [INFO]  Epoch[7] Train-cross-entropy=15.742908
2020-06-09 14:59:37,629 [INFO]  Epoch[7] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,633 [INFO]  Epoch[7] Time cost=0.046
2020-06-09 14:59:37,639 [INFO]  Saved checkpoint to "datawig_imputation/model-0007.params"
2020-06-09 14:59:37,658 [INFO]  Epoch[7] Validation-cross-entropy=44.817474
2020-06-09 14:59:37,663 [INFO]  Epoch[7] Validation-RH-accuracy=0.000000
2020-06-09 14:59:37,700 [INFO]  Epoch[8] Batch [0-1]	Speed: 1019.67 samples/sec	cross-entropy=15.740529	RH-accuracy=0.000000
2020-06-09 14:59:37,705 [INFO]  Epoch[8] Train-cross-entropy=15.740529
2020-06-09 14:59:37,709 [INFO]  Epoch[8] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,713 [INFO]  Epoch[8] Time cost=0.045
2020-06-09 14:59:37,719 [INFO]  Saved checkpoint to "datawig_imputation/model-0008.params"
2020-06-09 14:59:37,737 [INFO]  Epoch[8] Validation-cross-entropy=44.799011
2020-06-09 14:59:37,741 [INFO]  Epoch[8] Validation-RH-accuracy=0.000000
2020-06-09 14:59:37,777 [INFO]  Epoch[9] Batch [0-1]	Speed: 1026.19 samples/sec	cross-entropy=15.736058	RH-accuracy=0.000000
2020-06-09 14:59:37,782 [INFO]  Epoch[9] Train-cross-entropy=15.736058
2020-06-09 14:59:37,786 [INFO]  Epoch[9] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,790 [INFO]  Epoch[9] Time cost=0.045
2020-06-09 14:59:37,797 [INFO]  Saved checkpoint to "datawig_imputation/model-0009.params"
2020-06-09 14:59:37,815 [INFO]  Epoch[9] Validation-cross-entropy=44.983482
2020-06-09 14:59:37,820 [INFO]  Epoch[9] Validation-RH-accuracy=0.000000
2020-06-09 14:59:37,857 [INFO]  Epoch[10] Batch [0-1]	Speed: 1013.85 samples/sec	cross-entropy=15.724282	RH-accuracy=0.000000
2020-06-09 14:59:37,862 [INFO]  Epoch[10] Train-cross-entropy=15.724282
2020-06-09 14:59:37,868 [INFO]  Epoch[10] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,872 [INFO]  Epoch[10] Time cost=0.048
2020-06-09 14:59:37,879 [INFO]  Saved checkpoint to "datawig_imputation/model-0010.params"
2020-06-09 14:59:37,898 [INFO]  Epoch[10] Validation-cross-entropy=45.316013
2020-06-09 14:59:37,903 [INFO]  Epoch[10] Validation-RH-accuracy=0.000000
2020-06-09 14:59:37,940 [INFO]  Epoch[11] Batch [0-1]	Speed: 1019.85 samples/sec	cross-entropy=15.707994	RH-accuracy=0.000000
2020-06-09 14:59:37,945 [INFO]  Epoch[11] Train-cross-entropy=15.707994
2020-06-09 14:59:37,949 [INFO]  Epoch[11] Train-RH-accuracy=0.000000
2020-06-09 14:59:37,954 [INFO]  Epoch[11] Time cost=0.046
2020-06-09 14:59:37,960 [INFO]  Saved checkpoint to "datawig_imputation/model-0011.params"
2020-06-09 14:59:37,979 [INFO]  Epoch[11] Validation-cross-entropy=45.736656
2020-06-09 14:59:37,983 [INFO]  Epoch[11] Validation-RH-accuracy=0.000000
2020-06-09 14:59:38,022 [INFO]  Epoch[12] Batch [0-1]	Speed: 883.43 samples/sec	cross-entropy=15.693392	RH-accuracy=0.000000
2020-06-09 14:59:38,027 [INFO]  Epoch[12] Train-cross-entropy=15.693392
2020-06-09 14:59:38,032 [INFO]  Epoch[12] Train-RH-accuracy=0.000000
2020-06-09 14:59:38,036 [INFO]  Epoch[12] Time cost=0.049
2020-06-09 14:59:38,042 [INFO]  Saved checkpoint to "datawig_imputation/model-0012.params"
2020-06-09 14:59:38,062 [INFO]  No improvement detected for 5 epochs compared to 44.817474365234375 last error obtained: 46.216407775878906, stopping here
2020-06-09 14:59:38,066 [INFO]
========== done (1.060384750366211 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

32 rows have been imputed

2020-06-09 14:59:38,352 [INFO]
========== start: fit model
2020-06-09 14:59:38,356 [WARNING]  Already bound, ignoring bind()
2020-06-09 14:59:38,420 [INFO]  Epoch[0] Batch [0-2]	Speed: 1001.33 samples/sec	cross-entropy=16.361950	RH-accuracy=0.000000
2020-06-09 14:59:38,425 [INFO]  Epoch[0] Train-cross-entropy=16.361950
2020-06-09 14:59:38,430 [INFO]  Epoch[0] Train-RH-accuracy=0.000000
2020-06-09 14:59:38,434 [INFO]  Epoch[0] Time cost=0.068
2020-06-09 14:59:38,441 [INFO]  Saved checkpoint to "datawig_imputation/model-0000.params"
2020-06-09 14:59:38,460 [INFO]  Epoch[0] Validation-cross-entropy=15.880401
2020-06-09 14:59:38,465 [INFO]  Epoch[0] Validation-RH-accuracy=0.000000
2020-06-09 14:59:38,518 [INFO]  Epoch[1] Batch [0-2]	Speed: 990.86 samples/sec	cross-entropy=15.589709	RH-accuracy=0.000000
2020-06-09 14:59:38,523 [INFO]  Epoch[1] Train-cross-entropy=15.589709
2020-06-09 14:59:38,528 [INFO]  Epoch[1] Train-RH-accuracy=0.000000
2020-06-09 14:59:38,532 [INFO]  Epoch[1] Time cost=0.063
2020-06-09 14:59:38,538 [INFO]  Saved checkpoint to "datawig_imputation/model-0001.params"
2020-06-09 14:59:38,557 [INFO]  Epoch[1] Validation-cross-entropy=17.014980
2020-06-09 14:59:38,562 [INFO]  Epoch[1] Validation-RH-accuracy=0.000000
2020-06-09 14:59:38,618 [INFO]  Epoch[2] Batch [0-2]	Speed: 961.33 samples/sec	cross-entropy=15.584965	RH-accuracy=0.000000
2020-06-09 14:59:38,624 [INFO]  Epoch[2] Train-cross-entropy=15.584965
2020-06-09 14:59:38,628 [INFO]  Epoch[2] Train-RH-accuracy=0.000000
2020-06-09 14:59:38,632 [INFO]  Epoch[2] Time cost=0.064
2020-06-09 14:59:38,639 [INFO]  Saved checkpoint to "datawig_imputation/model-0002.params"
2020-06-09 14:59:38,658 [INFO]  Epoch[2] Validation-cross-entropy=17.669565
2020-06-09 14:59:38,663 [INFO]  Epoch[2] Validation-RH-accuracy=0.000000
2020-06-09 14:59:38,714 [INFO]  Epoch[3] Batch [0-2]	Speed: 1007.24 samples/sec	cross-entropy=15.729202	RH-accuracy=0.000000
2020-06-09 14:59:38,719 [INFO]  Epoch[3] Train-cross-entropy=15.729202
2020-06-09 14:59:38,723 [INFO]  Epoch[3] Train-RH-accuracy=0.000000
2020-06-09 14:59:38,727 [INFO]  Epoch[3] Time cost=0.061
2020-06-09 14:59:38,734 [INFO]  Saved checkpoint to "datawig_imputation/model-0003.params"
2020-06-09 14:59:38,752 [INFO]  Epoch[3] Validation-cross-entropy=17.302082
2020-06-09 14:59:38,757 [INFO]  Epoch[3] Validation-RH-accuracy=0.000000
2020-06-09 14:59:38,810 [INFO]  Epoch[4] Batch [0-2]	Speed: 989.68 samples/sec	cross-entropy=15.696235	RH-accuracy=0.000000
2020-06-09 14:59:38,816 [INFO]  Epoch[4] Train-cross-entropy=15.696235
2020-06-09 14:59:38,821 [INFO]  Epoch[4] Train-RH-accuracy=0.000000
2020-06-09 14:59:38,825 [INFO]  Epoch[4] Time cost=0.065
2020-06-09 14:59:38,832 [INFO]  Saved checkpoint to "datawig_imputation/model-0004.params"
2020-06-09 14:59:38,850 [INFO]  Epoch[4] Validation-cross-entropy=16.756250
2020-06-09 14:59:38,855 [INFO]  Epoch[4] Validation-RH-accuracy=0.000000
2020-06-09 14:59:38,907 [INFO]  Epoch[5] Batch [0-2]	Speed: 1019.39 samples/sec	cross-entropy=15.635357	RH-accuracy=0.000000
2020-06-09 14:59:38,912 [INFO]  Epoch[5] Train-cross-entropy=15.635357
2020-06-09 14:59:38,916 [INFO]  Epoch[5] Train-RH-accuracy=0.000000
2020-06-09 14:59:38,920 [INFO]  Epoch[5] Time cost=0.061
2020-06-09 14:59:38,927 [INFO]  Saved checkpoint to "datawig_imputation/model-0005.params"
2020-06-09 14:59:38,946 [INFO]  No improvement detected for 5 epochs compared to 15.880400657653809 last error obtained: 16.610872268676758, stopping here
2020-06-09 14:59:38,949 [INFO]
========== done (0.597437858581543 s) fit model
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

25 rows have been imputed

In [0]:
# 3.Appending all years back
imputed_year_dflist = [yr_2016_overall, yr_2017_overall, yr_2018_overall,
                       yr_2019_overall, yr_2020_overall]
chennai_combined_data2 = pd.DataFrame()

In [0]:
for imputed_df in imputed_year_dflist:
    chennai_combined_data2 = chennai_combined_data2.append(imputed_df)

In [68]:
chennai_combined_data2['PM_updated'].mean(axis = 0, skipna = True)

45.434255911546096

In [69]:
chennai_combined_data2['PM2.5'].replace(0, np.NaN, inplace = True)
chennai_combined_data2['PM2.5'].mean(axis = 0, skipna = True)

48.38841095890415

In [70]:
chennai_combined_data2['RH_updated'].mean(axis = 0, skipna = True)

58.11690366931941

In [71]:
chennai_combined_data2['RH'].replace(0, np.NaN, inplace = True)
chennai_combined_data2['RH'].mean(axis = 0, skipna = True)

54.60396551724141

In [0]:
#Corrected PM and corrected RH

In [0]:
chennai_combined_data2.to_csv('chennai_overall_data.csv')